pancakeswap/pancake-frontend

src/views/Ifos/components/IfoCard/index.tsx
=> fix: Claim button on IFO

src/views/Farms/Farms.tsx
=> chore: Remove a button on the farm page

package.json, src/views/Farm/components/Harvest.tsx, src/views/Farm/components/Image.tsx, src/views/Farm/components/Stake.tsx, src/views/Farms/Farms.tsx, src/views/Farms/components/FarmCard.tsx, src/views/Ifos/CurrentIfo.tsx, src/views/Lottery/components/HowItWorks.tsx, src/views/Lottery/components/WinningNumbers.tsx, src/views/Pools/components/CardTokenImg.tsx, src/views/Pools/components/Coming.tsx, src/views/Pools/components/PoolCard.tsx, yarn.lock
Implement the images lazy loading components from the uikit.
=> perf: Lazyload images

src/config/constants/farms.ts
Deploy time: 3:55pm SGT (4:55pm JST)
=> chore: Add front farm

public/index.html, src/views/Farms/Farms.tsx, src/views/Farms/components/FarmCard.tsx, src/views/Pools/components/Coming.tsx
A batch of small fixes for lighthouse errors
=> chore: Fix some lighthouse issues

netlify.toml
Did not account for branches from forks.
=> build: Add wildcard to handle forked branches

src/components/Menu/config.ts
=> fix: Pool menu link

src/config/constants/farms.ts, src/views/Lottery/components/TicketCard/BuyTicketModal.tsx, src/views/Lottery/components/TicketCard/TicketActions.tsx
update helmet farm to 1X multiplier
Add two button IDs for lottery ticket purchases
=> chore: Helmet to 1x + IDs for lottery

src/hooks/useTickets.ts
Removed some of the unnecessary dependency on account with the lottery data
=> feat(lottery): Remove account dependency

src/config/constants/ifo.ts
=> fix: update cake to burn

src/hooks/api.ts, src/views/Home/Home.tsx, src/views/Home/components/CakeStats.tsx, src/views/Home/components/FarmStakingCard.tsx, src/views/Home/components/LotteryCard.tsx, src/views/Home/components/TotalValueLockedCard.tsx
=> feat(dashboard): Add TVL

src/views/Home/components/CakeHarvestBalance.tsx, src/views/Home/components/CakeWalletBalance.tsx, src/views/Home/components/CardValue.tsx, src/views/Home/components/FarmStakingCard.tsx, src/views/Home/components/LotteryCard.tsx, src/views/Home/components/TotalValueLockedCard.tsx, src/views/Pools/Syrup.tsx
Fix layout content shift problems
=> style: Fix Layout shift ATF

src/App.tsx, src/config/abi/pancakeProfile.json, src/config/constants/contracts.ts, src/state/actions.ts, src/state/hooks.ts, src/state/index.ts, src/state/profile/getProfile.ts, src/state/profile/index.tsx, src/state/types.ts, src/utils/addressHelpers.ts, src/views/Teams/index.tsx
Sets up basic redux structure based on the data we have
=> feat(profile): Redux structure

src/utils/contractHelpers.ts, src/views/Profile/ProfileCreation/TeamSelection.tsx, src/views/Profile/ProfileCreation/index.tsx, src/views/Profile/components/SelectionCard.tsx, src/views/Profile/index.tsx
=> feat: Select a team (mock)

src/views/Profile/ProfileCreation/TeamSelection.tsx, src/views/Profile/components/SelectionCard.tsx
=> feat: Fetch teams

src/config/constants/farms.ts
=> fix(farms): Remove wrong farm

src/config/constants/farms.ts
=> Deploy 24:00 JST

.env, .gitignore, src/App.tsx, src/views/Profile/ProfileCreation/Steps.tsx, src/views/Profile/ProfileCreation/UserName.tsx, src/views/Profile/ProfileCreation/contexts/ProfileCreationProvider.tsx, src/views/Profile/ProfileCreation/contexts/hook.ts, src/views/Profile/ProfileCreation/contexts/types.ts
Username selection and profile validation
=> feat: Add username selection and profile creation

src/hooks/useLotteryTotalPrizesUsd.ts
Adds a hook to get the total prize amount in USD
=> feat: Lottery amountin USD hook

src/hooks/useContract.ts, src/views/Profile/ProfileCreation/Mint.tsx, src/views/Profile/ProfileCreation/ProfilePicture.tsx, src/views/Profile/ProfileCreation/UserName.tsx
=> fix: Profile creation

package.json, src/config/abi/pancakeProfile.json, src/config/constants/contracts.ts, yarn.lock
=> feat(profile): Update profile contract address

package.json, yarn.lock
=> build: Bump uikit to 0.9.5

src/views/Home/Home.tsx, src/views/Home/components/EarnAPYCard.tsx, src/views/Home/components/EarnAssetCard.tsx, src/views/Home/components/WinCard.tsx
Moved the new UI Cards to the center and adjusted spacing
=> style(home): Rearranged cards

src/views/Home/components/EarnAssetCard.tsx
=> feat(home): Update asset list

package.json, src/components/Menu/index.tsx, src/state/hooks.ts, src/views/Profile/ProfileCreation/ProfilePicture.tsx, src/views/Profile/ProfileCreation/Steps.tsx, src/views/Profile/PublicProfile.tsx, src/views/Profile/TaskCenter.tsx, src/views/Profile/components/ComingSoon.tsx, src/views/Profile/components/Header.tsx, src/views/Profile/components/Menu.tsx, src/views/Profile/components/WalletNotConnected.tsx, src/views/Profile/index.tsx, yarn.lock
=> feat(profile): Added tasks placeholder

src/App.tsx, src/config/constants/nfts.ts, src/hooks/useTeams.ts, src/state/types.ts, src/views/Profile/ProfileCreation/TeamSelection.tsx, src/views/Profile/PublicProfile.tsx, src/views/Profile/components/Header.tsx, src/views/Profile/components/HeaderWrapper.tsx, src/views/Profile/components/StatBox.tsx, src/views/Teams/Team.tsx, src/views/Teams/components/TeamCard.tsx, src/views/Teams/components/TeamHeader.tsx, src/views/Teams/components/TeamListCard.tsx, src/views/Teams/index.tsx
=> feat(teams): Team overview

src/views/Profile/ProfileCreation/UserName.tsx
=> feat: Added acknoledgement

src/views/Profile/ProfileCreation/UserName.tsx
Add support for BSC wallet signature
=> Bsc wallet sign

package.json, src/components/Menu/index.tsx, yarn.lock
=> build: Upgrade UI Kit

src/state/hooks.ts, src/views/Farms/Farms.tsx
Quick fix for ETH farms.
To be removed when the WSS will be live.
=> fix: Quickfix for ETH quote token

src/config/abi/claimRefund.json, src/config/constants/contracts.ts, src/utils/addressHelpers.ts, src/views/Profile/components/ClaimGiftModal.tsx, src/views/Profile/components/Header.tsx
=> Nft refund

src/utils/addressHelpers.ts, src/views/Home/components/EarnAssetCard.tsx
=> fix: Address helper

src/components/Menu/index.tsx
- Fixes issue when removing NFT image
=> fix: Undefined profile nft

src/views/Pools/Syrup.tsx
=> fix: Comp APY

src/config/constants/pools.ts
- Set old Comp pool to finished
- Launch new Comp pool
- Update various pools to isFinished `true`
- Update ordering to fix visual glitches on frontend
=> chore: Pool updates

src/views/Lottery/Lottery.tsx
=> chore: Add temporary message for lottery

src/hooks/useTheme.ts, src/views/Farms/Farms.tsx, src/views/Farms/components/FarmTabButtons/index.tsx, src/views/Pools/Syrup.tsx, src/views/Pools/components/PoolTabButtons/index.tsx
Filtering farming pools & farms
New filter button 'farming' between active & inactive
=> feat: Filtering farming pools & farms

src/views/Home/components/EarnAssetCard.tsx
=> fix(home): Remove duplicate CAKE

src/config/index.ts, src/utils/lotteryUtils.js, src/views/Lottery/components/HowItWorks.tsx, src/views/Lottery/components/PastLotteryRoundViewer/PastRoundCardDetails.tsx, src/views/Lottery/components/PrizeGrid.tsx, src/views/Lottery/components/TicketCard/BuyTicketModal.tsx, src/views/Lottery/components/WinningNumbers.tsx
=> fix: Lottery matching numbers

CONTRIBUTING.md
Fixes minor typos in the CONTRIBUTING.md file
- Projet -> Project
- Dyanamic -> Dynamic
=> fix: typos in contributing document

src/views/Lottery/components/HowItWorks.tsx, src/views/Lottery/components/PrizeGrid.tsx, src/views/Lottery/components/WinningNumbers.tsx
=> chore: Remove 1 matching ticket from lottery

src/views/Lottery/components/PrizeGrid.tsx
=> fix: Put lottery burn at 20%

src/utils/lotteryUtils.js
ParseInt is done on the wrong variable.
Using BigNumber to be sure there is no problem.
=> fix: Number of tickets bought

src/config/constants/farms.ts, src/config/constants/pools.ts
Farm: Stake BRY-WBNB LP Tokens, Earn CAKE
2x CAKE rewards for the first 48 hours and then 1x CAKE rewards after that.
Start block: 4928180 (Feb 16th 6PM SGT)
BRY-WBNB LP Token Contract:
Pool: Stake CAKE, Earn BRY
Total Tokens: 200,000 BRY
Distribution duration: 60 days
Start block: 4928180 (Feb 16th 6PM SGT)
Finish block: 6656180 (April 16th 6PM SGT)
Token rewards per block: 0.1157 BRY
=> feat (farm/pool): Add BRY

src/views/Ifos/CurrentIfo.tsx
=> feat: Warning IFO

src/views/Home/components/CakeWinnings.tsx, src/views/Home/components/CardBusdValue.tsx
=> fix: USD amount on CAKE winnings

src/views/Profile/ProfileCreation/Mint.tsx, src/views/Profile/ProfileCreation/UserName.tsx, src/views/Profile/ProfileCreation/config.ts, src/views/Profile/ProfileCreation/contexts/ProfileCreationProvider.tsx, src/views/Profile/components/ConfirmProfileCreationModal.tsx
Changes in the FE in response to the new prices
=> chore(profile): Update CAKE price

src/config/constants/nfts.ts
=> fix(nft): Hiccup ipfs link

src/views/Profile/components/ClaimPointsCallout .tsx
Fixes error where if you landed on the task center directly it crash
=> fix: Error with null profile

package.json, yarn.lock
=> build: Update UI Kit

src/views/Profile/components/AchievementsList.tsx
Fix typo in Profile, for tasks achievements.
=> fix: Typo for profile tasks

.github/workflows/lint.yml
=> ci: Add commit lint to GH Actions

src/config/constants/pools.ts
=> fix: Pool sous ID

package.json, src/App.tsx, src/components/EasterEgg/EasterEgg.tsx, src/components/EasterEgg/index.ts, yarn.lock
Add EasterEgg feature (falling bunnies).
use components from this PR https://github.com/pancakeswap/pancake-uikit/pull/192
=> Bounty: easter-egg feature

src/views/Ifos/components/IfoCard/BalanceInUsd.tsx, src/views/Ifos/components/IfoCard/Claim.tsx, src/views/Ifos/components/IfoCard/IfoCardActions.tsx, src/views/Ifos/components/IfoCard/MetaLabel.tsx, src/views/Ifos/hooks/useGetWalletIfoData.ts
- Hide reward price if claimed
=> feat(ifo): Add refunding amount

src/views/Farms/components/FarmCard/FarmCard.tsx
feat: Set FarmCard animation shadow border-radius value to FarmCard border-radius value
[x] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[x] Before requesting a review, all the checks need to pass
[x] Explain what your PR does
Everything is explained in this issue https://github.com/pancakeswap/pancake-frontend/issues/538 .
closes #538
=> feat: Set FarmCard animation shadow border-radius value

package.json, src/hooks/useAuth.ts, src/hooks/useEagerConnect.ts, src/utils/web3React.ts, yarn.lock
=> fix: Eager connect based on connector

package.json, yarn.lock
=> build: Bump uikit to 0.13.1

src/components/TokenInput/TokenInput.tsx
=> Removed unnecessary styled components

src/App.tsx, src/components/SuspenseWithChunkError/index.tsx
Fixes the issue where if you have the app open, and an update is pushed, the next route you visit will throw an error resulting in a white screen.
=> feat: Auto reload when app updates

src/views/Ifos/components/IfoCard/ContributeModal.tsx, yarn.lock
=> chore(ifo): Add text to IFO contribute modal

src/__tests__/unit/apy.test.ts, src/utils/apy.ts, src/views/Pools/Syrup.tsx, src/views/Pools/components/CardFooter.tsx, src/views/Pools/components/PoolCard.tsx
=> chore: Remove dirty code for pools APY

src/hooks/useEagerConnect.ts
=> fix: Skip login if no connector

src/hooks/useAuth.ts, src/utils/getFarmConfig.ts, src/utils/getRpcUrl.ts, src/utils/wallet.ts
Auto add BSC network to metamask
=> feat: Prompt to add BSC network to user wallet

package.json, src/views/Pools/components/PoolCard.tsx, yarn.lock
=> fix(pool): Add icon

src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
=> fix: Lint warning in ActionPanel

src/__tests__/config/contracts.test.ts, src/__tests__/config/farms.test.ts, src/__tests__/config/ifo.test.ts, src/__tests__/config/pools.test.ts
Fix tests formatting, and fix a bug on the LP address test
=> test: Update messages and fix a bug

src/utils/wallet.ts
=> fix: Network name when add on metamask

src/config/constants/pools.ts
Disable a finished pool, users were still able to stake
=> fix: Finished pool in config

src/views/Farms/components/FarmCard/HarvestAction.tsx, src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx, src/views/Farms/components/FarmTable/Earned.tsx
=> fix: Farm earnings still visible after disconnect from wallet

src/config/constants/farms.ts
=> fix: BUNNY

.github/CODEOWNERS
=> chore: Add ChefKai to codeowners

src/views/Lottery/components/HowItWorks.tsx, src/views/Lottery/components/WinningNumbers.tsx
=> fix: Lottery translations

src/views/Home/components/FarmStakingCard.tsx
=> fix: Harvest all translation in homepage

src/config/constants/contracts.ts, src/config/constants/tokens.ts, src/config/constants/types.ts, src/utils/addressHelpers.ts, src/views/Farms/Farms.tsx, src/views/Farms/components/FarmCard/FarmCard.tsx, src/views/Farms/components/FarmTable/Apr.tsx, src/views/Home/components/EarnAPYCard.tsx, src/views/Pools/components/PoolCard.tsx
Remove config which became obsolete after the token list rework
=> chore: Remove unused config related to tokens

src/utils/getLiquidityUrlPathParts.ts
=> fix: Farms liquidity links

src/__tests__/utils/apy.test.ts, src/config/constants/farms.ts, src/config/index.ts, src/state/hooks.ts, src/utils/apy.ts, src/views/Farms/Farms.tsx, src/views/Farms/components/FarmCard/ApyButton.tsx, src/views/Farms/components/FarmCard/ApyCalculatorModal.tsx, src/views/Farms/components/FarmCard/CardActionsContainer.tsx, src/views/Farms/components/FarmCard/FarmCard.tsx, src/views/Farms/components/FarmTable/Apr.tsx, src/views/Home/components/EarnAPYCard.tsx
=> refactor: Farms APY

src/utils/apy.ts, src/views/Home/components/EarnAPYCard.tsx
=> fix: HP max APY

src/views/Home/components/LotteryCard.tsx
=> fix: Lottery card active approve cake button when no wallet is connected

src/utils/getLiquidityUrlPathParts.ts, src/views/Farms/Farms.tsx, src/views/Farms/components/FarmCard/FarmCard.tsx, src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx, src/views/Farms/components/FarmTable/Actions/StakedAction.tsx, src/views/Farms/components/FarmTable/Apr.tsx
=> fix: Get token pair link in farms, apr and staked sections

src/views/Farms/components/FarmTable/Earned.tsx
=> fix: Fix earned text color to disabled (which is still active for the farms that you earn token) after wallet disconnect

src/state/hooks.ts
To avoid the slowrefresh on api fetch
=> fix: Use farms data to get the cake price

.env.test, src/__tests__/config/tokens.test.ts, src/config/constants/tokens.ts
Test token configs against onchain data
=> test: Add tests for token config

src/config/constants/farms.ts, src/config/constants/pools.ts
=> fix: Config tokens names

src/views/Home/components/WinCard.tsx
=> fix: Lottery total prize shows 0 when cake price loading

src/__tests__/config/farms.test.ts, src/__tests__/config/tokens.test.ts, src/config/abi/lpToken.json, src/utils/contractHelpers.ts
=> test: Add onchain tests for farms

src/__tests__/config/pools.test.ts, src/config/abi/sousChef.json
=> test: Onchain pools tests

.env.test
To be sure we always have the same results
=> test: Update env file for more consistency

src/config/constants/pools.ts
**Earn:** bBADGER
**Earn Token Contract Address:**
0x1f7216fdb338247512ec99715587bb97bbf96eae
**Rewards per block:** 0.00265278 bBADGER
**Start block:** 5930020 (March 23rd 7PM SGT)
**End block:** 7658020 (May 22nd 7PM SGT)
**Project website:** https://badger.finance/
**Contract Address:** 0xe4dD0C50fb314A8B2e84D211546F5B57eDd7c2b9
=> feat: Add bBadger pool

src/config/constants/farms.ts, src/config/constants/pools.ts
FARM
--------------
**Stake LP Token:** bBADGER-BTCB LP Token
**LP Token Contract Address:** 0x10F461CEAC7A17F59e249954Db0784d42EfF5DB5
**Earn:** Cake
**Multiplier:** 3x for first 48 hours, then 2x for the next 48 hours, then 1x
**Start block:** 5810500
Pool
--------------
**Earn:** bBADGER
**Earn Token Contract Address:**
0x1f7216fdb338247512ec99715587bb97bbf96eae
**Rewards per block:** 0.00265278 bBADGER
**Start block:** 5930020 (March 23rd 7PM SGT)
**End block:** 7658020 (May 22nd 7PM SGT)
**Project website:** https://badger.finance/
**Contract Address:**0xe4dD0C50fb314A8B2e84D211546F5B57eDd7c2b9
=> feat(farm/pool): BBadger

src/views/Farms/Farms.tsx
=> fix: Build

src/views/Farms/Farms.tsx, src/views/Farms/components/FarmTable/Apr.tsx
=> fix: Apr shows loading in finished farms

src/hooks/useGetPublicIfoData.ts, src/state/block/index.ts, src/state/hooks.ts, src/state/types.ts, src/views/Pools/Syrup.tsx, src/views/Pools/components/CardFooter.tsx
Saves the first loaded block to state
=> feat: Add initial block to redux

src/hooks/useGetBlockCountdown.ts
=> feat: Block countdown hook

src/config/index.ts, src/views/Home/components/CakeStats.tsx
=> chore: Update # of cake per block

src/views/Profile/components/EditProfileModal/StartView.tsx
While the check was correct in checking the proper amount it was not using it for the display message
=> fix: Show correct amount to reactivate

src/hooks/useGetBlockCountdown.ts
A couple issues:
1. Using the `initialBlock`seemed like a good idea but doesn't work well for pages where the use will be on the page longer
2. The timer was prematurely being cleared
=> fix: Block countdown

src/views/Lottery/components/TotalPrizesCard/index.tsx
=> feat: Add busd cake value to lottery page

src/config/constants/contracts.ts
=> chore: Update bunny special contract on testnet

src/hooks/usePrevious.ts, src/hooks/usePreviousValue.ts
https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state
=> feat: Add usePrevious hook

src/config/constants/contracts.ts
Reverts pancakeswap/pancake-frontend#770
Bunny special is actually bunny factory. They will be two separate contracts.
=> Revert "chore: Update bunny special contract on testnet"

src/views/Lottery/components/PrizeGrid.tsx
=> feat: Add usd price of cake for each matched numbers in lottery pot

src/components/Timer/TimerTooltip.tsx, src/components/Timer/index.tsx, src/views/Farms/components/Tooltip/Tooltip.tsx
This is a generic timer component that will render a D, H, M countdown and a tooltip.
UI Example with tooltip while hovered
UI example without tooltip
UI example without using custom text components
Code usage:
```js
<Timer
timerStage={'string that preceeds the timer'}
minutes={'minutes value as number'}
hours={'hours value as number'}
days={'days value as number'}
blockNumber={'number used by the tooltip to show the specific block being counted to'}
showTooltip={'boolean - render or don't render tooltip'}
HeadingTextComponent={'component - allows you to pass a custom header text comp, with sensible defaults'}
BodyTextComponent={'component - allows you to pass a custom body text comp, with sensible defaults'}
/>
```
Code usage example:
```js
const TimerHeadingComponent = ({ children }) => …
```
=> feat(timer): Timer component

src/components/layout/Page.tsx, src/views/TradingCompetition/components/BattleCta/index.tsx, yarn.lock
=> fix(page-styles): Pass className to Page component so it can be restyled

src/views/TradingCompetition/components/PrizesInfo/PrizesText.tsx, src/views/TradingCompetition/components/Rules/FAQs.tsx
=> chore(trading-competition): Update some FAQ / prizes text

src/components/Menu/config.ts
=> chore(trading-competition): Change Trading Comp menu text 'SOON' to 'JOIN'

src/components/layout/Page.tsx
=> fix: Page title shows "false" when loading

src/config/constants/meta.ts
=> chore: Change default image to easter battle

src/hooks/useApprove.ts, src/hooks/useHarvest.ts, src/hooks/useStake.ts, src/hooks/useUnstake.ts, src/state/hooks.ts, src/state/index.ts, src/views/Farms/Farms.tsx, src/views/Profile/components/ClaimPointsCallout .tsx, src/views/Profile/components/ConfirmProfileCreationModal.tsx, src/views/Profile/components/EditProfileModal/ChangeProfilePicView.tsx, src/views/Profile/components/EditProfileModal/PauseProfileView.tsx
https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-dispatch-type
The immediate benefit is Typescript will now see the `dispatch` function as a thunk now.
=> refactor: Typed dispatch

src/config/constants/farms.ts, src/config/constants/pools.ts
FARM
--------------
**Stake LP Token:** HOO-BUSD LP Token
**LP Token Contract Address:** https://bscscan.com/token/0x3c9e55edbd937ae0ad8c084a1a8302110612a371
**Earn:** CAKE
**Multiplier:** 2x for first 48 hours, then 1x
**Start block:** 6328600
POOL
--------------
**Earn:** HOO
**Earn Token Contract Address:** https://bscscan.com/address/0xe1d1f66215998786110ba0102ef558b22224c016
**Rewards per block:** 0.489 HOO
**Start block:** 6328600
**End block:** 8056600
**Token Decimals:** 8
**Project website:** https://hoo.com/
**Contract Address:** 0x47fD853D5baD391899172892F91FAa6d0cd8A2Aa
=> feat(farm/pool): HOO

src/views/Home/components/EarnAPYCard.tsx
=> fix: Fix Farm APR card

src/config/constants/farms.ts, src/config/constants/pools.ts
FARM
--------------
**Stake LP Token:** TKO-BNB LP Token
**LP Token Contract Address:** 0x496a8b716A3A3410B16e71E3c906968CE4488e52
**Earn:** CAKE
**Multiplier:** 3x for first 48 hours, then 1x
**Start block:** 6361600
POOL
--------------
**Earn:** TKO
**Earn Token Contract Address:** https://bscscan.com/token/0x9f589e3eabe42ebc94a44727b3f3531c0c877809
**Rewards per block:** 1.1574 TKO
**Start block:** 6361600
**End block:** 7225600
**Project website:** http://www.tokocrypto.com/ 
**Contract Address:** 0x9bbDc92474a7e7321B78dcDA5EF35f4981438760
=> feat(farm/pool): TKO

src/config/constants/farms.ts, src/config/constants/pools.ts
16:00 JST
FARM
--------------
**Stake LP Token:** BONDLY-BNB LP Token
**LP Token Contract Address:** https://bscscan.com/address/0x67581bfb4fc13bb73c71489b504e9b5354769063
**Earn:** CAKE
**Multiplier:** 2x for first 48 hours, then 1x
**Start block:** 6381500
POOL
--------------
**Earn:** BONDLY
**Earn Token Contract Address:** https://bscscan.com/address/0x96058f8c3e16576d9bd68766f3836d9a33158f89
**Rewards per block:** 0.4629
**Start block:** 6380660
**End block:** 8108660
**Project website:** https://www.bondly.finance/
**Contract Address:** 0x1329ad151dE6C441184E32E108401126AE850937
=> feat(farm/pool): Bondly

src/utils/lotteryUtils.ts
=> fix: Lottery tickets match

src/views/Lottery/components/PastLotteryRoundViewer/PastLotterySearcher.tsx
=> fix: NaN warning and Add numeric keyboard support for ios of past lottery searcher

src/views/TradingCompetition/components/Countdown/ProgressStepper.tsx
=> fix: Progress step key warning

src/components/TicketInput/TicketInput.tsx, src/views/Lottery/components/TicketCard/BuyTicketModal.tsx
Fixes #842 , fixes #843 , fixes #844 , fixes #848
=> fix: Ticket input numeric keyboard, non-integer values, empty value confirm button active

src/components/Timer/TimerTooltip.tsx, src/views/Farms/Farms.tsx, src/views/Home/components/EarnAPYCard.tsx, src/views/TradingCompetition/components/Countdown/index.tsx, src/views/TradingCompetition/components/Section/index.tsx
=> chore: Use absolute url for imports

src/App.tsx
=> chore: Remove global nft claim status

src/components/ModalInput/ModalInput.tsx, src/views/Farms/components/FarmCard/StakeAction.tsx, src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
=> fix: Display stake balance correctly when lp price is too high that causes little lp's staked

src/hooks/useLastUpdated.ts
I noticed in this [PR](https://github.com/pancakeswap/pancake-frontend/pull/873) a force update was added and I have done something similar so this is a utility hook that will achieve it.
=> feat: Last updated hook

src/state/hooks.ts, src/views/Ifos/components/IfoV2Card/Achievement.tsx, src/views/Ifos/components/IfoV2Card/SmallCard/IfoCardDetails.tsx, src/views/Ifos/components/IfoV2Card/index.tsx
=> fix: Prices on IFO

src/views/Ifos/components/IfoV2Card/Achievement.tsx, src/views/Ifos/components/IfoV2Card/SmallCard/IfoCardTokens.tsx
=> fix: Visual bugs on the IFO

src/config/constants/campaigns.ts
=> fix: Achievement title

src/config/constants/ifo.ts, src/config/constants/types.ts, src/hooks/ifo/v2/types.ts, src/hooks/ifo/v2/useGetPublicIfoData.ts, src/views/Ifos/components/IfoV2Card/Achievement.tsx, src/views/Ifos/components/IfoV2Card/SmallCard/IfoCardDetails.tsx, src/views/Ifos/components/IfoV2Card/index.tsx
=> feat(ifo): Add missing data into the config

src/components/FoldableText/index.tsx
=> fix: Foldable text align text with icon

src/views/Farms/components/FarmCard/HarvestAction.tsx
=> feat: Add busd cake price info to farm card

src/hooks/usePersistState.ts, src/views/Farms/Farms.tsx, src/views/Pools/Syrup.tsx
Adds a generic hook to save values to local storage
- Pool card staked only setting
- Farm view and staked setting
=> feat: Hook to save value to local storage

src/hooks/useTickets.ts, src/views/Home/components/CakeWinnings.tsx, src/views/Home/components/LotteryCard.tsx, src/views/Lottery/NextDrawPage.tsx, src/views/Lottery/components/YourPrizesCard/index.tsx
Includes: Fixes #828, fixes #937 and revert margin is fix (because when you win the lottery YourPrizesCard changes places of the children)
=> fix: You won not disappear on lottery page, claim amount not updated on lottery card

src/config/constants/farms.ts, src/config/constants/pools.ts
14:00 deploy
FARM
--------------
**Stake LP Token:** pCGG-BNB LP Token
**LP Token Contract Address:** 0x484c60f6202c8043DCA0236bB3101ada7ec50AD4
**Earn:**
**Multiplier:** 2x for the first 48 hours, then 1x
**Start block:** 6695630
Pool 1
--------------
**Earn:** MIX
**Earn Token Contract Address:** 0xB67754f5b4C704A24d2db68e661b2875a4dDD197
**Rewards per block:** 0.3721 MIX
**Start block:** 6695630
**End block:** 9287630
**Project website:** https://mixie.chainguardians.io/
Pool 2
--------------
**Earn:** pCGG
**Earn Token Contract Address:** …
=> feat(farm/pool): MIX and CGG

src/utils/getLotteryRoundData.ts, src/views/Lottery/components/PastLotteryRoundViewer/PastRoundCardDetails.tsx, src/views/Lottery/components/PrizeGrid.tsx
Response is always null and it is not used anywhere visually
=> refactor: Remove unused and null match1ticket prop

src/views/Profile/PublicProfile.tsx
The icon next to the address should be clickable  #957
Thanks! <3333333
=> fix: Profile icon next to address clickable

src/config/constants/tokens.ts
=> fix: XED ticker

src/components/BlockProgress.tsx
=> style: BlockProgress

src/hooks/useTokenBalance.ts
A hook for getting a wallet's BNB balance
=> feat: Get bnb balance hook

package.json, yarn.lock
=> chore: Bump UI Kit

src/views/Farms/Farms.tsx
Staked only when on the history page
=> feat: Staked only on history page

src/config/constants/pools.ts
=> fix: New tBTC pool

src/components/Banner/Banner.tsx, src/components/Banner/MigrationV2.tsx, src/components/Banner/index.ts, src/components/Menu/config.ts, src/components/layout/Page.tsx
Don't merge before the migration start
=> feat: Add migration banner

src/components/Menu/config.ts
=> chore: Migration menu update

src/components/Menu/config.ts
=> fix: Migration link

src/components/Menu/config.ts
=> chore: Update exchange links

src/views/Farms/Farms.tsx, src/views/Farms/components/FarmTabButtons/index.tsx, src/views/Pools/Syrup.tsx, src/views/Pools/components/PoolTabButtons/index.tsx
=> Add red dot to finished farms and pools

package.json, src/components/Menu/config.ts, yarn.lock
- Update uikit to v 0.28.0
- New trade menu entry
```js
{
label: 'Trade',
icon: 'TradeIcon',
status: {
text: 'MIGRATE',
color: 'warning',
},
items: [
{
label: 'LP Migration',
href: 'https://v1exchange.pancakeswap.finance/#/migrate',
},
{
label: 'Exchange',
href: 'https://v1exchange.pancakeswap.finance',
},
{
label: 'Liquidity',
href: 'https://v1exchange.pancakeswap.finance/#/pool',
},
],
},
```
=> feat(menu-config): Update menu entries and uikit version

src/components/Banner/MigrationV2.tsx
=> Update migration banner message due to delay

src/views/Farms/components/FarmCard/CardActionsContainer.tsx
=> Fix userdata for farm cards

src/components/Banner/MigrationV2.tsx, src/components/Menu/config.ts
=> chore: Rollback banner

src/views/Farms/components/FarmCard/CardActionsContainer.tsx, src/views/Farms/components/FarmCard/StakeAction.tsx, src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
=> chore: Remove staking on V1 farms

src/state/prices/index.ts
v2 endpoint. Same logic, new contracts.
=> feat: API migration v2

src/views/Home/components/LotteryCard.tsx
=> feat: Change disabled buy tickets to on sale soon button on lottery card when lottery has drawn

src/config/constants/farms.ts, src/hooks/ifo/types.ts, src/hooks/ifo/v1/useGetPublicIfoData.ts, src/hooks/ifo/v1/useGetWalletIfoData.ts, src/hooks/ifo/v2/useGetPublicIfoData.ts, src/hooks/ifo/v2/useGetWalletIfoData.ts, src/views/Ifos/CurrentIfo.tsx, src/views/Ifos/components/IfoFoldableCard/Achievement.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeButton.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx, src/views/Ifos/components/IfoSteps.tsx
Remove `addUserContributedAmount` and refetch data instead, in order to avoid data inconsistencies.
=> fix: Ifo blink problems on contribute

src/config/constants/farms.ts, src/config/constants/pools.ts
16:00 deploy
POOL
--------------
**Earn:** DFD
**Earn Token Contract Address:** https://bscscan.com/address/0x9899a98b222fcb2f3dbee7df45d943093a4ff9ff
**Rewards per block:** 0.46296 DFD
**Start block:** 6923600
**End block:** 8651600
**Project website:** https://dusd.finance/
FARM
--------------
**Stake LP Token:** DFD-BUSD LP Token
**LP Token Contract Address:** https://bscscan.com/address/0x029d66f9c0469450b7b4834b8ddc6a1118cec3e1
**Earn:** CAKE
**Multiplier:** 2x for the first 48 hours, then 1x
**Start block:** 6923610
=> feat(farm/pool): DFD

src/hooks/useGetBlockCountdown.ts
This fixes an issue that can arise if the timer is accepting new block numbers to calculate from.
=> refactor: Block countdown hook

src/views/Profile/ProfileCreation/index.tsx, src/views/Profile/index.tsx
=> fix: Fix double banner on profile page

src/state/predictions/helpers.ts
=> fix: Bet count on market poll data

src/views/Predictions/components/RiskDisclaimer.tsx
=> style(predictions): Add scrolling for disclaimer

src/components/Banner/Banner.tsx, src/components/Banner/MigrationV2.tsx, src/components/layout/Page.tsx, src/views/Farms/Farms.tsx, src/views/Profile/ProfileCreation/index.tsx, src/views/Profile/index.tsx, src/views/TradingCompetition/components/Section/index.tsx, src/views/TradingCompetition/index.tsx
First two commits basically revert https://github.com/pancakeswap/pancake-frontend/pull/1016 and https://github.com/pancakeswap/pancake-frontend/pull/987
3rd commits cleans up the rest
=> Remove migration banners (except Farms page)

src/state/hooks.ts
Moved the logic to get the price of BNB in BUSD into its own hook.
=> feat: Hook for getting BNB in BUSD

package.json, src/views/Predictions/Mobile.tsx, yarn.lock
Update the structure of the mobile view on Predictions so all 3 views are loaded.
=> refactor(predictions): Mobile pages hidden instead of unmounted

src/views/Predictions/components/RoundCard/CalculatingCard.tsx, src/views/Predictions/components/RoundCard/CardHeader.tsx, src/views/Predictions/components/RoundCard/LiveRoundCard.tsx, src/views/Predictions/components/RoundCard/MultiplierArrow.tsx, src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
- Displaying calculating card after interval blocks
=> feat(predictions): Calculating card

src/views/Pools/components/CakeVaultCard/UnstakingFeeCountdownRow.tsx
=> chore: Update default text on card when disconnected

src/views/Pools/components/BountyCard.tsx, src/views/Pools/components/BountyModal.tsx, src/views/Pools/components/CakeVaultCard/FeeSummary.tsx, src/views/Pools/components/CakeVaultCard/RecentCakeProfitBalance.tsx, src/views/Pools/components/CakeVaultCard/UnstakingFeeCountdownRow.tsx, src/views/Pools/components/PoolCard/AprRow.tsx, src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx, src/views/Pools/components/PoolCard/CardFooter/index.tsx
=> feat(cake-vault-tooltips): Add tooltips for the vault

package.json, yarn.lock
It contains tooltip on hover disappear immediately fix
=> feat: (uikit) Bump up uikit version to 0.29.2

src/components/Timer/index.tsx, src/views/Farms/components/FarmTable/Liquidity.tsx, src/views/Farms/components/FarmTable/Multiplier.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx, src/views/Pools/components/BountyCard.tsx, src/views/Pools/components/BountyModal.tsx, src/views/Pools/components/CakeVaultCard/FeeSummary.tsx, src/views/Pools/components/CakeVaultCard/RecentCakeProfitBalance.tsx, src/views/Pools/components/CakeVaultCard/UnstakingFeeCountdownRow.tsx, src/views/Pools/components/PoolCard/AprRow.tsx, src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx, src/views/Pools/components/PoolCard/CardFooter/index.tsx, src/views/Pools/components/PoolCard/Modals/CollectModal.tsx, src/views/Predictions/components/RoundCard/EnteredTag.tsx, src/views/Predictions/components/RoundCard/LiveRoundCard.tsx, src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
Bunch of adjustments for tooltips, relies on https://github.com/pancakeswap/pancake-toolkit/pull/91 and new release of UIKit.
=> Tooltip adjustments

src/views/Farms/Farms.tsx
=> fix: Farm sort by earned

src/components/Timer/index.tsx, src/views/Farms/components/FarmTable/Liquidity.tsx, src/views/Farms/components/FarmTable/Multiplier.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx, src/views/Pools/components/BountyCard.tsx, src/views/Pools/components/BountyModal.tsx, src/views/Pools/components/CakeVaultCard/FeeSummary.tsx, src/views/Pools/components/CakeVaultCard/RecentCakeProfitBalance.tsx, src/views/Pools/components/CakeVaultCard/UnstakingFeeCountdownRow.tsx, src/views/Pools/components/PoolCard/AprRow.tsx, src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx, src/views/Pools/components/PoolCard/CardFooter/index.tsx, src/views/Pools/components/PoolCard/Modals/CollectModal.tsx, src/views/Predictions/components/RoundCard/EnteredTag.tsx, src/views/Predictions/components/RoundCard/LiveRoundCard.tsx, src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
Reverts pancakeswap/pancake-frontend#1062
=> Revert "Tooltip adjustments"

crowdin.yml, src/config/localization/languages.ts
=> chore: Update file pattern for Crowdin

crowdin.yml
=> chore: Update crowdin config

src/contexts/Localization/helpers.ts
=> fix: Update key to avoid conflicts with old system

src/config/localization/translations.json, src/views/Predictions/components/RoundCard/SetPositionCard.tsx
=> fix(predictions): Negative numbers when balance is less than dust

src/components/ApyCalculatorModal/index.tsx
=> fix(apr-modal): Fix localisation data for APR modal and make perf fee condition more explicit

src/config/constants/types.ts, src/hooks/useUnstake.ts, src/utils/callHelpers.ts, src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
=> feat: Add a generic system for emergency withdraw in pools

src/__tests__/config/pools.test.ts, src/config/abi/sousChefV2.json, src/utils/contractHelpers.ts
The olf ABI is currently still compatible with the new contract.
Execpt for the tests, where we need to fetch the staking token.
=> test: Use the new pool abi for tests

src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx, src/views/Pools/components/PoolTabButtons.tsx
Tiny ui changes, PR title says it all
=> style(cake-vault): Remove text decoration from Pools Help button, make 'add to matamask' cursor: pointer

src/config/constants/farms.ts, src/config/constants/pools.ts
Images already exist
Farm reordered
Pool
--------------
**Earn:** xMARK
**Earn Token Contract Address:** https://bscscan.com/address/0x26a5dfab467d4f58fb266648cae769503cec9580
**Rewards per block:** 0.0298 xMARK
**Start block:** 7175420
**End block:** 8903420
**Token Decimals:** 9
**Project website:** https://benchmarkprotocol.finance/
=> feat(farm/pool): XMARK - 12:00 Release

src/views/Home/components/EarnAPRCard.tsx, src/views/Home/components/EarnAssetCard.tsx, src/views/Home/components/WinCard.tsx
Wrapped entire blocks into the `<NavLink>` component, so it's entirely clickable.
Also added a hover effect, to make it clearer that the element is clickable.
Here's how it looks now:
https://user-images.githubusercontent.com/9339019/116486644-61872000-a88e-11eb-9b28-f053f0023ae5.mp4
Please let me know if the hover effect is fine, or if further changes are needed :slightly_smiling_face:
=> style(home): Add hover effect on card and wrap entire block in NavLink

package.json, src/components/Menu/index.tsx, src/config/localization/languages.ts, src/contexts/Localization/Provider.tsx, src/contexts/Localization/helpers.ts, src/contexts/Localization/types.ts, yarn.lock
=> refactor: Add locale and keep old code

src/views/Predictions/components/CollectRoundWinningsModal.tsx
=> chore: Add BNB label

src/config/constants/pools.ts
pool
--------------
**Earn:** LMT
**Earn Token Contract Address:**  https://bscscan.com/address/0x9617857e191354dbea0b714d78bc59e57c411087
**Rewards per block:** 0.66145 LMT
**Start block:** 7206000
**End block:** 8934000
**Token Decimals:**  18
**Project website:** https://lympo.io/lmt/
=> feat(pool): LMT - 12:00 release

src/config/localization/translations.json, src/views/Predictions/History.tsx
=> chore: Update text

package.json, src/App.tsx, yarn.lock
=> chore: Bump web3@1.3.5 and remove monkey patch

src/config/abi/chainlinkOracle.json, src/config/constants/contracts.ts, src/hooks/useContract.ts, src/utils/addressHelpers.ts, src/utils/contractHelpers.ts, src/views/Predictions/hooks/useGetLatestOraclePrice.ts
=> feat(predictions): Hook to get latest price from chainlink oracle

src/config/constants/farms.ts, src/config/constants/pools.ts
pool
--------------
**Earn:** bMXX
**Earn Token Contract Address:** https://bscscan.com/token/0x4131b87f74415190425ccd873048c708f8005823
**Rewards per block:** 0.01331 bMXX
**Start block:** 7370600
**End block:** 9098600
**Project website:** https://multiplier.finance/
farm
-------
boost to 1x, no change
=> feat(farm/pool): BMXX - 18:00

src/views/Pools/components/PoolCard/CardActions/ApprovalAction.tsx
Allows users to re-enable finished pools
=> feat(pools): Allow enabling of finished pools

src/views/Predictions/components/RoundCard/ExpiredRoundCard.tsx, src/views/Predictions/components/RoundCard/LiveRoundCard.tsx, src/views/Predictions/components/RoundCard/MultiplierArrow.tsx, src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
=> chore(predictions): Remove bnb amount from arrows

package.json, yarn.lock
=> chore: Bump web3 and swiper

src/config/constants/ifo.ts
=> fix: IFO token

src/config/localization/translations.json
=> chore(translations): Update cake vault translations

src/config/localization/translations.json, src/views/Ifos/components/IfoFoldableCard/Achievement.tsx
=> Ifo lp format

src/state/hooks.ts, src/state/pools/index.ts, src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx, src/views/Pools/index.tsx
=> fix: (pools): Finished farms by pool endblock instead of isFinished not shown properly

src/config/constants/farms.ts
=> fix: RFOX PID

src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
Documentation: https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#id33
=> chore: IFO gasPrice default

src/components/Menu/config.ts, src/config/localization/translations.json
=> feat: Remove tag from prediction and change label

src/components/Menu/config.ts
Reverts pancakeswap/pancake-frontend#1264
=> Revert "Feature/ifo live tag"

src/config/localization/translations.json, src/views/Home/components/EarnAPRCard.tsx, src/views/Home/components/EarnAssetCard.tsx
Reverts pancakeswap/pancake-frontend#1280
=> Revert "feat: Add translations for earn cards in home page"

src/__tests__/config/translations.test.ts, src/config/localization/translations.json, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardActions.tsx, src/views/Ifos/components/IfoSteps.tsx, src/views/Pools/components/CakeVaultCard/UnstakingFeeCountdownRow.tsx, src/views/TradingCompetition/components/RegisterModal/MakeProfile.tsx
=> fix: Missing more translations and add test that checks strings in json

src/hooks/useHarvest.ts, src/views/Home/components/FarmStakingCard.tsx
That causes the second transaction will fail with error, if user sends the first one
=> fix: Harvest all button in homepage creates multiple transactions with same nonce value

src/config/localization/translations.json, src/views/Home/components/EarnAPRCard.tsx, src/views/Home/components/EarnAssetCard.tsx
@hachiojidev Sorry for the inconvenience
=> feat: Add translations for earn cards in home page

src/state/hooks.ts, src/views/Pools/components/BountyCard.tsx, src/views/Pools/components/PoolCard/CardActions/HarvestActions.tsx, src/views/Pools/components/PoolCard/CardActions/StakeActions.tsx, src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
=> fix: Busd price returns false instead of bigNumber

src/views/Pools/components/CakeVaultCard/index.tsx, src/views/Pools/components/PoolCard/StyledCard.tsx
Issue: 
https://user-images.githubusercontent.com/2213635/119223655-e581a000-bafa-11eb-9edf-5cb414028378.MP4
=> fix: Promoted pool card blinking on mobile

src/hooks/api.ts, src/views/Home/components/TotalValueLockedCard.tsx
Preview: https://debank-tvl.netlify.app/
- Change our TVL request to use debank
=> feat(tvl): Use debank tvl response for tvl calc on home

CONTRIBUTING.md
=> chore: Yarn prettier changes

src/views/Lottery/components/PastDrawsHistory/HistoryChart.tsx
=> fix: Update to use correct theme color

src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
=> fix: (IFO) Total committed shows 0 when cake price is being loaded

src/__tests__/utils/truncateWalletAddress.test.ts, src/utils/truncateWalletAddress.ts, src/views/TradingCompetition/components/TeamRanks/TopTradersCard/ExpandedGridItem.tsx, src/views/TradingCompetition/components/TeamRanks/TopTradersCard/GridItem.tsx, src/views/TradingCompetition/helpers.ts
=> feat: Truncate wallet address helper

src/config/constants/farms.ts, src/config/constants/pools.ts
pool
--------------
**Earn:** LIEN
**Earn Token Contract Address:** https://bscscan.com/token/0x5d684adaf3fcfe9cfb5cede3abf02f0cdd1012e3
**Rewards per block:** 0.023148 LIEN
**Start block:** 7741000
**End block:** 8605000
**Token Decimals:** 8
**Project website:** https://lien.finance/
=> feat(farm/pool): LIEN 1800

src/views/Ifos/components/IfoFoldableCard/index.tsx
=> fix(ifo): Incorrect enable contract address

src/components/PageSection/index.tsx, src/views/TradingCompetition/index.tsx
- Remove some complexity in PageSection styles, and make them more generic so they are easier to use in other pages
- Make the component receive props so that the `BackgroundColor` Flex can be restyled
- Modify Trading Comp styles that were impacted by this simplification
=> style(page-section): Make PageSection styles less opinionated

src/__tests__/utils/bscscan.test.ts, src/components/Timer/index.tsx, src/utils/bscscan.ts, src/utils/wallet.ts, src/views/Farms/components/FarmCard/FarmCard.tsx, src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx, src/views/Ifos/components/IfoFoldableCard/Timer.tsx, src/views/Predictions/components/CollectRoundWinningsModal.tsx, src/views/Predictions/components/History/BetDetails.tsx, src/views/Predictions/components/History/PnlTab/PnlTab.tsx, src/views/Profile/PublicProfile.tsx
Adds some helpers for bsc scan links
=> Bscscan helpers

src/views/Ifos/components/IfoFoldableCard/Achievement.tsx
=> feat(ifo): Add contract link

src/config/abi/lotteryV2.json, src/config/constants/contracts.ts, src/hooks/useContract.ts, src/utils/addressHelpers.ts, src/utils/contractHelpers.ts
- Adding necessary contract utils for lottery v2
=> chore(lottery-contract): Add lottery v2 ABI and address consts

src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx, src/views/Pools/components/PoolsTable/Apr.tsx, src/views/Pools/components/PoolsTable/Cells/AprCell.tsx, src/views/Pools/components/PoolsTable/Cells/EarningsCell.tsx, src/views/Pools/components/PoolsTable/Cells/ExpandActionCell.tsx, src/views/Pools/components/PoolsTable/Cells/NameCell.tsx, src/views/Pools/components/PoolsTable/PoolRow.tsx
Improvements regarding fitting APR column on small screens
=> fix: Small screen pools table improvements

src/config/index.ts, src/utils/callHelpers.ts, src/views/Pools/components/BountyModal.tsx
=> chore: Renamed variable for clarity

src/config/localization/languages.ts
The languages which we already have it but don't use it right now.
Review :
https://deploy-preview-1402--pancakeswap-dev.netlify.app/
=> chore: (languages): Add missing bengal, polish and portuguese languages to the list

src/components/Select/Select.tsx
Review: https://deploy-preview-1376--pancakeswap-dev.netlify.app/
To produce the issue:
1. Go to farms
2. Change sort by value from select component or keep it as it is
3. Try different languages
4. See selected value is not translated
Before: 
https://user-images.githubusercontent.com/2213635/119902869-1ec96e00-bf48-11eb-9138-f93266e86479.mov
After: 
https://user-images.githubusercontent.com/2213635/119902883-225cf500-bf48-11eb-9726-f9ffb50435ac.mov
=> fix: (select) Selected value is not translated in select component

package.json, src/utils/getUserStakeInCakeBnbLp.ts, yarn.lock
Ported from https://github.com/pancakeswap/gatsby-pancake-api/blob/master/utils/balance.ts
=> feat: Utility to get user cake balance in cake-bnb lp

src/views/Home/components/CakeStats.tsx
=> feat(cake-stats): Update New CAKE/block value to 18

src/views/Home/components/CakeStats.tsx
=> feat(cake-stats): Revert CAKE/block value to 20

src/config/abi/Multicall.json, src/config/constants/contracts.ts, src/utils/multicall.ts
=> feat: Multicall v2

src/views/Predictions/components/RoundCard/SetPositionCard.tsx
To review:
https://deploy-preview-1442--pancakeswap-dev.netlify.app/
Fixes #1441
=> fix: (prediction) Setting position exceeds decimal limit when using percentage buttons

src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
=> fix(ifo): Decimal formatting on contribute modal

package.json, yarn.lock
=> build: Bump UI Kit

src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx, src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx, src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
@hachiojidev it should be merged after toolkit bump up
=> feat: (balance input) Add decimal check to balance input

src/hooks/useAuth.ts
Fixes #1468
https://github.com/pancakeswap/pancake-toolkit/pull/148 should also be merged to fix the issue
=> fix: (useAuth) Translations not applied to error messages when language changes

src/config/constants/farms.ts, src/config/constants/pools.ts
pool
--------------
**Earn:** BONDLY
**Earn Token Contract Address:** https://bscscan.com/address/0x96058f8c3e16576d9bd68766f3836d9a33158f89
**Rewards per block:** 0.6741 BONDLY
**Start block:** 8171500
**End block:** 9899500
**Project website:** https://www.bondly.finance/
=> feat(pool): Bondly

src/config/index.ts, src/utils/addressHelpers.ts, src/utils/contractHelpers.ts
TestNet gas price should be 10 gwei, rather than the default 5.
- Add a getDefaultGasPrice helper to manage this.
- Add chainID consts to `/config`
=> fix(contract-helpers): Add getGasPrice helper and chainid consts to set gas based on chainid

src/views/Farms/components/FarmCard/StakeAction.tsx, src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
To review:
https://deploy-preview-1487--pancakeswap-dev.netlify.app/
=> feat: (farms) Show staked lp token amount in usd

src/config/constants/farms.ts, src/config/constants/pools.ts
pool
--------------
**Earn:** ODDZ
**Earn Token Contract Address:** https://bscscan.com/token/0xcd40f2670cf58720b694968698a5514e924f742d
**Rewards per block:** 0.4843 ODDZ
**Start block:** 8200200
**End block:** 9928200 
**Project website:** https://oddz.fi/
Farm is getting a boost
Token and images config already exist
=> feat(pool): ODDZ - 1800

src/hooks/useGetBlockCountdown.ts, src/hooks/useTokenBalance.ts, src/hooks/useWeb3.ts, src/state/hooks.ts, src/state/pools/fetchPoolsUser.ts, src/utils/callHelpers.ts, src/utils/contractHelpers.ts, src/utils/lotteryUtils.ts, src/utils/makeBatchRequest.ts, src/utils/multicall.ts, src/utils/web3.ts, src/views/Farms/components/FarmCard/CardActionsContainer.tsx, src/views/Farms/components/FarmCard/FarmCard.tsx, src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
Some rework to facilitate future work
=> Prepare migration

src/views/Home/components/CakeHarvestBalance.tsx, src/views/Home/components/FarmStakingCard.tsx
This will reduce the amount of requests made in farm staking card in home page.
=> feat: (farmstakingcard) Remove duplicate farm balance requests

src/views/Farms/components/FarmCard/FarmCard.tsx, src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
To review:
https://deploy-preview-1509--pancakeswap-dev.netlify.app/
1. Go to farms
2. Click See Pair Info
=> fix: (farms) Info links

src/config/constants/farms.ts, src/config/constants/pools.ts
pool
--------------
**Earn:** DFT
**Earn Token Contract Address:** https://bscscan.com/address/0x42712dF5009c20fee340B245b510c0395896cF6e
**Rewards per block:** 1.7361 DFT
**Start block:** 8369000
**End block:** 10097000
**Project website:** https://dfuture.com/
Farm boost & images already exist
=> feat(pool): DFT

src/config/constants/farms.ts, src/config/constants/pools.ts
pool
--------------
**Earn:** JGN
**Earn Token Contract Address:** https://bscscan.com/address/0xc13b7a43223bb9bf4b69bd68ab20ca1b79d81c75
**Rewards per block:** 0.1001 JGN
**Start block:** 8371400
**End block:** 10099400
**Project website:** https://jgndefi.com/
farm boost 
logos already exist
=> feat(pool): JGN - 1800

src/config/localization/translations.json, src/views/Home/Home.tsx, src/views/Home/components/LotteryCard.tsx, src/views/Home/components/PredictionBetaCard.tsx
To review:
https://deploy-preview-1527--pancakeswap-dev.netlify.app/
=> feat: (home) Change lottery card and add prediction beta card in homepage

package.json, src/components/TokenPairImage/index.tsx, src/views/Farms/components/FarmCard/CardHeading.tsx, src/views/Farms/components/FarmTable/Farm.tsx, src/views/Pools/components/CakeVaultCard/CakeVaultTokenPairImage.tsx, src/views/Pools/components/PoolCard/StyledCardHeader.tsx, src/views/Pools/components/PoolsTable/Cells/NameCell.tsx, yarn.lock
Moves the logic of constructing the token image url from the UI Kit top the app.
=> feat: Token pair image

src/config/constants/pools.ts
=> fix: Woo pool

src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx, src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
To review:
https://deploy-preview-1545--pancakeswap-dev.netlify.app/
1. Go to pools
2. Go to pool tables
3. Click details
4. See the links
5. Do the same things for pool cards
6. Compare the results
=> fix: (pools) Sync poolcard and pooltable detail links

src/config/index.ts, src/utils/addressHelpers.ts, src/utils/contractHelpers.ts
- Remove chain Ids from config
- Replace places where they are used with SDK values
=> chore(contractHelpers): Use SDK for chainIds

src/config/abi/lotteryV2.json, src/config/constants/contracts.ts
- Update lotteryv2 ABI & contract address
- Add multicall testnet contract address - https://testnet.bscscan.com/address/0x8F3273Fb89B075b1645095ABaC6ed17B2d4Bc576#code
=> chore(contracts): Add updated Lotteryv2 and multicall contracts

src/views/Home/components/PredictionPromotionCard.tsx
=> chore: Add id to prediction CTA

src/config/localization/translations.json, src/views/Farms/components/FarmCard/FarmCard.tsx
=> chore: Update farm card text

.github/workflows/updateLPsAPR.yml
=> chore: Update commit message for LP APR workflow

src/config/constants/farms.ts, src/config/constants/pools.ts
pool
--------------
**Earn:** SUTER
**Earn Token Contract Address:** https://bscscan.com/address/0x4cfbbdfbd5bf0814472ff35c72717bd095ada055
**Rewards per block:** 69.9074 SUTER
**Start block:** 8686700
**End block:** 9550700
**Project website:** https://shield.suterusu.io/
farm boost & image exists already
=> feat(pool): SUTER

src/config/constants/nfts.ts
=> refactor: Use pinata for video urls

src/config/localization/translations.json, src/views/Predictions/components/History/BetResult.tsx
=> feat(predictions): Show total amount collected

src/views/Voting/components/Proposal/Row.tsx
Fixes visual issue with votes on mobile
=> style: Clean up voting results on mobile

src/utils/achievements.ts
`checkClaimStatuses` was hitting the max limit causing it to throw an error. Migrated to multicall.
=> fix(profile): IFO achievement status check

src/views/Profile/components/AchievementAvatar.tsx
=> style: Remove border radius from achievement badge

src/config/constants/farms.ts, src/config/constants/pools.ts
no new farm - Images already exist
pool
--------------
**Earn:** GUM
**Earn Token Contract Address:** https://bscscan.com/token/0xc53708664b99DF348dd27C3Ac0759d2DA9c40462
**Rewards per block:** 0.67129 GUM
**Start block:** 8743900
**End block:** 10471900
**Project website:** https://gourmetgalaxy.io/
=> feat(pool): GUM - 1800

src/react-app-env.d.ts, src/utils/wallet.ts, src/utils/web3React.ts, src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx, src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx, src/views/Profile/ProfileCreation/UserName.tsx, src/views/Voting/CreateProposal/index.tsx, src/views/Voting/components/CastVoteModal/index.tsx
Adds a sign message method that uses `bnbSign` if wallet is BSC.
=> feat: Support for BSC Wallet signing

.env.development, .env.production, src/config/constants/endpoints.ts, src/state/voting/helpers.ts, src/utils/calls/pools.ts, src/utils/getRpcUrl.ts, src/utils/providers.ts, src/views/Voting/helpers.ts
Removed deprecated archive node provider.
=> chore: Remove archive node

src/__tests__/state/predictions/helpers.test.ts, src/state/predictions/helpers.ts, src/state/predictions/queries.ts, src/state/types.ts
Removes the market data subgraph dependency
=> refactor(prediction): Remove subgraph market call

src/utils/web3React.ts, src/views/Voting/components/Proposal/Row.tsx, src/views/Voting/components/Proposal/VoteRow.tsx
=> fix: Wallet Connect message signing

src/__tests__/utils/apr.test.ts, src/components/ApyCalculatorModal/index.tsx, src/config/localization/translations.json, src/utils/apr.ts, src/views/Farms/Farms.tsx, src/views/Farms/components/FarmCard/ApyButton.tsx, src/views/Farms/components/FarmCard/FarmCard.tsx, src/views/Farms/components/FarmTable/Apr.tsx, src/views/Home/components/EarnAPRCard.tsx
Show base APR and combined APR separately
=> Separate CAKE and LP APR

src/hooks/useApproveConfirmTransaction.ts, src/views/Collectibles/components/ClaimNftModal.tsx, src/views/Farms/components/DepositModal.tsx, src/views/Farms/components/FarmCard/HarvestAction.tsx, src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx, src/views/Farms/components/WithdrawModal.tsx, src/views/Home/components/FarmStakingCard.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ClaimButton.tsx, src/views/Pools/components/BountyModal.tsx, src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx, src/views/Pools/components/PoolCard/Modals/CollectModal.tsx, src/views/Pools/components/PoolCard/Modals/StakeModal.tsx, src/views/Pools/hooks/useApprove.ts, src/views/Predictions/components/CollectRoundWinningsModal.tsx, src/views/Predictions/components/ReclaimPositionButton.tsx, src/views/Predictions/components/RoundCard/SetPositionCard.tsx, src/views/Profile/ProfileCreation/ProfilePicture.tsx, src/views/Profile/components/AchievementRow/index.tsx, src/views/Profile/components/ClaimGiftModal.tsx, src/views/Profile/components/EditProfileModal/ApproveCakeView.tsx, src/views/Profile/components/EditProfileModal/PauseProfileView.tsx, src/views/TradingCompetition/components/ClaimModal/index.tsx, src/views/TradingCompetition/components/RegisterModal/RegisterWithProfile.tsx
Error messages should be unified imho and it should give information about gas
=> refactor: (error) Make error messages unified

src/config/index.ts, src/views/Home/components/CakeStats.tsx
=> chore: Update cake per block

src/views/LotteryV2/components/RewardBracketDetail.tsx
=> feat: Increase font size

src/views/LotteryV2/components/PreviousRoundCard/Footer.tsx
=> fix(lottery-v2): Fix Prize Pot cake price for historic rounds

src/utils/calls/estimateGas.ts, src/views/Pools/components/BountyModal.tsx, src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
=> fix: Gas margin on auto cake pool

src/config/localization/translations.json, src/views/Home/components/LotteryBanner.tsx, src/views/Home/components/LotteryPromotionCard.tsx
To review:
https://deploy-preview-1660--pancakeswap-dev.netlify.app/
@ChefHutch I was about to write this to the comment of previous pr but then it is merged, So i decided to implement the logic by myself.
=> fix: (lotterybanner) Adapt lottery banner and promotion to different languages

src/views/Pools/components/BountyModal.tsx, src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
=> chore: Increase gas limit for auto cake pool

src/views/Predictions/components/RoundCard/CalculatingCard.tsx, src/views/Predictions/components/RoundCard/CanceledRoundCard.tsx, src/views/Predictions/components/RoundCard/CardHeader.tsx, src/views/Predictions/components/RoundCard/ExpiredRoundCard.tsx, src/views/Predictions/components/RoundCard/LiveRoundCard.tsx, src/views/Predictions/components/RoundCard/OpenRoundCard.tsx, src/views/Predictions/components/RoundCard/SoonRoundCard.tsx
=> feat(prediction): Add timestamp to card header

src/App.tsx
=> chore: Redirect from /pool to /liquidity

src/components/ReactMarkdown/styles.tsx
=> fix(voting): Table color in dark mode

.github/ISSUE_TEMPLATE/bug-report.yaml
=> fix: Yarn prettier changes on bug report

package.json, yarn.lock
=> chore: UI Kit bump

.github/CODEOWNERS, LICENSE
=> docs: Add license

src/views/Farms/Farms.tsx, src/views/Pools/index.tsx
To review:
https://deploy-preview-1750--pancakeswap-dev.netlify.app/
To reproduce: 
1. Go to pools or farms
2. Toggle staked only
3. See everytime it toggles (if there are few staked only pools to trigger intersection) amount of farms or pools shown increases on stakedOnly off mode
=> fix: (pools&farms) Number of visible items increasing when toggling staked only

src/config/constants/farms.ts, src/config/constants/pools.ts
Farm boost - images and token exist.
pool
--------------
**Earn:** PMON
**Earn Token Contract Address:** https://bscscan.com/address/0x1796ae0b0fa4862485106a0de9b654eFE301D0b2
**Rewards per block:** 0.02696 PMON
**Start block:** 9317900
**End block:** 11045900
**Project website:** https://polkamon.com/
=> feat(pool): PMON

src/components/App/Transactions/TransactionsModal.tsx, src/components/SearchModal/CurrencySearch.tsx, src/config/constants/tokenLists/pancake-default.tokenlist.json, src/hooks/useActiveWeb3React.ts, src/hooks/useFetchListCallback.ts, src/setupTests.js, src/state/application/hooks.ts, src/state/application/updater.ts, src/state/burn/hooks.ts, src/state/mint/hooks.ts, src/state/multicall/hooks.ts, src/state/multicall/updater.tsx, src/state/transactions/hooks.tsx, src/state/transactions/updater.tsx, src/state/user/hooks/index.tsx, src/state/user/hooks/useUserAddedTokens.ts, src/views/Swap/index.tsx
Fixing some bugs on the exchange
=> Usage issues

src/views/Farms/Farms.tsx
To review:
https://deploy-preview-1764--pancakeswap-dev.netlify.app/
1. Go to farms 
2. You should not see any difference
=> refactor: Remove redundant div container in farms

src/config/constants/farms.ts
=> fix: Farm quote token

package.json, src/config/localization/translations.json, src/views/Predictions/components/RoundCard/EnteredTag.tsx, src/views/Predictions/components/RoundCard/ExpiredRoundCard.tsx, src/views/Predictions/components/RoundCard/MultiplierArrow.tsx, src/views/Predictions/components/RoundCard/index.tsx, yarn.lock
- Add `hasClaimedUp` & `hasClaimedDown` conditions
- Style EnteredTag accordingly
=> (feature) Predictions - Add styling to EnteredTag for claimed rounds

src/views/Pools/components/PoolTabButtons.tsx, src/views/Pools/index.tsx
To review:
https://deploy-preview-1772--pancakeswap-dev.netlify.app/
1. Go to pools
2. Check control container (that has staked toggle and search filter)
3. Then go to farms
4. Check the differences
=> feat: Make pools settings container looks like same as farms container

src/views/Predictions/hooks/useIsRefundable.ts
=> fix(predictions): Refundable status

src/components/App/Settings/SettingsModal.tsx, src/components/App/Settings/TransactionSettings.tsx, src/components/Menu/Footer.tsx, src/components/Menu/SubNav.tsx, src/config/localization/translations.json, src/state/swap/hooks.ts, src/views/AddLiquidity/index.tsx, src/views/Pool/index.tsx
=> chore(translations): Add missing translations for exchange

package.json, yarn.lock
Preview https://jolly-yonath-9afc57.netlify.app
=> chore(packages): Bump @web3-react/walletconnect-connector

src/config/constants/farms.ts
=> fix: Farm order

src/views/Predictions/Desktop.tsx
To review:
https://deploy-preview-1811--pancakeswap-dev.netlify.app/prediction
To reproduce:
1. Go to predictions
2. You should not see any difference
=> refactor: Remove redundant div in predictions positions

src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx, src/views/Farms/components/FarmTable/Actions/StakedAction.tsx, src/views/Farms/components/FarmTable/Actions/styles.ts, src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx
To review:
https://deploy-preview-1810--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to pools table without an account
2. Click details
3. Check harvest balance number
4. Compare it with farms table
=> refactor: Sync pools table harvest action with farms table

src/config/localization/translations.json, src/views/FarmAuction/index.tsx, src/views/Home/components/FarmAuctionsBanner.tsx, src/views/Home/index.tsx
Preview https://youthful-nightingale-402740.netlify.app/
=> feat(farm-auctions-banner): Add farm auctions banner to home

src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx, src/views/Lottery/components/BuyTicketsModal/EditNumbersModal.tsx
GA didn't like the template strings
=> chore(lottery): Update GA ids

src/views/Home/index.tsx
=> chore(home): Remove farm auctions banner from homepage

src/config/constants/farms.ts
=> feat: Add community tags to auction winner farms

src/views/FarmAuction/components/FAQs.tsx, src/views/FarmAuction/index.tsx
=> fix: Dark theme on auctions page

src/views/RemoveLiquidity/index.tsx
Fixes https://github.com/pancakeswap/pancake-frontend/issues/1848
=> chore(remove-liquidity): Wrap burned text in Text el so it is responsive to theming

src/config/constants/farms.ts
=> chore: Reorder farms

src/views/Home/components/Banners/FarmAuctionsBanner.tsx, src/views/Home/components/Banners/PotsFarmBanner.tsx, src/views/Home/index.tsx
=> feat(pots-farm-banner): Add PotsFarmBanner to homepage

.github/ISSUE_TEMPLATE/feature-request.yaml
=> fix: Feature request template

src/components/Menu/UserMenu/ProfileUserMenutItem.tsx
=> fix: Profile links in user menu doesn't work

src/views/Farms/components/FarmCard/StakeAction.tsx
=> fix: Farm card LP amount display

src/config/localization/translations.json, src/views/Home/components/Banners/FarmAuctionsBanner.tsx, src/views/Home/index.tsx
=> feat(home): Reanimate farm auctions banner

src/views/Home/components/MetricsSection/index.tsx
=> chore(homepage-metrics): Update metrics with data 13/8/21

src/components/Menu/GlobalSettings/SettingsModal.tsx, src/components/Menu/GlobalSettings/TransactionSettings.tsx
I forgot them.
To review:
https://deploy-preview-1920--pancakeswap-dev.netlify.app/
=> fix: Add remaining global settings tooltips placements

src/components/Menu/GlobalSettings/TransactionSettings.tsx
To review:
https://deploy-preview-1922--pancakeswap-dev.netlify.app/
=> chore: Fix typo in transaction settings

src/config/localization/translations.json, src/views/Home/components/Banners/FarmAuctionsBanner.tsx
=> chore: Update farm auction banner text

src/config/constants/farms.ts, src/config/constants/pools.ts
=> feat: Bel pool

src/utils/calls/farms.ts
Commit should be self explanatory
=> chore: remove duplicate await keyword

src/state/farms/hooks.ts, src/views/Farms/Farms.tsx, src/views/Pools/index.tsx
To review:
https://deploy-preview-1967--pancakeswap-dev.netlify.app/
1. Go to pools
3. Check there is no difference
Amount of requests is reduced
=> refactor: (pool) Dont fetch user farm data in pools

src/views/Voting/Proposal/Votes.tsx, src/views/Voting/components/Proposal/Row.tsx
Fix spacing issue with the voting table on mobile
=> style(voting): Fix mobile vote view

src/components/PageSection/CurvedDivider.tsx, src/components/RoiCalculatorModal/useRoiCalculatorReducer.ts, src/state/lottery/hooks.ts, src/state/predictions/helpers.ts, src/utils/compoundApyHelpers.ts, src/views/FarmAuction/helpers.tsx, src/views/Lottery/components/BuyTicketsModal/useTicketsReducer.tsx, src/views/Lottery/components/PreviousRoundCard/Body.tsx, src/views/Lottery/components/TicketNumber.tsx, src/views/Lottery/components/WinningNumbers.tsx, src/views/Lottery/helpers.tsx, src/views/RemoveLiquidity/index.tsx, src/views/Voting/CreateProposal/index.tsx, src/views/Voting/components/CastVoteModal/index.tsx, src/views/Voting/helpers.ts
=> chore: Fix typos

src/state/predictions/helpers.ts, src/state/predictions/index.ts, src/views/Predictions/components/CollectRoundWinningsModal.tsx, src/views/Predictions/components/History/BetResult.tsx, src/views/Predictions/components/History/HistoricalBet.tsx
History items were not checking the correct place in state for the claim status.
=> fix: Claimable status

src/config/localization/translations.json, src/state/predictions/config.ts, src/state/predictions/helpers.ts, src/state/predictions/hooks.ts, src/state/predictions/index.ts, src/state/types.ts, src/views/Predictions/History.tsx, src/views/Predictions/components/CollectRoundWinningsModal.tsx, src/views/Predictions/components/History/RoundsTab.tsx
Adds a "View More" button when a user has more than a thousand rounds.
=> feat(predictions): View all history

.github/workflows/staleIssues.yml
Adds a GH workflow to auto-close stale issues
=> build: Add workflow for stale issues

src/config/localization/translations.json, src/views/Predictions/components/PositionTag.tsx, src/views/Predictions/components/RoundCard/ExpiredRoundCard.tsx, src/views/Predictions/components/RoundCard/MultiplierArrow.tsx, src/views/Predictions/components/RoundResult/RoundResult.tsx, src/views/Predictions/components/RoundResult/styles.tsx, src/views/Predictions/helpers.ts
=> feat(predictions): Card state for house wins

src/config/constants/farms.ts, src/config/constants/pools.ts
Details: https://pancakeswap.finance/voting/proposal/QmX2izDpVNAqyx3whubvN4mnRCqTiuM4aigsP8F3r6tPWW
=> feat(farm/pool): BP

src/config/localization/translations.json, src/views/Lottery/components/NextDrawCard.tsx, src/views/Lottery/components/PreviousRoundCard/Body.tsx
To review:
https://deploy-preview-2059--pancakeswap-dev.netlify.app/
To reproduce: 
2. Check next draw section
3. Change language
4. See Your tickets part not translated correctly
=> fix: Lottery user ticket amount info text not translated correctly

src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
To review: 
https://deploy-preview-2045--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to pools
2. Go to unstake or stake one of the pools that you have
3. Put an amount higher than you have
4. See there is no warning and confirm button is enabled
=> feat: (pools) Add token amount validations to pool stake/unstake modal

src/config/constants/meta.ts, src/config/localization/translations.json, src/views/Page.tsx, src/views/Predictions/Leaderboard/index.tsx, src/views/Predictions/index.tsx, src/views/Voting/CreateProposal/index.tsx, src/views/Voting/Proposal/index.tsx, src/views/Voting/index.tsx
To review:
https://deploy-preview-2074--pancakeswap-dev.netlify.app/
=> fix: Missing page titles

src/views/Farms/Farms.tsx, src/views/Pools/index.tsx
To review: 
https://deploy-preview-2087--pancakeswap-dev.netlify.app/
1. Go to pools and farms
2. See farms and pools loaded automatically when reaching the bottom
=> refactor: Use intersection observer in pools and farms

src/hooks/useIntersectionObserver.ts
To review: 
https://deploy-preview-2086--pancakeswap-dev.netlify.app/
1. Go to homepage 
2. See prediction and lottery card is working (those are the ones that use intersection observer for now)
=> refactor: Add cleanup function to intersection observer

src/views/Home/components/WinSection/LotteryCardContent.tsx, src/views/Home/components/WinSection/PredictionCardContent.tsx
To review:
https://deploy-preview-2085--pancakeswap-dev.netlify.app/
1. Go to homepage 
2. See prediction and lottery card is working
=> refactor: Remove duplicate observer ref in lottery and prediction cards

src/views/Voting/Proposal/index.tsx
=> fix: Remove verification

src/views/Home/components/MetricsSection/index.tsx
=> chore(metrics): Update bitquery metrics on homepage

src/state/user/actions.ts, src/state/user/hooks/index.tsx, src/state/user/reducer.ts, src/views/Predictions/components/ChartDisclaimer.tsx, src/views/Predictions/index.tsx
=> refactor: (prediction) Move prediction user settings to redux

src/components/Menu/GlobalSettings/ExpertModal.tsx, src/components/Menu/GlobalSettings/SettingsModal.tsx, src/state/user/actions.ts, src/state/user/hooks/index.tsx, src/state/user/reducer.ts, src/views/Profile/PublicProfile.tsx
To review:
https://deploy-preview-2122--pancakeswap-dev.netlify.app/
Check user name visibility and expert mode acknowledge remember (when turning on the expert mode from user settings) working properly
=> refactor: Move username visibility and expert mode acknowledge settings to redux

cypress/integration/exchange/add-liquidity.test.ts, cypress/integration/exchange/remove-liquidity.test.ts, cypress/integration/exchange/swap.test.ts, package.json
To review:
https://deploy-preview-2118--pancakeswap-dev.netlify.app/
=> chore: Yarn prettier changes and change format script directory level

src/config/abi/nftMarket.json, src/config/constants/contracts.ts, src/hooks/useContract.ts, src/utils/addressHelpers.ts, src/utils/contractHelpers.ts
=> chore(nft-market): Add testnet address and hooks for contract

src/state/user/actions.ts, src/state/user/hooks/index.tsx, src/state/user/reducer.ts, src/views/Farms/Farms.tsx, src/views/Farms/components/ToggleView/ToggleView.tsx, src/views/Farms/components/types.ts, src/views/Pools/components/PoolTabButtons.tsx, src/views/Pools/components/ToggleView/ToggleView.tsx, src/views/Pools/index.tsx
To review:
https://deploy-preview-2099--pancakeswap-dev.netlify.app/
Check pools staked only, view mode and farms view mode settings works properly
=> refactor: (pools & farms) Move staked only and view mode settings to redux

src/state/nftMarket/helpers.ts, src/state/nftMarket/hooks.ts, src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts
=> Fetch nfts

src/views/Collectibles/components/NftList.tsx
Fixes #2098 
Not sure if this is the correct way, @ChefNina and @Chef-Chungus can you confirm?
To review: 
https://deploy-preview-2103--pancakeswap-dev.netlify.app/
=> fix: Claim button is visible even after the claiming deadline passed

src/config/constants/farmAuctions.ts, src/config/constants/tokens.ts
Checksum everythiiiing. Tests will be clearer to analyze for future failures too :)
Not sure if we want to fix the last warning about tests with are related to Redux reducer.. That will be another PR anyway.
=> chore: Checksum addresses

src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts
=> chore: Move NFTs at the root of the state

src/App.tsx, src/config/localization/translations.json, src/views/Nft/market/IndividualNFTPage/DetailsCard.tsx, src/views/Nft/market/IndividualNFTPage/ExpandableCard.tsx, src/views/Nft/market/IndividualNFTPage/ForSaleTableCard/ForSaleTableRows.tsx, src/views/Nft/market/IndividualNFTPage/ForSaleTableCard/index.tsx, src/views/Nft/market/IndividualNFTPage/MainNFTCard.tsx, src/views/Nft/market/IndividualNFTPage/ManageCard.tsx, src/views/Nft/market/IndividualNFTPage/MoreFromThisCollection.tsx, src/views/Nft/market/IndividualNFTPage/PropertiesCard.tsx, src/views/Nft/market/IndividualNFTPage/index.tsx, src/views/Nft/market/IndividualNFTPage/tmp.ts, src/views/Nft/market/IndividualNFTPage/types.ts, src/views/Nft/market/index.tsx
WIP with tons of shitcode, don't look here
=> feat: Individual NFT Page

src/utils/calls/nftMarket.ts
=> feat: Add call helpers for nft market

src/config/index.ts
To review:
https://deploy-preview-2162--pancakeswap-dev.netlify.app/
=> refactor: Remove unused constant

src/views/Swap/components/confirmPriceImpactWithoutFee.ts
To review: 
https://deploy-preview-2175--pancakeswap-dev.netlify.app/
=> fix: (swap) Confirm error shown everytime in swap

src/config/index.ts, src/utils/apr.ts
To review:
https://deploy-preview-2161--pancakeswap-dev.netlify.app/
Check apr's on farms and pools work properly.
=> refactor: Remove bignumber in constants

src/components/Menu/Footer.tsx
Add "ercBridge" id to this link at Ali's request
=> chore(swap-footer): Add ercBridge id to Bridge link

src/views/FarmAuction/index.tsx, src/views/Home/components/Banners/FarmAuctionsBanner.tsx, src/views/Ifos/components/IfoSteps.tsx, src/views/NotFound.tsx, src/views/TradingCompetition/components/HowToJoin/index.tsx
To review:
https://deploy-preview-2177--pancakeswap-dev.netlify.app/
=> refactor: Change a tag link to router link to not refresh page

src/state/nftMarket/helpers.ts, src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts, src/views/Nft/market/components/CollectibleCard/CollectibleCard.tsx
Waiting for the API to be updated
=> feat: Use API for NFTs data

src/views/Nft/market/Collectible/Filters.tsx, src/views/Nft/market/Collectible/Header.tsx, src/views/Nft/market/Collectible/index.tsx, src/views/Nft/market/Collectibles/index.tsx, src/views/Nft/market/components/GridPlaceholder.tsx
- Add grid placeholder component
=> feat: Flesh out collectibles page

src/views/Nft/market/Collectible/Header.tsx
=> fix: Typing problem

public/index.html, src/utils/getRpcUrl.ts
=> chore: Increase load on Google to 50%

src/state/nftMarket/helpers.ts, src/state/nftMarket/hooks.ts, src/state/nftMarket/queries.ts, src/views/Nft/market/Home/Newest.tsx, src/views/Nft/market/Home/index.tsx
=> feat: Latest NFTs

src/components/AddressInputSelect/index.tsx, src/state/predictions/hooks.ts, src/state/predictions/index.ts, src/state/types.ts, src/views/Nft/market/Collectible/Header.tsx, src/views/Nft/market/Collectible/TopBar.tsx, src/views/Predictions/Leaderboard/components/AddressSearch.tsx, src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
- Moved address input search to global to be used in NFT market
=> refactor: Address search

src/views/Page.tsx
=> fix(duplicate nav): Remove duplicate SubNav

src/state/nftMarket/helpers.ts
=> fix(nft-market-sg): Fix casing

package.json, src/views/Home/index.tsx, yarn.lock
- Update UIKit with the latest fixes
- Adjust home spacing
=> feat(menu): Update UIKit

src/state/nftMarket/helpers.ts, src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts, src/views/Nft/market/Profile/components/UserNfts.tsx
Re-creating this PR because I messed up.
=> feat(user-nfts): Add metadata fetch to fetchUserNfts reducer

src/App.tsx, src/state/nftMarket/helpers.ts, src/state/nftMarket/types.ts, src/views/Nft/market/Collectible/CollectionNfts.tsx, src/views/Nft/market/Home/Newest.tsx, src/views/Nft/market/Profile/components/UserNfts.tsx, src/views/Nft/market/components/CollectibleCard/CollectibleCard.tsx, src/views/Nft/market/index.tsx
=> feat: Add links on cards

src/views/Nft/market/Home/index.tsx, src/views/Nft/market/components/CollectibleCard/HotCollectionCard.tsx, src/views/Nft/market/index.tsx
=> feat: Add links on hp collections

src/config/localization/translations.json
=> chore(nft-market-translations): Add missing translations

src/components/Menu/UserMenu/ProfileUserMenutItem.tsx, src/components/Menu/config/config.ts, src/components/Menu/index.tsx, src/views/Nft/market/Collectible/TopBar.tsx, src/views/Nft/market/Collectibles/index.tsx, src/views/Nft/market/Home/index.tsx, src/views/Nft/market/Profile/components/SubMenu.tsx, src/views/Nft/market/Profile/components/TabMenu.tsx, src/views/Nft/market/Profile/index.tsx, src/views/Nft/market/components/BuySellModals/SellModal/EditStage.tsx, src/views/Nft/market/components/BuySellModals/SellModal/SellStage.tsx, src/views/Nft/market/components/CollectibleCard/CollectibleCard.tsx, src/views/Nft/market/index.tsx, src/views/ProfileCreation/Header.tsx, src/views/ProfileCreation/index.tsx, src/views/TradingCompetition/components/RegisterModal/MakeProfile.tsx, src/views/TradingCompetition/components/RegisterModal/ReactivateProfile.tsx
- Create `nftsBaseUrl` const. 
- Use throughout nfts links and routing.
=> chore(nft-market): Create const for '/nfts' route

src/config/localization/translations.json, src/state/transactions/updater.tsx
To review
https://deploy-preview-2284--pancakeswap-dev.netlify.app/
=> fix: Missing translations in transaction updater

src/state/nftMarket/hooks.ts
=> chore(nft-market): Delete unused metadata hook

src/state/nftMarket/reducer.ts, src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx, src/views/Nft/market/components/BuySellModals/SellModal/index.tsx, src/views/ProfileCreation/Mint.tsx
Add actions to update, add and remove a single NFT within a user's wallet - used when buying/selling/transferring etc.
=> feat(nft-market): Add new actions to fire after successful buy/sell/transfer events

src/config/constants/priceHelperLps.ts
[x] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[x] Explain what your PR does
```
absense -> absence
```
=> chore: Fix typo in priceHelperLps.ts

.env.development, .env.production, .env.test, public/index.html, src/utils/getRpcUrl.ts, src/utils/providers.ts, src/utils/wallet.ts, src/utils/web3React.ts
=> chore: Migrate to Google node only

.env.development, .env.production, .env.test, public/index.html, src/utils/getRpcUrl.ts, src/utils/providers.ts, src/utils/wallet.ts, src/utils/web3React.ts
Reverts pancakeswap/pancake-frontend#2308
=> Revert "chore: Migrate to Google node only"

.env.development, .env.production, src/config/constants/contracts.ts, src/utils/getRpcUrl.ts
=> feat: Add mainnet URLs

src/views/Collectibles/components/GlobalCheckClaimStatus.tsx
Revert lottery claiming check change that was done in #2266
=> feat(lottery claim): Revert lottery claim check

src/config/localization/translations.json, src/state/nftMarket/reducer.ts, src/views/Nft/market/Profile/components/ActivityHistory/ActivityPrice.tsx, src/views/ProfileCreation/Mint.tsx, src/views/ProfileCreation/ProfilePicture.tsx
Improved minting experience during profile creation.
=> chore(nft-mint): Re-fetch user NFTs after mint

src/config/localization/translations.json, src/state/nftMarket/helpers.ts, src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts, src/views/Nft/market/Profile/components/ActivityHistory/TableLoader.tsx, src/views/Nft/market/Profile/components/ActivityHistory/index.tsx, src/views/Nft/market/Profile/components/EditProfileModal/ChangeProfilePicView.tsx, src/views/Nft/market/Profile/hooks/useUserActivity.tsx
- Add style for when user has no activity history
- Improve state when transitioning between accounts
- Other minor styling improvements
=> feat(nft-market): Style 'no activity' state. Improve loading conditions

.env.production, public/index.html, src/utils/getRpcUrl.ts
=> fix: Temporarily remove google node due to connection issues

src/views/Collectibles/components/GlobalCheckClaimStatus.tsx
Reverts pancakeswap/pancake-frontend#2322
=> Revert "feat(lottery claim): Revert lottery claim check"

src/views/Nft/market/Collection/Header.tsx
Subgraph response is just a string, no need for ethers conversions
=> fix: Trade volume fix

src/views/Nft/market/components/BuySellModals/SellModal/SetPriceStage.tsx
=> feat(nft): Add USD to sell amount

src/views/Nft/market/Collection/IndividualNFTPage/MoreFromThisCollection.tsx, src/views/Nft/market/Collection/IndividualNFTPage/index.tsx
- Fix issues with styling on slider
=> fix: Duplicate nft on more section

src/components/Menu/UserMenu/ProfileUserMenutItem.tsx, src/components/Menu/UserMenu/index.tsx, src/config/localization/translations.json
=> chore(menu-items): Separate profile and NFT menu items

src/components/Menu/config/config.ts
=> chore(menu-items): Remove 'All Items' menu item until we have the page

src/components/Menu/utils.ts
=> chore(active-menu-items): Guard against homepage menu crash

src/views/Nft/market/Collection/IndividualNFTPage/MainNFTCard.tsx
=> fix: Use thumbnail image

src/components/AddressInputSelect/index.tsx, src/views/Nft/market/Collection/TopBar.tsx, src/views/Nft/market/Home/index.tsx, src/views/Nft/market/components/SearchBar.tsx
=> feat: Add search on overview page

src/App.tsx, src/hooks/useUserAgent.ts
Add user agent as data attribute. This is needed to target specific browsers.
Example on UIKit: https://github.com/pancakeswap/pancake-toolkit/pull/293
=> fix(bottom nav): Add user agent as data attribute

src/views/Nft/market/Collection/Traits/PancakeBunniesTraits.tsx, src/views/Nft/market/Collection/Traits/styles.tsx, src/views/Nft/market/Collection/Traits/types.ts, src/views/Nft/market/Collection/Traits/utils.tsx
Add a sort button on rarity column.
=> feat: Add rarity sort

src/state/nftMarket/helpers.ts, src/views/Nft/market/Collection/IndividualNFTPage/ForSaleTableCard/ForSaleTableRows.tsx, src/views/Nft/market/Profile/components/ActivityHistory/ActivityRow.tsx, src/views/Nft/market/components/ProfileCell.tsx
- Create new `ProfileCell` component for adding to tables to fetch and render a profile from an address
- Now links to the new profile pages
=> feat(profile-cell): Create shared ProfileCell component linking to user profiles

src/config/constants/contracts.ts, src/views/Nft/market/Collection/Items/Filters.tsx
=> chore: Update market address

src/views/Nft/market/components/BuySellModals/SellModal/SetPriceStage.tsx
=> fix(sell-price): Use inputMode = decimal

src/views/Nft/market/components/BuySellModals/SellModal/EditStage.tsx, src/views/Nft/market/components/BuySellModals/SellModal/SellStage.tsx
Fix 'View item' condition sending users to the tokenId page for PBs
=> fix(view-item): Fix condition for 'View Item' to pb id rather than tokenid

src/config/localization/translations.json, src/views/Nft/market/Collection/IndividualNFTPage/index.tsx, src/views/Nft/market/Collection/Traits/PancakeBunniesTraits.tsx, src/views/Nft/market/Collection/Traits/utils.tsx, src/views/Nft/market/Collections/index.tsx, src/views/Nft/market/Home/Collections.tsx, src/views/Nft/market/Home/index.tsx, src/views/Nft/market/Profile/components/ActivityHistory/index.tsx, src/views/Nft/market/Profile/hooks/useFetchUserNfts.tsx, src/views/Nft/market/Profile/hooks/useUserActivity.tsx, src/views/Nft/market/components/BuySellModals/SellModal/SetPriceStage.tsx, src/views/Nft/market/components/BuySellModals/SellModal/index.tsx, src/views/Nft/market/hooks/useAllPancakeBunnyNfts.ts
To review: 
https://deploy-preview-2416--pancakeswap-dev.netlify.app/
=> fix: (nft): Typos and missing translations

src/components/Menu/index.tsx
=> chore: Remove unused menu code

src/views/Info/hooks/useBlocksFromTimestamps.ts
It will reduce the amount of total requests (options + post) from 13 to 8
To review:
https://deploy-preview-2325--pancakeswap-dev.netlify.app/
1. Go to https://pancakeswap.finance/info
2. Check requests to https://api.thegraph.com/subgraphs/name/pancakeswap/blocks
=> refactor: Add dependency array to blocks from timestamps hook

src/views/Nft/market/Collection/Items/CollectionNfts.tsx
=> fix: Collection page crash on non PB collections

src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts, src/views/Nft/market/Collection/Items/CollectionNfts.tsx
=> fix: Fetch data for non PB collections

src/state/nftMarket/helpers.ts, src/state/nftMarket/types.ts, src/views/Nft/market/Collection/Traits/CollectionTraits.tsx, src/views/Nft/market/Collection/Traits/PancakeBunniesTraits.tsx, src/views/Nft/market/Collection/Traits/index.tsx, src/views/Nft/market/Collection/Traits/styles.tsx, src/views/Nft/market/hooks/useGetCollectionDistribution.tsx
=> feat(market): Collection traits

doc/Cypress.md
Just a minor grammar fixes in the Cypress docs
=> docs: typo fixes

src/config/constants/meta.ts
=> fix: (pancakesquad): Fix page title

src/views/PancakeSquad/components/Buttons/Mint.tsx, src/views/PancakeSquad/hooks/useUserInfos.tsx
=> fix: Minting for squad

src/views/PancakeSquad/components/EventStepsSection/index.tsx
To review:
https://deploy-preview-2536--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to https://pancakeswap.finance/pancake-squad
2. Go to Sounds great, how can I get one? section
3. Click View Market button
=> fix: (squad): Nft market link in landing page

src/views/Farms/components/FarmTable/Actions/StakedAction.tsx, src/views/Pools/components/CakeVaultCard/UnstakingFeeCountdownRow.tsx
To review:
https://deploy-preview-2512--pancakeswap-dev.netlify.app/
=> refactor: Use css text transform for upper and lower case

src/views/Nft/market/Collection/IndividualNFTPage/shared/MoreFromThisCollection.tsx
To review:
https://deploy-preview-2501--pancakeswap-dev.netlify.app/
=> feat: (morefromcollection): Shuffle cards when rerender and fetch data only when no data available in state

src/config/constants/farms.ts
=> feat(farm/pool): Game auction winners

src/views/Home/index.tsx
=> fix: Banner mobile style

src/components/Menu/config/config.ts, src/views/Home/components/Banners/IFOBanner.tsx
=> chore: Change live porto

src/components/Menu/config/config.ts, src/views/Home/index.tsx
=> chore: Remove banner

src/config/constants/farms.ts
Reverts pancakeswap/pancake-frontend#2692
=> Revert "fix: Temporarily remove Porto farm"

src/state/achievements/index.ts, src/state/farms/index.ts, src/state/nftMarket/reducer.ts, src/state/predictions/index.ts
To review:
https://deploy-preview-2661--pancakeswap-dev.netlify.app/
=> refactor: (reducer): Remove unused reducers

package.json
CVE-2020-29041
Same stuff as https://github.com/pancakeswap/pancake-frontend/pull/2670 just with fixed commit message.
=> chore: Do not build sourcemaps for prod

public/locales/ru-RU.json
Even if you briefly look through file you can see that in most cases variable `%***%` is at the end. For this one it definitely should be at the end.
=> [Ru-Translation] The order in Russian different

public/locales/ru-RU.json
If everywhere else staking is translated as вложение then here is also have to be вложение. Otherwise there might be some confusions.
=> [Ru-Translation] For consistency

public/locales/ru-RU.json
`Learn more` is not `read more` so you cannot translate it the same.
=> [Ru-Translation] Better translation

public/locales/ru-RU.json
The main purpose of this text is to inform that this exact page is one where NFT are going to be claimed. But this was not mentioned at all.
=> [Ru-Translation] Something was missing

public/locales/ru-RU.json
This is a process so ... should be at the end.
=> [Ru-Translation] 3 dos is missing

package.json, yarn.lock
=> chore: Bump uikit

src/views/Lottery/components/AllHistoryCard/index.tsx, src/views/Lottery/components/NextDrawCard.tsx, src/views/Lottery/components/YourHistoryCard/FinishedRoundRow.tsx, src/views/Lottery/components/YourHistoryCard/index.tsx, src/views/Lottery/helpers.tsx
To reproduce: 
3. See months in dates are not translated
To review: 
https://deploy-preview-2750--pancakeswap-dev.netlify.app/
=> fix: (lottery): Missing date translations

src/views/Info/Overview/index.tsx, src/views/Info/components/InfoCharts/BarChart/index.tsx, src/views/Info/components/InfoCharts/CandleChart/index.tsx, src/views/Info/components/InfoCharts/ChartCard/index.tsx, src/views/Info/components/InfoCharts/LineChart/index.tsx
To review:
Check date translation on charts
https://deploy-preview-2751--pancakeswap-dev.netlify.app/
=> fix: (info): Missing date translations

src/config/localization/translations.json, src/views/FarmAuction/components/AuctionDetailsCard/AuctionSchedule.tsx, src/views/FarmAuction/components/AuctionHistory.tsx, src/views/FarmAuction/components/AuctionLeaderboard/index.tsx
To review:
https://deploy-preview-2743--pancakeswap-dev.netlify.app/
=> fix: (farm-auction): Missing translations

public/locales/ru-RU.json
You do not buy gas you pay gas for transaction.
=> [Ru-Translation] Not buy gas but paying gas.

src/views/FarmAuction/components/AuctionHistory.tsx
To review:
1. Go to farm auction
2. Go to archive
3. Put non numeric values to input
4. See it doesn't accept to values
https://deploy-preview-2747--pancakeswap-dev.netlify.app/
=> feat: (farm-auction): Add input validation to auction history archive

src/config/constants/farms.ts, src/config/constants/pools.ts
Farm info:
LP address: 0x74fA517715C4ec65EF01d55ad5335f90dce7CC87
LP Symbol: SFUND-BNB
Pool info:
Token address: 0x477bc8d23c634c154061869478bce96be6045d12	
Pool contract address: 0x7f103689cabe17c2f70da6faa298045d72a943b8
Pool token rewards per block: 0.0311
=> feat: List SFUND

src/components/Menu/Footer.tsx, src/views/Page.tsx, src/views/Swap/index.tsx
Fixes #2774
To review:
https://deploy-preview-2777--pancakeswap-dev.netlify.app/
=> fix: (swap): Need help image component position

src/config/constants/farms.ts, src/config/constants/pools.ts
Farm info:
LP address: 0x85e5889fc3ed01b4e8b56bbc717d7643294d2c31
LP Symbol: ZOO-BNB
Pool info:
Token address: 0x1d229b958d5ddfca92146585a8711aecbe56f095	
Pool contract address: 0x2efe8772eb97b74be742d578a654ab6c95bf18db
Pool token rewards per block: 0.4516
=> feat(farm/pool): ZOO

src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
as title
https://deploy-preview-2781--pancakeswap-dev.netlify.app/ifo
=> feat(ifo): Show price with fee per token after finished

src/state/nftMarket/helpers.ts, src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/MainNFTCard.tsx, src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx, src/views/Nft/market/components/CollectibleCard/CardBody.tsx, src/views/Nft/market/components/NFTImage.tsx, src/views/Nft/market/components/NFTMedia.tsx
Support video and gif for PB and other NFT collections
preview:
https://deploy-preview-2780--pancakeswap-dev.netlify.app/
=> feat(nft): NFT video and gif

src/state/block/hooks.ts, src/state/multicall/updater.tsx
https://deploy-preview-2785--pancakeswap-dev.netlify.app/
=> fix: Skip block retry error

src/views/Swap/components/Chart/PriceChart.tsx, src/views/Swap/components/Chart/SwapLineChart.tsx
To review:
https://deploy-preview-2769--pancakeswap-dev.netlify.app/
=> fix: (swap-chart): Missing date translations

src/views/Ifos/components/IfoQuestions/config.ts, src/views/Ifos/components/IfoQuestions/index.tsx
To review:
https://deploy-preview-2773--pancakeswap-dev.netlify.app/
=> fix: (ifo): Make ifo questions translations testable

src/config/constants/farms.ts, src/config/constants/pools.ts
Farm info:
LP address: 0x06043b346450bbcfde066ebc39fdc264fdffed74
LP Symbol: SANTOS-BNB
Pool info:
Token address: 0xA64455a4553C9034236734FadDAddbb64aCE4Cc7	
Pool contract address: 0x0914b2d9d4dd7043893def53ecfc0f1179f87d5c
Pool token rewards per block: 0.0578
=> feat(farm/pool): List santos

src/components/Menu/config/config.ts, src/views/Home/index.tsx
Remove banner and menu tag
Based on this https://github.com/pancakeswap/pancake-frontend/pull/2804
=> Remove IFO banner and menu tag

src/components/Menu/config/footerConfig.ts
=> fix: (home): Bug bounty link

src/views/Info/components/InfoTables/TransactionsTable.tsx
To reproduce:
1. Go to info
2. Go to pools
3. See transaction table
4. Order transactions by token amounts
5. See not ordered correctly
To review: 
https://deploy-preview-2761--pancakeswap-dev.netlify.app/
=> fix: (info): Token amounts not ordered correctly in transaction list

src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeButton.tsx, src/views/Ifos/components/IfoFoldableCard/index.tsx, src/views/Ifos/hooks/v1/useGetPublicIfoData.ts, src/views/Ifos/hooks/v1/useGetWalletIfoData.ts, src/views/Ifos/hooks/v2/useGetPublicIfoData.ts, src/views/Ifos/hooks/v2/useGetWalletIfoData.ts, src/views/Ifos/types.ts
New approach
Old one:
https://github.com/pancakeswap/pancake-frontend/pull/2795
To review:
https://deploy-preview-2818--pancakeswap-dev.netlify.app/
=> fix: (ifo): Reduce amount of requests on both live and past ifos

src/components/ReactMarkdown/styles.tsx
reactmarkdown adopt to <a> Tag
=> fix(voting): Page overflow fixed

src/config/localization/translations.json, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeButton.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx, src/views/Ifos/types.ts
Fix checking for max userBalance and token entry.
Note that it will auto adjust to either max userBalance or max token entry if user enter more than those amount.
=> fix(ifo): Contribute input max

src/views/Pools/components/PoolsTable/Cells/AprCell.tsx, src/views/Pools/components/PoolsTable/Cells/AutoAprCell.tsx, src/views/Pools/components/PoolsTable/Cells/AvgBalanceCell.tsx, src/views/Pools/components/PoolsTable/Cells/StakedCell.tsx, src/views/Pools/components/PoolsTable/PoolRow.tsx
make pool APY, APR in same column
=> feat(pool): Apy/Apr in same col

src/components/TradingView.tsx, src/config/localization/translations.json, src/views/Predictions/Desktop.tsx, src/views/Swap/components/Chart/TradingViewChart.tsx
Add TV link when widget is installed on page. It's required by TV
.
=> chore: Add TV label and link

package.json, src/views/PancakeSquad/components/ArtistSection/config.tsx, src/views/Swap/index.tsx, yarn.lock
Fix #2854 and update swap icon
=> fix(swap): Switch token onclick and icon

src/state/index.ts
=> fix: Redux getDefaultMiddleware

src/utils/web3React.ts, src/views/ProfileCreation/UserName.tsx, src/views/Voting/CreateProposal/index.tsx, src/views/Voting/components/CastVoteModal/index.tsx
To reproduce
1. Install binance smart chain wallet on your browser]
2. Connect pcs with metamask wallet
3. Do create profile or cast vote action
4. See approval popup not appeared in metamask
To review:
https://deploy-preview-2901--pancakeswap-dev.netlify.app/
=> fix: (sign): Cannot show approval screen on the wallet connected when bsc wallet is installed

src/state/pools/fetchPools.ts
Instead of 2 multicall 1 multicall is made.
To review:
https://deploy-preview-2864--pancakeswap-dev.netlify.app/
=> perf: (pool): Pools block limits calls

src/components/Menu/config/config.ts
=> chore: Update menu tags

package.json, src/contexts/RefreshContext.tsx, src/hooks/useRefresh.ts, src/hooks/useTokenBalance.ts, src/state/farms/hooks.ts, src/state/farms/index.ts, src/state/lottery/hooks.ts, src/state/pools/hooks.ts, src/state/pools/index.ts, src/state/types.ts, src/views/FarmAuction/components/AuctionLeaderboard/AuctionProgress.tsx, src/views/FarmAuction/hooks/useCurrentFarmAuction.ts, src/views/Home/components/WinSection/LotteryCardContent.tsx, src/views/Home/components/WinSection/PredictionCardContent.tsx, src/views/Home/hooks/useFarmsWithBalance.tsx, src/views/Home/hooks/useGetTopPoolsByApr.tsx, src/views/Ifos/components/IfoFoldableCard/index.tsx, src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
1. Split fast and slow refresh context
2. Add conditional fetch on farms action
=> refactor: Split refresh context

src/components/Menu/config/config.ts, src/views/Nft/market/Activity/index.tsx, src/views/Nft/market/Home/Newest.tsx, src/views/Nft/market/index.tsx
Component that shows activities from all collections combined in nft.
To review:
To reach the all activity page there are 2 options
1. Activity in Nft menu 
2. View all in Overview -> Newest Arrivals
https://deploy-preview-2950--pancakeswap-dev.netlify.app/
=> feat: (nft): All collections activity component

src/state/transactions/updater.tsx
To review:
https://deploy-preview-2946--pancakeswap-dev.netlify.app/
=> refactor: Use ToastDescriptionWithTx in updater

src/hooks/useBUSDPrice.ts, src/state/farms/hooks.ts, src/views/Ifos/components/IfoCardV3Data.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx, src/views/Ifos/components/IfoFoldableCard/index.tsx, src/views/Ifos/components/IfoPoolVaultCard.tsx, src/views/Ifos/components/IfoSteps.tsx, src/views/Pools/components/CakeVaultCard/VaultCardActions/index.tsx, src/views/Pools/components/PoolsTable/Cells/AvgBalanceCell.tsx, src/views/Pools/components/PoolsTable/PoolRow.tsx
add `useBUSDCurrencyAmount` and `useBUSDCakeAmount` hook for getting price * amount more easier
=> refactor(ifo): AvgBalance busd hook

package.json, yarn.lock
https://deploy-preview-2930--pancakeswap-dev.netlify.app/
=> chore: Bump ethers

src/components/Menu/config/config.ts, src/hooks/useContract.ts, src/state/pools/hooks.ts, src/state/pools/index.ts, src/views/Ifos/hooks/v3/useGetWalletIfoData.ts, src/views/Ifos/index.tsx, src/views/Pools/components/PoolsTable/PoolRow.tsx
Add pool action for specify pool zero
=> perf(ifo): Reduce ifo pool network request

src/views/Nft/market/Home/Newest.tsx
Numbers response from nft api maybe null, better matching the response with id
=> fix(nft): Newest api response may be null

src/state/pools/hooks.ts, src/views/Pools/index.tsx
It is already done useFetchPublicPoolsData and useFetchUserPools
=> fix: (pools): Stake component flickering in cake pools

scripts/updateLPsAPR.ts, src/App.tsx, src/components/Menu/GlobalSettings/SettingsModal.tsx, src/components/ScrollToTopButton/index.tsx, src/components/SubgraphHealthIndicator/index.tsx, src/config/constants/endpoints.ts, src/config/localization/translations.json, src/contexts/Localization/types.ts, src/hooks/useSubgraphHealth.ts, src/state/user/actions.ts, src/state/user/hooks/index.tsx, src/state/user/reducer.ts
Add subgraph health indicator
Q: How to determine the subgraph is delayed? 
15 mins is delayed
~5~ 2.5 mins is slow
=> feat: Subgraph health indicator

src/views/Pools/components/PoolsTable/Cells/AutoEarningsCell.tsx, src/views/Pools/components/PoolsTable/PoolRow.tsx
To review:
https://deploy-preview-2972--pancakeswap-dev.netlify.app/
=> fix: (earnings): Auto earning cell loading indicator uses wrong variable

src/views/Home/index.tsx
@chef-jojo less work for you :)
=> chore: Remove auctions banner

src/hooks/useIntersectionObserver.ts, src/views/Nft/market/components/NFTMedia.tsx
NftMedia will be played only when its visible
To review:
https://deploy-preview-2996--pancakeswap-dev.netlify.app/
=> feat: (nft): Play nft media only when its visible for browser performance

src/config/localization/translations.json, src/views/Swap/components/SwapWarningModal/SafemoonWarning.tsx
Add translation https://github.com/pancakeswap/pancake-frontend/pull/2973
=> feat(swap-warning-modals): Update SAFEMOON warning

src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeButton.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardActions.tsx
=> feat(ifo): Display disabled commit button on pre ifo period

src/config/constants/farms.ts, src/config/constants/pools.ts
Farm info:
LP address: 0x2Eebe0C34da9ba65521E98CBaA7D97496d05f489
LP Symbol: BCOIN-BNB
Pool info:
Token address: 0x00e1656e45f18ec6747F5a8496Fd39B50b38396D	
Pool contract address: 0xad8F6A9d58012DCa2303226B287E80e5fE27eff0
Pool token rewards per block: 0.1493
Start Block: https://bscscan.com/block/countdown/14299090
=> feat(farm/pool): List BCOIN

src/views/Ifos/CurrentIfo.tsx, src/views/Ifos/components/IfoSteps.tsx, src/views/Ifos/index.tsx
- Set how-to section in IFO page to be full screen width
=> chore(ifo): Set how-to section full screenwidth

src/config/constants/pools.ts
Add new BCOIN pool address 0x25ca61796d786014ffe15e42ac11c7721d46e120
=> feat(pools): Add new BCOIN pool address

src/state/pools/fetchPools.ts
Uses multicall instead of call per pool.
With farm call refactor, total pools calls will be down from ~900 to ~10.
To review:
https://deploy-preview-2860--pancakeswap-dev.netlify.app/
=> perf: (pool): Refactor pool staking limit calls

src/config/localization/translations.json, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
=> feat(ifo): Add small amount warning for Unlimited Sale

src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ManagePancakeBunniesCard.tsx
To review:
1. Go to nft details page of one of bunny that account has
2. See manage yours section
3. See count in title
https://deploy-preview-3012--pancakeswap-dev.netlify.app/
=> feat: (nft): Add bunny count to manage yours title

src/views/Nft/market/components/Activity/ActivityRow.tsx
To review:
1. Go to nft activity
2. Click collection text in activity row
3. See it redirects to collection page instead of nft details page
=> feat: (nft): Add link to collection in activity row

src/components/Card/index.tsx, src/components/CurrencyInputPanel/NumericalInput.tsx, src/components/Layout/Column.tsx, src/components/Layout/Row.tsx, src/components/SearchModal/ImportToken.tsx, src/components/SearchModal/ManageTokens.tsx, src/components/SearchModal/filtering.ts, src/state/lists/reducer.ts, src/views/Info/components/InfoSearch/index.tsx
Fixing issues in:
https://sonarcloud.io/project/issues?id=pancakeswap_pancake-frontend&resolved=false&severities=MAJOR&types=BUG
=> refactor: Remove redundant sub-expressions and use for each

src/config/localization/translations.json, src/views/Swap/components/SwapWarningModal/SafemoonWarning.tsx
Update more meaninful SAFEMOON new address message.
=> fix(swap): Update SAFEMOON new address message

src/config/constants/farms.ts, src/config/constants/pools.ts
Pool info:
Token address: 0x40c8225329bd3e28a043b029e0d07a5344d2c27c 
Pool contract address: 0xa34832efe74133763A85060a64103542031B0A7E
Pool token rewards per block: 0.6435
Start Block: https://bscscan.com/block/countdown/14385280
=> feat: Add AOG pool

src/views/Lottery/index.tsx
To reproduce:
1. Go to prediction 
2. Then go to lottery from tab menu
3. See title still shows prediction
To review:
=> fix: (lottery): Page title when accessing from another page

src/state/user/hooks/index.tsx, src/state/user/reducer.ts
To review:
https://deploy-preview-2825--pancakeswap-dev.netlify.app/
=> feat: (phishing): Remind phishing banner once in a day

src/hooks/useIntersectionObserver.ts
Issue mainly happens in https://github.com/pancakeswap/pancake-frontend/pull/2865 where nftmedia with video mounted after first render.
=> fix: (intersection): Intersection observer cannot detect new mounted element after re-render

src/views/Swap/components/Chart/BasicChart.tsx, src/views/Swap/components/Chart/PriceChart.tsx, src/views/Swap/components/Chart/PriceChartContainer.tsx, src/views/Swap/components/Chart/TradingViewChart.tsx, src/views/Swap/components/Chart/styles.tsx, src/views/Swap/components/styleds.tsx, src/views/Swap/index.tsx
It stops rerendering the trading view chart on every price change
It also fixes trading chart not completely visible in normal mode
To review:
https://deploy-preview-2835--pancakeswap-dev.netlify.app/
=> refactor: Reduce chart rerenders

src/config/constants/nftsCollections/index.ts, src/config/constants/nftsCollections/types.ts, src/views/Nft/market/constants.ts
There is already interface named Collection.
=> refactor: (nft constant): Rename collection to pancakecollection

src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx, src/views/Nft/market/Collection/Traits/PancakeBunniesTraits.tsx, src/views/Nft/market/hooks/useGetCollectionDistribution.tsx
To review:
1. Go to pb traits page or pb nft details page to check rarity and supply count data
2. Current fan token and xmas bunny data is wrong
https://deploy-preview-3001--pancakeswap-dev.netlify.app/
=> fix: (nft): PB token distribution by using on chain data

src/state/nftMarket/types.ts, src/views/Nft/market/Collections/index.tsx
To review:
1. Go to collections page
2. See now order is shuffled by default
3. Click Collection header
4. See it is ordered by created date of collection.
https://deploy-preview-2868--pancakeswap-dev.netlify.app/
=> feat: (nft): Make NFT Default collections order random and add order by collection option

src/config/localization/translations.json, src/views/Pools/components/PoolsTable/Cells/AutoEarningsCell.tsx
continues the work on #1526 
To review:
https://deploy-preview-2970--pancakeswap-dev.netlify.app/
=> feat: (pools) Adds profit over time calculations, based on previous earnings since last user action

src/hooks/useContract.ts, src/views/ProfileCreation/ProfilePicture.tsx
To reproduce:
1. Go to profile creation
2. Proceed to profile picture selection
3. Select nft aside from bunny and squad
4. Go to the last step
5. Click confirm
6. See error message
To review:
https://deploy-preview-2873--pancakeswap-dev.netlify.app/
=> fix: (profile creation): Nfts that have not nft role in profile contract shown when selecting p.p

src/contexts/Localization/Provider.tsx
Before:
https://user-images.githubusercontent.com/97418926/149693846-159d8668-2bbc-4881-a339-d670c5be7a49.mp4
After:
https://user-images.githubusercontent.com/97418926/149694838-c89efc66-f5f6-4f8e-8f84-0de0b0d29109.mp4
=> fix(performance): Avoid unexpected re-rendering in component using transalation

src/views/Pools/hooks/useUnstakePool.ts
Fixes:
TypeError: b.wait is not a function
=> fix: (pool): Unstake tx wait undefined error
