pancakeswap/pancake-frontend

netlify.toml
Adds a config for Netlify to auto-cancel builds if the branch name does not start with `feature/`. This will enable us to keep PR deploy previews on for only PR's we want a preview.
=> feat(build): Enable deploy previews based on branch

src/config/constants/farms.ts, src/state/farms/fetchFarms.ts
Uses multiplier from the contract as opposed to the config.
=> feat(farms): Fetch multiplier from contract

src/App.tsx, src/components/Menu/config.ts, src/views/Teams/Profile/index.tsx, src/views/Teams/ProfileCreation/index.tsx, src/views/Teams/components/NoProfileCard.tsx, src/views/Teams/index.tsx
Structure for profiles
`/teams` - main landing page
`/teams/profile` - user's profile page, renders creation screen if doesn't exist
=> feat(teams): Route structure (wip)

src/hooks/useApproval.ts, src/views/Home/components/LotteryCard.tsx, src/views/Lottery/components/TicketCard/TicketActions.tsx
Fixes https://github.com/pancakeswap/pancake-frontend/issues/310
Adds the approve state so that the"Approve" button is shown instead of the "Buy tickets". I've duplicated the logic of `src/views/Lottery/components/TicketCard/TicketActions.tsx` as I'm not yet too familiar with the codebase.
=> fix: No 'approve' state on the dashboard lottery modal. Fixes #310

src/contexts/Localisation/languageContext.tsx, src/hooks/useI18n.ts
When first starting up the project i got the following error:
Change the value when an error is encountered while loading crowdin translations to an empty array to prevent errors in code that doesn't handle the 'error' string value
=> fix: improve error handling when loading translations

src/utils/callHelpers.ts
Following reports from the community, a lot of users are experiencing lower estimated gas limit than used by contract call by their wallet resulting in multiple failed transactions, and as such wasting BNB. They need bump the gas limit in their wallet on each transaction to ensure it will not fail. Along this, users of Binance Chain wallet are not allowed to tweak their gas price and gas limit settings.
This will enhance the user experience.
> Note: Gas Price not affected as it's a node consensus on the BSC, and value is fetched by the wallet at each transaction via the connected node.
This is covering most use-cases:
- Harvest
- Compound
- Stake
- Unstake
Approve and Emergency Withdraw still use the default estimated gas limit by the wallet.
Documentation: …
=> fix: Set minimal gas limit @ 200k

.env, src/config/constants/ifo.ts, src/state/profile/getProfile.ts, src/views/Profile/ProfileCreation/UserName.tsx
- Cleaner URL syntax
- Use official domain name
> Note: This is ready to be deployed as-is. Legacy and new URL's syntax are both supported by the API in production.
=> chore: Update Profile API endpoints

src/utils/lotteryUtils.js
Fixes https://github.com/pancakeswap/pancake-frontend/issues/265
The issue was with this assertion `if (ticketIssue.toString() === issueIdex) {}` in `src/utils/lotteryUtils.js`. One is a string and the other a number, so when we use the triple equals for strict equality they are not equal.
I've fixed it with double equals so that it performs type coercion, I'm happy to convert the `issueIdex` to string as well if that's more preferable. I think it looks cleaner using loose equality though, but had to disable a eslint rule.
=> fix: Fix 265 - Unable to view lottery tickets from past draws

src/hooks/useApproveConfirmTransaction.ts
This is in response to a user who cannot continue with creating their profile. It displays the errors.
=> feat: Add error message on approve/confirm

src/hooks/useTokenBalance.ts
This fixes issue #463
This works by using the hook `useWeb3` instead of `useWallet`. The `useWeb3` hook attempts to use the wallet provider first, then if that does not work, it will use the http provider as a fallback.
Then `web3.currentProvider` passes the correct provider to `getTokenBalance` to find the amount of CAKE tokens in address `0x000000000000000000000000000000000000dEaD`.
=> fix: show the burned balance with or without a wallet

src/views/Home/components/CakeStats.tsx
Burned balance in cake stats shows value with decimals. We should show as same type that total supply does
I reviewed it and made the corrections
=> feat: make Burned Balance value user friendly

package.json, src/state/profile/getProfile.ts, yarn.lock
The current implementation of getting the profile avatar and username to the exchange will not work with local storage. This PR updates the code to use a cookie.
=> feat: Save user profile and avatar to cookie

src/config/constants/farms.ts, src/config/constants/pools.ts
Farm
Stake WATCH-BNB LP Tokens, Earn CAKE
2x CAKE rewards for the first 48 hours and then 1x CAKE rewards after that.
Start block: 5382600 (March 4th 6PM SGT)
WATCH-BNB LP Token Address: 0xdc6c130299e53acd2cc2d291fa10552ca2198a6b
Syrup Pool
Stake CAKE, Earn WATCH
Total Pool Tokens: 600,000 WATCH
Distribution duration: 60 days
Start block: 5382600 (March 4th 6PM SGT)
Finish block: 7110600 (May 3rd 6PM SGT)
Token rewards per block: 0.3472 WATCH
WATCH Token Contract: https://bscscan.com/token/0x7a9f28eb62c791422aa23ceae1da9c847cbec9b0
=> feat(farm/pool): Add WATCH

src/hooks/useAllowance.ts
`fetchAllowance` was being called with `setInterval` even if no account was present
=> fix: Fetch allowance called without an account

src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
The new detail menu would look like this
=> feat: Make links in farm pair dropdown menu more descriptive

src/utils/getLiquidityUrlPathParts.ts, src/views/Farms/components/FarmCard/FarmCard.tsx, src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx, src/views/Farms/components/FarmTable/Actions/StakedAction.tsx, src/views/Farms/components/FarmTable/Apr.tsx, src/views/Ifos/ComingSoon.tsx, src/views/Ifos/CurrentIfo.tsx, src/views/Ifos/components/IfoCard/ContributeModal.tsx
Remove ETH in swap urls.
To be release at the same time as https://github.com/pancakeswap/pancake-swap-interface/pull/234.
=> chore: Replace ETH by BNB in swap urls

src/views/Lottery/Lottery.tsx
=> fix: Show last lottery results instead of first in past draws when wallet is not connected

src/views/Lottery/components/PastLotteryRoundViewer/PastLotterySearcher.tsx
=> fix: Remove arrows underneath lottery past draws search button

src/components/EasterEgg/EasterEgg.tsx
Currently FallingBunnies use random position for bunnies. so RefreshContextProvider make the EasterEgg component rerender then it changes bunnies position in the middle of animation and it's not nice.
=> fix: Prevent EasterEgg bunnies reposition on rerenders

src/config/constants/pools.ts
BTCST are removing one decimal from their token
https://btcst.medium.com/btcst-redenomination-guide-for-exchange-and-wallet-partners-ad00eade8cec
=> chore: Update BTCST decimals

src/views/Farms/Farms.tsx
=> fix: Farms page crash when order by multiplier when farms being loaded

src/views/Pools/components/CardFooter.tsx, src/views/Pools/components/PoolCard.tsx
BNB doesn't have an address , which break some pools after the token list rework
=> fix: Past pools with BNB token

src/hooks/useGetDocumentTitlePrice.ts
Fixes #711 
And added dependency to useEffect regarding to 
https://github.com/pancakeswap/pancake-swap-interface/pull/295#discussion_r598396443
=> fix: Cake price in webpage title shows 0 when loading fresh restart and added dependency to useEffect

src/views/Farms/Farms.tsx
In Farms table sort by APR does not sort farms with more than 1000 APR properly.
Currently in master it gets shoved below farms with 200% APR due to the way how lodash's orderBy works with BigNumber.js numbers.
You can see contrived example in sandbox here - https://codesandbox.io/s/c1kgz
This PR fixes ordering so farms with >1000% APR come on top.
Fixes #650 
**Current master (note BUX-BNB)**
**This PR**
=> fix: Sort by APR not sorting high APR properly

src/views/Home/components/CakeWinnings.tsx, src/views/Home/components/LotteryCard.tsx, src/views/Home/components/LotteryJackpot.tsx
Cake winnings section shows 0 when no wallet connected
Look like this when no wallet connected and cake price is loading
=> fix: Cake winnings section Locked when no wallet and remove cake prize in dollar when 0

src/hooks/api.ts
Use a tailored endpoint for frontend to return only used values such as to display the Total Value Locked, and avoid loading all pairs state.
=> chore(api): TVL endpoint

src/state/achievements/index.ts
Found a bug in the achievements reducer (`state/achievements/index.ts`). `.concat` returns new array and does not change the existing array, so it didn't affect the state at all.
Right now only `addAchievement` is used. `addAchievements`, `setAchievements` and `clearAchievements` are not used anywhere in the code, so there is no bug in prod. However as I understand the competition will give multiple achievements to users so it might be used soon.
I've made a quick demo UI to test it:
You can try it yourself, here is a [branch](https://github.com/Chef-Cheems/pancake-frontend/tree/feature/test-achievement-broken) on my fork (on top of current develop)
https://user-images.githubusercontent.com/81824236/113603526-bbf4de00-964c-11eb-9c6a-f95f8485798c.mp4
And here is the same testing UI on top …
=> fix: Fix addAchievements in achievements reducer

src/views/Ifos/components/IfoCard/MetaLabel.tsx, src/views/Profile/ProfileCreation/TeamSelection.tsx
The `MetaLabel` and `Team` types that are removed in this PR are defined but not used. Moreover, they also have the same name as the React components. Luckily TS compiler is able to figure out to export React component on the last line and not the type, so nothing is broken, but better to clean it up.
=> chore: Remove unused types

src/hooks/useGetLotteryHasDrawn.ts
Until ticket sale progress always shown and countdown from 1 hour repeatedly till end of lottery draw when no wallet connected
=> fix: Wrong Until ticket sale progress when no wallet connected

src/views/TradingCompetition/components/BattleBanner/index.tsx, src/views/TradingCompetition/components/ClaimModal/index.tsx, src/views/TradingCompetition/components/Countdown/ProgressStepper.tsx, src/views/TradingCompetition/components/Countdown/index.tsx, src/views/TradingCompetition/components/PrizesInfo/PrizesGrid/index.tsx, src/views/TradingCompetition/components/RegisterModal/RegisterWithProfile.tsx, src/views/TradingCompetition/components/Ribbon/index.tsx, src/views/TradingCompetition/components/Rules/FoldableText.tsx
- Fix the timer & prizes grid breaking out on smaller devices.
- Media queries added to reduce padding/margins at smaller sizes and make the page style correctly down to 320px
- *Note* Struggled to get overflow-x scrolling on the prize grid, so have just shrunk padding/margins. When less time-pressed with the trading comp components we can improve this.
Before (318 px):
After (318 px):
=> fix: Trading Competition styles for small devices

src/views/TradingCompetition/components/YourScore/CardUserInfo.tsx
UI catch for users with 0 volume
=> fix(trading-comp-zero-vol): Add catches for zero vol users

src/views/TradingCompetition/components/TeamRanks/TopTradersCard/GridItem.tsx, src/views/TradingCompetition/components/TeamRanks/TopTradersCard/TopTradersGrid.tsx
Use index rather than API rank value for the # rank
Before (two #1 #1s)
After
=> fix(trading-comp-rankings-fix): Add index values for ranking

src/views/TradingCompetition/types.tsx
username no longer coming back from leaderboard, so removing it from types
=> chore(types): Remove username type for leaderboard data item

src/views/Pools/components/PoolCard.tsx
Fix a crash in the pools history page due to the API based on token address, which is null for BNB pools.
=> fix: Pools history page

src/views/TradingCompetition/components/YourScore/CardUserInfo.tsx, src/views/TradingCompetition/components/YourScore/NextRankBox.tsx
Some styles that are implicit in Chrome, aren't in Safari.
Before:
After:
=> fix(trading-comp-your-score): Fix some YourScore styling bugs on Safari

src/views/TradingCompetition/components/YourScore/NextRankBox.tsx
Hard coded gradient wasn't respecting dark mode, now it will.
I'll look at moving this within the uikit to `theme/colors` tomorrow
=> fix(trading-comp): Use themed background gradient for 'Next Tier' box

src/views/TradingCompetition/components/TeamRanks/TopTradersCard/ExpandedGridItem.tsx, src/views/TradingCompetition/components/TeamRanks/TopTradersCard/GridItem.tsx, src/views/TradingCompetition/components/TeamRanks/TopTradersCard/TopTradersGrid.tsx, src/views/TradingCompetition/components/TeamRanks/TopTradersCard/index.tsx
Expand the Top Traders section to show the next 15 traders on `ExpandableLabel` click
- Between **576 - 852px** (where the card has the full-screen) and again above **1080px**, the expanded wrapper shows as a three-column grid.
- Above & below those values, it renders as a block element.
- Resulting in lots of media queries to make this work across screen sizes.
Preview https://elegant-payne-0f0170.netlify.app/competition
=> Feature: Top Traders - Top 20

src/hooks/useEagerConnect.ts
Fixes Binance Chain Wallet not working with eager connect, requiring users to re-authenticate on every refresh.
This fix defines `BinanceChain` property on window with a getter & setter so that we get notified once the extension has initialized and we can proceed with login.
=> fix(auth): Eager connect not working with bsc extension

src/views/Home/components/CakeHarvestBalance.tsx, src/views/Home/components/CakeWalletBalance.tsx, src/views/Home/components/CakeWinnings.tsx, src/views/Home/components/LotteryJackpot.tsx
- Fix height when no price available when no wallet connected
Before: 
After: 
- Fix height when no price available when wallet connected
Before:
After: 
- Fix cake busd price when available 
Before: 
After:
=> fix: Align lottery jackpot and staking card when no price or no cake winning available

src/views/TradingCompetition/components/BattleBanner/index.tsx, src/views/TradingCompetition/components/CompetitionHeadingText.tsx, src/views/TradingCompetition/components/Countdown/index.tsx, src/views/TradingCompetition/components/LeadInBanner/index.tsx, src/views/TradingCompetition/components/PreviewComponents/PreviewBattleBanner.tsx
`Warning: Received `true` for a non-boolean attribute `fill`. If you want to write it to the DOM, pass a string instead: fill="true" or fill={value.toString()}. h2 O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 div O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 div O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 div O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 div O@http://localhost:3000/static/js/vendors~main.chunk.js:214520:6 LeadInBanner@http://localhost:3000/static/js/0.chunk.js:256:88 Home@http://localhost:3000/static/js/11.chunk.js:760:88 Route@http://localhost:3000/static/js/vendors~main.chunk.js:199424:29 Switch@http://localhost:3000/static/js/vendors~main.chunk.js:199626:29 Suspense …
=> fix: Fix dom key warning

src/__tests__/utils/compoundApyHelpers.test.ts, src/components/ApyCalculatorModal/index.tsx, src/utils/compoundApyHelpers.ts, src/views/Farms/components/FarmCard/ApyButton.tsx
- As this component is needed by the Pools view as well as the Farms view, I thought it made sense to move it to `src/components`
I have renamed some variables to help understanding:
- `calculateCakeEarnedPerThousandDollars` -> `cakeEarnedPerThousandDollarsCompounding `
- `apyModalRoi` -> `getRoi `
- `apy` -> `apr` (the calculator expects an APR value - it then calculates the return over various periods of time, including 365d (APY))
=> chore: Move APY calculator to /components

src/views/Lottery/components/TicketCard/BuyTicketModal.tsx
=> refactor: Use balanced number instead of full one for readability in buy ticket modal

src/views/TradingCompetition/components/ClaimModal/index.tsx
=> style(trading-competition-claim-modal): Fix alignment issue within claim modal on safari

src/views/Pools/components/Card.tsx
Currently when a `PoolCard` gets expanded it's siblings which are on the same row also grow to the same height.
**Before**
**After**
=> fix(pool): PoolCard height adjusting to siblings

src/state/hooks.ts
Fix issue with token address casing not matching, and resulting in some APR's values missing for farms/pools.
=> fix: Token address casing

src/views/Pools/components/CardFooter.tsx
In pools there's an option on each card to add that card's token to MetaMask.
Currently this option is still available if there's no MetaMask extension installed, in such cases clicking it will result in errors in console.
=> refactor: Hide "Add to MetaMask" if no MetaMask in scope

src/views/Lottery/components/YourPrizesCard/index.tsx
Fixes #869 
**Ipad:**
**Android:**
**Iphone:**
**Desktop:**
=> fix: Missing margin lottery won card

src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
=> fix: Farm table stake lp button not showing when 0

src/views/Farms/Farms.tsx, src/views/Farms/components/SearchInput.tsx
**Every time I search farms, it’s very slow because it renders every characters while typing. So, I have improved it by adding debounce (Lodash already exists) to search farm**   
before adding debounce it for used **304 ms render time**
after adding debounce it used just **1.5 ms render time (faster almost 300x )**
I hope you review my PR
=> perf: add debounce to search farm

src/state/achievements/helpers.ts
It is generally a bad practice to use string literals in queries / mutations as this doesn't properly secure the passed values.
This would also makes it easier to manage / re-use queries in the future.
=> refactor(graphql): Change string literals to variables in gql requests

src/views/Lottery/components/PastLotteryRoundViewer/PastLotteryActions.tsx
=> refactor: Remove redundant divs on past lottery round

src/components/TicketInput/TicketInput.tsx
=> fix: Add extra space to ticket symbol and remove redundant div

src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx
Fixes #920 
When price is loading: 
After loaded
=> fix: (farms) Earned cake usd price 0 when price is loading

src/views/Farms/components/FarmTable/Liquidity.tsx
Once wrapping the code in the `useMemo`, in [this PR](https://github.com/pancakeswap/pancake-frontend/pull/909), the TS compiler started throwing a type mismatch error in `Farms.tsx`, on line `230`.
It is caused because `LiquidityProps.liquidity` is of type `number`, while the `FarmsWithStakedValue.liquidity` is of type `BigNumber`.
=> fix: Liquidity type mismatch

src/views/Pools/components/PoolCard.tsx
We were using a ternary operator to check if there is a `pendingTx`, if so we'd set the `text` of the button to be "Compounding", however, when compounding we don't really use `pendingTx` and for that reason we were displaying "Compounding" when actually harvesting.
In this PR that logic is removed, and the button remains with the "Compound" text when harvesting.
Closes #893
=> fix: Pool card shows compounding when click harvest

src/config/constants/nfts.ts
Fix 'Dollop' collectible not showing as `In Wallet` because of identifier typo.
```
$ getTokenIdAndData TypeError: Cannot read property ‘identifier’ of undefined
```
=> fix(collectibles): Dollop identifier

src/hooks/useAuth.ts, src/state/profile/index.tsx
Currently user profile is not cleared from redux when `logout` action is called.
This causes things such as profile picture to remain in the navbar & edit profile button to remain on the profile page.
=> fix(auth): Clear profile state on logout

src/config/constants/farms.ts, src/config/constants/pools.ts
Note. farm already exists and so do all the images.
Pool
--------------
**Earn:** SWINGBY 
**Earn Token Contract Address:** https://bscscan.com/address/0x71DE20e0C4616E7fcBfDD3f875d568492cBE4739
**Rewards per block:** 0.21527 SWINGBY
**Start block:** 6755400
**End block:** 8483400
**Project website:** https://swingby.network/
Farm only changing to 2x
=> feat(farm/pool): Swingby

src/views/Farms/Farms.tsx
I noticed that there is practically no margin separating the content of the farm cards, from the control, on smaller screen (mobile devices), so I added some margins there.
Here's how it looked like before:
And here's how it looks like in the PR:
I chose `32px`, because to be consistent with the margins between the cards. 
Let me know what you think.
=> fix: Add margin to farm controls on small screens

src/hooks/ticker.ts
Hook for opening a web socket connection to Binance's ticker API. Currently only supports `bnbusdt`.
=> feat: Binance token pair ticker

src/views/TradingCompetition/components/Section/index.tsx, src/views/TradingCompetition/index.tsx
The TradingCompetition `<Section>` component extends the `<Page>`, component (we wanted the page styles) - but this means the banner is added to every section on the page.
This fixes that, and because of styling difficulties when wrapping the competition page within the `<Page>` component, instead this adds the banner directly to the competition page (note for when we need to remove it).
=> feat(competition-migration-banner): Fix Page styles and banner on trading competition page

src/state/farms/fetchFarmUser.ts, src/state/farms/fetchFarms.ts, src/state/farms/index.ts, src/state/hooks.ts, src/state/types.ts, src/utils/farmHelpers.ts, src/views/Farms/Farms.tsx, src/views/Farms/components/FarmTabButtons/index.tsx, src/views/Home/components/EarnAPRCard.tsx
New tab in Farms page for Archived farms.
Fetching logic slightly reworked so it doesn't fetch data for archived pools unless you're looking at them.
=> Farm Archived tab

src/config/constants/contracts.ts, src/utils/addressHelpers.ts
There was a typo `mullticall` that was fixed to `multicall`
=> Fixed typo

src/views/Predictions/components/RoundCard/SetPositionCard.tsx
This could be bug in input range component. Which you can test it via this code
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_range
put this to input 
`<input type="range" id="vol" name="vol" min="0" max="0.1259255862692049"  step="any">`
I set step to 15 decimal digits, which input type range rounds it to 15 from 16 after some point that affects max value check.
=> fix: (prediction) Slider cannot be set to max by sliding it to the right

src/state/hooks.ts, src/state/predictions/helpers.ts, src/state/predictions/index.ts, src/state/types.ts, src/views/Predictions/components/RoundCard/OpenRoundCard.tsx, src/views/Predictions/components/RoundCard/SetPositionCard.tsx, src/views/Predictions/components/RoundCard/index.tsx, src/views/Predictions/hooks/usePollRoundData.ts, src/views/Predictions/index.tsx
`<RoundCard />` now makes a fetch on initial load for the user's bets. This will ensure that the entered tag always shows even if a round has greater than 1,000 bets.
=> fix(predictions): Fetch user bets on load

src/views/Farms/components/DepositModal.tsx, src/views/Farms/components/WithdrawModal.tsx
If it is enabled it can be misunderstood from users to cancel the pending confirmation
=> fix: (farms) Disable cancel button on deposit and withdraw modals when pending confirmation

src/views/Pools/components/PoolTabButtons.tsx
**Environment:**
Device and OS: Any
Browser: Any
Reproducibility rate: 100%
**Steps to reproduce:**
1. Set theme to dark
2. Go to the Pool view
3. Click on stacked only switch
**Actual result:**
**Expected result:**
=> Fix pool "stacked only switch" UI in dark theme

src/__tests__/utils/compoundApyHelpers.test.ts, src/components/ApyCalculatorModal/index.tsx, src/utils/compoundApyHelpers.ts, src/views/Pools/components/CakeVaultCard/index.tsx, src/views/Pools/components/PoolCard/AprRow.tsx
- Add APR 'fee' logic to our APY helper
- Slight UI changes, adding an explainer when a performance fee _is_ modifying the APY/APR calc
- Update tests
=> feat(apy-calculator): Allow APY calculator to handle performance fee deductions

src/hooks/cakeVault/useWithdrawalFeeTimer.ts, src/views/Pools/components/CakeVaultCard/UnstakingFeeCountdownRow.tsx, src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
unstakingFee was mistakenly called performanceFee in some places.
=> chore: Rename unstaking fee related variables

src/contexts/Localization/Provider.tsx
Before if the key was not in the translation file it would return the key without interpolation. Now it still interpolates the key even if it is not found.
=> refactor: Interopolate even when missing key

src/views/Pools/components/PoolCard/AprRow.tsx
Adds conditional 'APR' / 'APY' tooltip text:
APY
APR
=> chore(apr-row): Make tooltip text conditional depending on whether it's an auto vault

src/config/constants/pools.ts
Set `isFinished` for the following pools to 'true'
> - watch
> - xmark
> - bmxx
> - iotx
> - bor
> - bopen
=> chore(pools-config): Update finished pools

src/views/Pools/components/CakeVaultCard/RecentCakeProfitRow.tsx, src/views/Pools/components/CakeVaultCard/UnstakingFeeCountdownRow.tsx, src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx, src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultApprovalAction.tsx, src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultStakeActions.tsx, src/views/Pools/components/CakeVaultCard/VaultCardActions/index.tsx, src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx, src/views/Pools/components/CakeVaultCard/index.tsx, src/views/Pools/index.tsx
- Triggered by fixing the incorrect assigning of an account string's default to `true` - https://github.com/pancakeswap/pancake-frontend/blob/bec23a0b7e9674e015d88ddcbd780d6ca5ac14af/src/views/Pools/components/CakeVaultCard/UnstakingFeeCountdownRow.tsx#L26
- Initially the cake vault followed the same pattern as the pool cards - use a single function call within `pools/index.tsx` to get `account`, and then pass it down to all components that required it.
- While this may provide a tiny bit of optimisation to the pool cards (where every function that is called, is called 60 times) - it is unnecessary in the vaults and complicates things.
=> chore(cake-vault): Remove unnecessary passing of account in the Cake Vault, instead fetch it from the provider

src/views/Pools/components/CakeVaultCard/UnstakingFeeCountdownRow.tsx
Condition for when a user has deposited to the vault but no longer has a withdrawal fee (i.e. 72 hrs has passed since depositing).
- If a user has made a deposit to the CAKE vault (`lastDepositedTime` is true), but doesn't have a fee to pay (`hasUnstakingFee` is false): then show a 0% staking fee
- The impacts both the card, and the withdrawal modal
Staked, no fee
Staked, has fee
Not staked
=> fix(fee-countdown-row): Conditional for handling fee row if a user's fee time has expired

src/views/Home/components/EarnAssetCard.tsx
No need to do the computation on every render
=> refactor: (earn asset card) Move asset list to constant since pools configuration is constant

src/views/Profile/ProfileCreation/UserName.tsx
=> fix: Web3 utf8ToHex must be called to allow hex-like usernames registration

src/views/Predictions/components/History/BetDetails.tsx, src/views/Predictions/components/RoundResult/RoundResult.tsx
Removes the payout rows from the expired round card and only show them in the history.
=> refactor(predictions): Remove payout row from expired cards

src/views/Pools/components/PoolCard/CardActions/index.tsx, src/views/Pools/components/PoolCard/index.tsx
If user unapproved a pool (e.g. using https://app.unrekt.info/) the pool will not show Enable button (and you'll get failed transaction if you'd try to stake more CAKE). The check for staked balance seems to be not needed at all here.
=> fix: Unapproved pool does not show enable button

src/hooks/cakeVault/useGetVaultBountyInfo.ts, src/views/Pools/components/BountyCard.tsx, src/views/Pools/components/BountyModal.tsx
- Reorganise vault bounty hook to no longer convert the contract responses into string display balances
- Improve var names. Fewer 'magic numbers'
- Add ternary to check user account is connected on the confirm button
=> chore(cake-vault-bounty): Reorganise vault bounty hook, Improve var names. Account check

src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
I recently tested a 100% withdrawal transaction, and it didn't call the `withdrawAll` contract call, leaving some dust in the vault
Transaction confirms `withdraw` was called, not `withdrawAll` https://bscscan.com/tx/0x2d74d9d962c6264a9fb560abe94bdc4bec410fa32473cd9a97dd276f59204a0f
This PR modifies the threshold at which a `withdrawAll` call will be triggered:
From
> withdrawAll if `0.0000000000002` or fewer CAKE would remain in the vault
to
> withdrawAll if `0.000001` or fewer CAKE would remain in the vault
=> fix(cake-vault-withdrawal): Increase withdrawAll threshold - make it trigger more easily

src/views/Predictions/components/RoundCard/CollectWinningsOverlay.tsx
Fixes #1094 
@hachiojidev I think I found the root cause of that issue. I tested it by mocking response of that request with big response times, and I was able reproduce it. As you can see the response times of that graph api requests (huge response times)
We have to clean the stop the async response processing when useEffect function is cleaned up (in our case it happens after claiming the winnings and before re-rendering)
I keep the local collect state (just changed the name) to stop making further requests after successful collection
=> fix: Collect winnings button pops up again after successful claim

src/views/Pools/components/PoolCard/CardActions/StakeActions.tsx
Use the correct token decimal value for the `stakedTokenBalance`
=> fix(pool-card-stake-actions): Use correct token for decimalisation in stakedTokenBalance

src/views/Predictions/Mobile.tsx, src/views/Predictions/index.tsx
The screen is not displayed when the width is 853 to 967.
=> fix: specific section is not displayed in Prediction page

src/views/Farms/components/FarmCard/FarmCard.tsx, src/views/Pools/components/CakeVaultCard/index.tsx, src/views/Pools/components/PoolCard/StyledCard.tsx, src/views/Pools/components/PoolCard/StyledCardHeader.tsx, src/views/Pools/components/PoolCard/index.tsx
- Shiny animated gradient for promoted pools (currently just auto CAKE) and CAKE - BNB farm
- Change card header logic to be bubblegum gradient when staked
and cardHeader gradient when not
=> feat(pool-cards): Add new bg gradient style to pool cards and accent farm card

src/hooks/cakeVault/useWithdrawalFeeTimer.ts
Previously, the Vault withdrawal fee timer would fetch the seconds remaining once on component mount, now it sets an interval that updates the `currentSeconds` value every 1000ms, meaning the timer will count down as the user sits on the page.
=> feat(withdrawal-fee-timer): Make vault timer update per second that passes

src/config/constants/pools.ts, src/views/Pools/index.tsx
- Create a new pools data array - `stakedOnlyFinishedPools`. Shown when the 'Staked only' toggle is active
- change `ramp` (sousId `129`) to finished in config
- change `dexe` (sousId `117`) to finished in config
- We'll be less reliant on these config changes for finished pools when Memoyil's PR  is in https://github.com/pancakeswap/pancake-frontend/pull/1036
=> feat(pools): Staked only toggle now works for finished pools

src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx, src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
=> fix: (pools) Zero with decimals shown in amount when bunny slider moved back to zero

src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
Two issues in live
- STAKING: Pools with a `stakingLimit` of `BIG_ZERO` are returning the stakingLimit value (0), not the user token balance (`stakingTokenBalance`)
- UNSTAKING: There's no specific handling for determining how much a user can unstake in the FE. Currently - it uses the same as the amount that you can stake.
Preview - https://pools-fixes-13-5.netlify.app/
=> fix(stake-modal): Catch for zero staking limit & handling for unstaking

src/hooks/cakeVault/useWithdrawalFeeTimer.ts, src/state/hooks.ts, src/views/Pools/components/BountyCard.tsx, src/views/Pools/components/CakeVaultCard/RecentCakeProfitRow.tsx, src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx, src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultStakeActions.tsx, src/views/Pools/components/CakeVaultCard/VaultCardActions/index.tsx, src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx, src/views/Pools/components/CakeVaultCard/index.tsx
PR is doing a couple of things 
- Replace any instances where `useGetApiPrice` is being used to access the price of CAKE, and replace it with `usePriceCakeBusd`
- Clear timer for `useWithdrawalFeeTimer` when `doesUnstakingFeeApply` is false, to prevent unnecessary re-renders
- useMemo to wrap the returns of all BigNumbers within the `useCakeVault`. If one of the return values was used as a useEffect/Memo dependency, then it would trigger a re-render as it is a new class instance with a different reference
=> feat(cake-api-price): Replace API price with Farms price for CAKE

package.json
Removed `--log-level error` so we can see the effected files in the GH action
=> chore: Remove log level from prettier check

src/components/Select/Select.tsx, src/views/Home/Home.tsx, src/views/Lottery/components/YourPrizesCard/NoPrizesContent.tsx, src/views/Pools/components/PoolCard/AprRow.tsx, src/views/Pools/components/PoolCard/CardFooter/index.tsx
Some small styling improvements.
- Help Icon on Pool Card (Flex instead of Box)
- Home cards - unify margin/gap on mobile (Large screens unaffected)
- Lottery - no prizes to collect alignment
- Selects - Prevent text / user selection
- TooltipText on Pool cards, ugly underline issue
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
=> Styling improvements

src/views/Lottery/components/PastDrawsHistory/HistoryChart.tsx
I modified the HistoryChart a little and gave the chart.js tooltip the PCS look, I also unified the number formatting and naming.
Before:
After:
Before:
After:
=> HistoryChart (Chart.js) improvements

src/views/Ifos/components/IfoFoldableCard/Achievement.tsx
=> fix: (IFO) ~Infinity LP shown when price is being loaded in Achivements

src/views/Lottery/components/PastDrawsHistory/HistoryChart.tsx
The lottery history chart.js had two loading indicators, the loading spinner and a text, now only one loading indicator is used.
Before lottery history is ready:
Before chart.js is ready (also appeared when changing the "last" value in dropdown):
Before:
After:
=> style(lottery): Two loading indicators

src/views/Lottery/components/PastDrawsHistory/Legend.tsx
=> style(lottery): Legend colors incorrect in dark mode

src/views/Predictions/components/RoundCard/CalculatingCard.tsx
=> fix: Position of info icon in calculating card

src/state/hooks.ts
We were still getting price references for CAKE/BUSD & BNB/BUSD from v1 farm pids, I've updated these to reflect our v2 farms:
```
{
pid: 251,
lpSymbol: 'CAKE-BNB LP',
lpAddresses: {
97: '0x3ed8936cAFDF85cfDBa29Fbe5940A5b0524824F4',
56: '0x0eD7e52944161450477ee417DE9Cd3a859b14fD0',
},
token: tokens.cake,
quoteToken: tokens.wbnb,
},
{
pid: 252,
lpSymbol: 'BUSD-BNB LP',
lpAddresses: {
97: '',
56: '0x58F876857a02D6762E0101bb5C46A8c1ED44Dc16',
},
token: tokens.busd,
quoteToken: tokens.wbnb,
},
```
=> fix(hooks-bnb-cake-price-busd): Update cake and bnb busd price hooks to use v2 farm

src/utils/bigNumber.ts, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
Comments, and change type for possible edge-case bugs.
`gasPrice - String` - https://web3js.readthedocs.io/en/v1.3.3/web3-eth-contract.html#id33
=> fix: Type for gasPrice

src/config/localization/translations.json, src/views/Home/components/EarnAPRCard.tsx, src/views/Home/components/EarnAssetCard.tsx
Since we have different components for apr and asset text, this is the solution that i found. It is better than nothing I think.
=> feat: Add translations for earn cards in home page

src/state/farms/fetchFarms.ts, src/state/hooks.ts, src/state/types.ts
Preview: https://lp-price-calc-fix.netlify.app/
LP price was coming through incorrectly from the `useLpTokenPrice` hook.
Previous price calculations were being made using `farm.lpTotalSupply` - _all_ LP tokens & `farm.lpTotalInQuoteToken` - _staked_ quote tokens in the MC contract. The staked total is about 10% less than the raw total. As we're using the raw total LP supply, we should also be calculating the LP unit price using the raw LP token amounts.
I've also made the maths in the `useLpTokenPrice` slightly more verbose and easier to understand.
=> fix(lp-price-hook): Add raw LP token totals to fetchFarms and re-calculate LP token price

src/config/constants/farms.ts, src/config/constants/pools.ts
note: token config etc already exists because this is a boost
pool:
--------------
**Earn:** HGET
**Earn Token Contract Address:** https://bscscan.com/token/0xc7d8d35eba58a0935ff2d5a33df105dd9f071731
**Rewards per block:** 0.03553 HGET
**Start block:** 7592800
**End block:** 8456800
**Token Decimals:** 6
**Project website:** https://www.hedget.com/
farm
---------------
PID 296 (HGET-BNB) to 0.5x
0.5x multiple to run for 14 days from 5am UTC on May 21st (Block 7592800) until 5am UTC on June 4th (Block 8456800), before reverting back to 0.1x CAKE rewards after that.
=> feat(farm/pool): HGET

src/views/Pools/components/BountyModal.tsx
Default gas limit setting on Cake vault bounty harvest (same as pools).
=> chore(vault): Harvest gas limit

src/config/localization/translations.json, src/views/Ifos/components/IfoFoldableCard/Achievement.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx, src/views/Ifos/components/IfoFoldableCard/index.tsx
Things done
-Added finisherd card ribbon when finished but active
-Grayfilter achievement when finished
-Change active profile warning when finished
Before:
After:
=> feat: (IFO): Add finished tags and grayfilter when Ifo pool card finished but still active

src/views/Pools/components/CakeVaultCard/index.tsx
=> fix: (pools) Cake vault card actions margin top to be aligned with other pool cards

src/state/hooks.ts, src/views/Pools/index.tsx
Extracts the pool data from the global hook and moves to the pool's view.
=> refactor: Move public pools polling to pools view

src/App.tsx, src/state/hooks.ts
Moved the global polling of the block number to its own hook. No logic has changed.
=> refactor: Extract block number polling into its own hook

src/state/hooks.ts
- usePriceBnbBusd hook was returning `token` (busd) .busdPrice instead of `quoteToken` (bnb) .busdPrice
=> fix(hooks): Fix usePriceBnbBusd hook to use quoteToken price

src/views/Predictions/components/RoundCard/SetPositionCard.tsx
To remove when new smart contract is live, or to update when BSC network fees are updated.
=> feat(prediction): Default gasPrice on BetBull/BetBear

src/views/Home/components/CakeHarvestBalance.tsx, src/views/Home/components/CakeWalletBalance.tsx, src/views/Home/components/CakeWinnings.tsx, src/views/Home/components/EarnAPRCard.tsx, src/views/Lottery/components/PrizeGrid.tsx, src/views/Lottery/components/TotalPrizesCard/index.tsx, src/views/Pools/components/BountyCard.tsx, src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx, src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx, src/views/Pools/components/PoolCard/CardActions/HarvestActions.tsx, src/views/Pools/components/PoolCard/CardActions/StakeActions.tsx, src/views/TradingCompetition/components/YourScore/UserPrizeGrid.tsx, src/views/TradingCompetition/helpers.ts
Root cause: usePriceCakeBusd() returns NaN that also not equals to 0 (which makes our condition always true from the beginning in that component) which causes in firefox browser to not rerender the component when price is available
To reproduce: Check Farms & Staking section on homepage with Production build on firefox
Issue:
=> fix: Change Cakebusd price checks against 0 equality to greater than

src/state/farms/fetchFarm.ts, src/state/farms/fetchPublicFarmData.ts
Issue mainly happens on firefox but might also happen on other browsers as well. If one of the farms fetching got stuck, that causes already fetched farms data to not be pushed to redux. Therefore user cannot see farm details as well as cake/busd price for very long time. Since we are using slowRefresh there user has to wait additional one minute to renew the request (and that request might also get stuck).  So I added timeout promise alongside with fetch promise and use promise race.
Review: https://deploy-preview-1318--pancakeswap-dev.netlify.app/
1. Open main page in firefox
2. See cake price is not loading 
3. If it is loaded quickly refresh the page and check it again.
=> fix: (farms) Farm data and cake price cannot be seen for very long time mainly Firefox

src/views/Predictions/components/Label.tsx, src/views/Predictions/components/Menu.tsx
Review: https://deploy-preview-1373--pancakeswap-dev.netlify.app/
2. Select greek language for example
3. Check timer label in top right
4. See the minute unit is not translated
Before: 
After:
=> fix: (prediction) Add missing timer label translation

src/components/Tags.tsx
Review: https://deploy-preview-1372--pancakeswap-dev.netlify.app/
Just took the part that @hachiojidev did in https://github.com/pancakeswap/pancake-frontend/pull/1301/files#diff-28711da0cf1463b4fe38771fa0db631fb3fb913ade15fb5ddc723611b781ab30 :)
1. Change language to Russian for example
2. Go to pools 
3. Check bottom of the pool card
4. See Auto or Manual tag is not translated
Before:
After:
=> fix: (tag) Add missing tag translation

src/config/localization/translations.json, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx, src/views/Ifos/components/IfoFoldableCard/Timer.tsx, src/views/Ifos/components/IfoQuestions/config.ts
Review: https://deploy-preview-1368--pancakeswap-dev.netlify.app/
To reproduce the issues: 
1. Go to ifo page 
2. Check translation of titles of the IfoPoolCards is not translated (Basic Sale and Unlimited Sale) (it is available in many languages)
3. Check in details section the 4th question's (Where does the participation fee go?) answer is not translated.
4. Check "(blocks)" translation next to the remaining Time above the IfoPoolCards (it will be visible in the next IFO)
=> fix: (IFO) Add missing translations in IFO

src/__tests__/config/translations.test.ts, src/views/TradingCompetition/components/Rules/FAQs.tsx
Review: https://deploy-preview-1367--pancakeswap-dev.netlify.app/
To reproduce the issue: 
1. Change language to French or Magyar for example (the text that is missing is translated there)
2. Go to Team Battle
3. Go to FAQ
4. Click details of "How do I claim my prize(s)?" (the bottom one)
5. See the answer is not translated
I also added a rule to unit test that catches these translation keys
=> fix: (Team Battle) Add missing translations in team battle and fix test to check translations with carriage return

src/state/farms/fetchPublicFarmData.ts
- Increase time before dropping farm fetch requests from 5s to 9s
- Add multiplier to return type
=> fix(fetch-public-farm-data): Increase timeout on farmFetch to 9s

src/views/Pools/components/PoolsTable/Cells/TotalStakedCell.tsx, src/views/Pools/index.tsx
Issues: 
1. Total staked column name in pools row
2. Sort by items in dropdown menu
3. Placeholder text in search input
=> fix: (pools) Add missing translations in pools table view

src/views/Pools/components/PoolsTable/Cells/EarningsCell.tsx
=> fix: (pools) Help icon in cake vault row shows default date when there is no earnings

src/hooks/useHasCakeBalance.ts, src/hooks/useTokenBalance.ts, src/views/Home/components/CakeWalletBalance.tsx, src/views/Home/components/LotteryCard.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeButton.tsx, src/views/Ifos/components/IfoSteps.tsx, src/views/Lottery/components/TicketCard/TicketActions.tsx
At the moment the state returned by `useTokenBalance` defaults to `BIG_ZERO`
Meaning there's no difference in state between these two scenarios:
- ‘finished fetching, user has none of that token’
- ‘not yet fetched the user balance’
In the new Lottery, we may want to conditionally send the users to purchase more CAKE if they have a zero balance. We wouldn't want to show that while the user balance is still being fetched. The new `fetchStatus` enum allows us to do this.
=> chore(useTokenBalance): Add hasFetchedBalance state to useTokenBalance

src/components/PageSection/CurvedDivider.tsx, src/components/PageSection/index.tsx, src/components/PageSection/svg/CurvedSvg.tsx, src/views/LotteryV2/components/TicketsNumberButton.tsx, src/views/LotteryV2/pageSectionStyles.tsx, src/views/LotteryV2/svgs/TicketPurchaseCard.tsx, src/views/LotteryV2/svgs/index.tsx, src/views/TradingCompetition/index.tsx
Changes that impact live pages:
- Tidy up `PageSection` component styles - used by the Trading Competition. All tested locally.
Changes that do not impact live pages:
- Initial SVGs/ style consts for lottery
- Tiny `TicketsNumberButton` comp
=> (styles) Add some initial new lottery styles

src/state/farms/fetchPublicFarmData.ts
The race condition for the farm fetch was causing more problems than it was solving. The impact for a lot of users was that the farms never fetched within the timeout, and this has the knock-on impact of meaning price data (used for APRs throughout the site) was missing.
This PR removes the race condition between the farmFetch and the timeout
https://lucid-haibt-de8af4.netlify.app/
=> chore(fetch-public-farm-data): Remove race promise timeout from fetchFarm function

src/__tests__/config/translations.test.ts
We have seen both usages of search input's placeholder keys are wrong, so it is worth to add unit test for it
=> chore: (test) Add translation check rule for search input placeholder in unittest

src/views/Lottery/components/PastDrawsHistory/HistoryChart.tsx
To review:
https://deploy-preview-1422--pancakeswap-dev.netlify.app/
Reproduce to issue:
2. Hover on history chart graphic (click if you are on mobile)
3. Check tooltip legend colors all white
Before:
After:
=> fix: (lottery) History chart tooltip legend colors

src/components/ApyCalculatorModal/index.tsx
Reproduce to issue
1. Go to farms
2. Change language to italian
3. Select any apy
4. Check table titles
**Roi and first title merged since the first one is very long, and bottom part has empty area at right when it is too wide**
**After alignment**
========================
- Width of modal depends on the widest grid item whose width applied to each cell makes modal very wide
- APY text merged with roi number when it is too long
**After alignment**
=> fix: (apymodal) Long grid titles shown together in another languages

src/hooks/useApproveConfirmTransaction.ts, src/views/Profile/components/ApproveConfirmButtons.tsx
Two changes:
*One*
- Enable the `ApproveConfirmButtons` to receive a `buttonArrangement` prop. This determines whether the approve & confirm buttons should be laid out in a row (the current style, set as the component default), or 'sequentially' (i.e. one after the other), as is a common pattern in other areas of the site (and will be used immediately within the Lottery).
```
<ApproveConfirmButtons
isApproveDisabled={isApproved}
...
buttonArrangement={ButtonArrangement.SEQUENTIAL}
/>
```
`isApproved` is false, therefore the approval button is rendered:
`isApproved` is true, therefore the confirm button is rendered:
*Two*
- Call an `onApproveSuccess()` function when there is a transaction receipt from the `handleApprove` function within the `useApproveConfirmTransaction` hook. This allows …
=> feat(approve-confirm-buttons): Allow different visual arrangement of ApproveConfirmButtons. Add onApproveSuccess func

src/contexts/RefreshContext.tsx, src/hooks/useTabVisibility.ts
This will reduce amount of requests made when tab is hidden (not focus)
For example in pools when tab or window is hidden, Amount of requests is reduced from ~600 to ~30 per minute
Check it from
https://deploy-preview-1382--pancakeswap-dev.netlify.app/
=> feat: Reduce amount of requests when tab is hidden

src/views/Predictions/Positions.tsx
To review:
https://deploy-preview-1427--pancakeswap-dev.netlify.app/
Issue: Swiper sensivity is too high that it moves multiple cards even with slow swipe
Before: 
https://user-images.githubusercontent.com/2213635/120577704-f7314480-c424-11eb-9833-6da63812d3ac.mp4
After: 
https://user-images.githubusercontent.com/2213635/120577667-eb458280-c424-11eb-925b-c4ef04f277fe.mp4
=> fix: (prediction) Reduce speed of swiper to make smooth transition between cards

src/views/Predictions/components/RoundCard/SetPositionCard.tsx
To review:
https://deploy-preview-1447--pancakeswap-dev.netlify.app/
Bnb amount lose precision when converting to number instead of string for representation
2. Open set position card
3. Check bnb amount in "Balance: ...."
4. Compare the amount with bscscan balance or other api
=> fix: (prediction) Show correct bnb balance with precision

src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx, src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
To review: 
https://deploy-preview-1443--pancakeswap-dev.netlify.app/
To Reproduce the issue: 
1. Go to pools
3. Click stake button any of the pools
4. Check Max button translation
Before:
After:
=> fix: (pools) Add missing translation of max percentage button text

src/views/Predictions/components/RoundCard/SetPositionCard.tsx
To review: 
https://deploy-preview-1458--pancakeswap-dev.netlify.app/
1. Go to predictions in mobile
2. Select down or up in open round card
3. Try to move bunny slider 
4. See swiper moves instead of slider
Before: 
https://user-images.githubusercontent.com/2213635/121023689-cf830900-c7a3-11eb-9e3d-8c807357b397.mp4
After:
https://user-images.githubusercontent.com/2213635/121023735-da3d9e00-c7a3-11eb-915c-327821970b97.mp4
=> fix: (predictions) Swiper moves when trying to move slider in set position card

src/components/Balance.tsx
Add balance prefix/unit regardless of whether the value is 0
i.e. instead of `0.00` (dollars)
show
`~0.00 USD`
=> chore(balance): Show prefix and unit for 0 balances

src/components/Banner/Banner.tsx, src/hooks/usePersistState.ts, src/views/Farms/Farms.tsx, src/views/Pools/index.tsx, src/views/Predictions/index.tsx, src/views/Profile/PublicProfile.tsx
This change to the `usePersistState` hook allows for saving additional types like BigNumber to local storage by allowing consumer to pass in a hyrdate and dehydrate function.
=> feat: Hydrate/dehydrate options for usePersistState

src/components/ModalInput/ModalInput.tsx
To review:
https://deploy-preview-1446--pancakeswap-dev.netlify.app/
To Reproduce the issue:
1. Go to farms
2. Click withdraw on any farm that you staked
3. Put amount with more than 20 decimals
4. Check error on console
=> fix: (farms) Error when put amount with decimals more than 18

src/views/Lottery/components/PastDrawsHistory/PastDrawsHistoryCard.tsx
3. Check history chart show last select dropdown menu
4. Check Max text translation
=> fix: (lottery) Add missing translation for select in history chart

src/views/TradingCompetition/components/BattleBanner/index.tsx
To review:
https://deploy-preview-1477--pancakeswap-dev.netlify.app/
1. Go to team battle
2. Change theme to dark
3. Check banner text "Compete with other teams to win CAKE, collectible NFTs, achievements & more!" under "$200,000 in Prizes!"
=> fix: (trading battle) Banner text not visible in dark mode

src/views/Pools/components/CakeVaultCard/index.tsx, src/views/Pools/components/PoolCard/StyledCard.tsx, src/views/Pools/components/PoolCard/StyledCardHeader.tsx
Not sure what triggered it, but some recent card style changes have removed the need for different border radii for promoted pools with rainbow borders. The code change is positive but the cake vault card looks nasty atm.
Live, icky:
After this PR's changes:
=> style(cake-vault-card): Remove cake-vault specific border radii

src/views/Predictions/components/RoundCard/SetPositionCard.tsx
Reproduce the issue:
2. Logout from your wallet
3. Open set position card
4. Try to swipe on the slider when it is disabled
=> fix: (prediction) Prevent swipe in set position when slider is active only

src/config/constants/teams.ts, src/views/Teams/components/TeamListCard.tsx
1. Go to team & profile -> leaderboard
3. Check teams description text
Should be translated as well
=> fix: (teams) Add missing description translation in team list card

src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
To review:
https://deploy-preview-1484--pancakeswap-dev.netlify.app/
1. Go to pools tables in mobile or tablet (especially)
2. Check action details
3. See empty space at the end of the action panel
Before:
After:
=> fix: (pools) Remove redundant empty space visible in mobile and tablets in action panel

src/views/Predictions/components/RoundCard/SetPositionCard.tsx
To review: 
https://deploy-preview-1454--pancakeswap-dev.netlify.app/
To Reproduce the issue:
2. Set position from card
3. Click max 
4. Check diff between your bnb balance and max (should be 0.01)
Before: 
After:
=> fix: (predictions) Use bignumber in set position instead of number to avoid precision errors

src/components/ModalInput/ModalInput.tsx, src/views/Farms/components/FarmCard/HarvestAction.tsx, src/views/Farms/components/FarmCard/StakeAction.tsx, src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx, src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
To review: 
https://deploy-preview-1460--pancakeswap-dev.netlify.app/
Issue 1
1. Go to farms 
2. Click unstake
3. Check balance in modal input
4. Click max 
5. Check the diff between them (balance should not be rounded up)
Issue 2
1. Go to farms 
2. Check harvest amount
3. Check diff between raw harvest balance and after returned from getBalanceNumber
Although diff is quite small it is better to stick with getBalanceAmount.
4. Harvest balance should not be rounded up too.
=> fix: (farms) Use getBalanceAmount instead of getBalanceNumber

src/views/Farms/components/FarmCard/CardActionsContainer.tsx
To review:
https://deploy-preview-1495--pancakeswap-dev.netlify.app/
LP symbol converted to uppercase in farm cards then passed to staked components which makes LP price return error with undefined pid when symbol has lowercase characters in farm config
Issue only occurs when there is a stake amount in those farms
Fixes #1493 #1496
To reproduce the problem
1. Go to farms
2. Select card view
3. Find a staked farm that has lower case character (originally) (such as bmxx-bnb)
4. Check console for error
=> fix: (farms) Fix farmcard loading error when has staked amount in farms with lowercase characters

src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx
To review:
https://deploy-preview-1490--pancakeswap-dev.netlify.app/
1. Go to farms
2. Check a farm that you don't have earnings
3. See harvest button enabled
=> fix: (farms) Harvest button is enabled when 0

src/views/Farms/components/FarmCard/HarvestAction.tsx, src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx, src/views/Farms/components/FarmTable/Actions/styles.ts
To review:
https://deploy-preview-1491--pancakeswap-dev.netlify.app/
With this all usd amounts in farms will be in same representation.
1. Go to farms 
2. Go to a farm that you have earnings
3. Check amount in usd style in harvest
=> feat: (farms) Use balance component for usd amounts instead of different components

src/views/Farms/components/FarmCard/CardActionsContainer.tsx, src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx, src/views/Farms/components/FarmTable/Actions/StakedAction.tsx, src/views/Farms/components/FarmTable/Actions/styles.ts
To review:
https://deploy-preview-1492--pancakeswap-dev.netlify.app/
There is a Todo above Subtle style component decleration which is waiting to be fixed.
https://github.com/pancakeswap/pancake-frontend/blob/5bc14994d8cd1334adb48acf0c40a2e68162c64b/src/views/Farms/components/FarmTable/Actions/styles.ts#L36
=> feat: (farms) Use Text component instead of Subtle and Title

src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
To review:
https://deploy-preview-1500--pancakeswap-dev.netlify.app/
Reproduce the issue
1. Open webpage in mobile
2. Go to pools
3. Select table view
4. Check details of one of the pools
5. See missing colons in some descriptions
Before: 
After:
=> fix: (pools) Add missing colons in details descriptions in pools table

src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx
To review: 
https://deploy-preview-1499--pancakeswap-dev.netlify.app/
1. Go pools
2. Go live ones
3. Go to pool cards
4. Click detail of any pool (except auto vault)
5. Check Block countdown and check max stake per user info
Block coundown should be clickable and forwards you to bscscan like in pools table. 
Max stake per user info should be visible in card details.
=> feat: (pools) Add link to bscscan countdown and max stake info in pools cards details

src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx, src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx, src/views/Pools/components/PoolsTable/Cells/EndsInCell.tsx
1. Go to pools
2. Check block count down bscscan link before pool started
3. It should show the start block instead of end block
=> fix: (pools) Countdown link should link to start block before pool started

src/views/Pools/components/BountyCard.tsx, src/views/Pools/components/BountyModal.tsx
To review: 
https://deploy-preview-1439--pancakeswap-dev.netlify.app/
1. Check the difference between data shown in pools page and bounty modal when it is open for a while
Before:
https://user-images.githubusercontent.com/2213635/120809187-1c6ba300-c54a-11eb-9354-10551b7db37b.mov
After:
https://user-images.githubusercontent.com/2213635/120809175-1aa1df80-c54a-11eb-9bb0-ba77b73b1a69.mov
=> fix: (pools) Bounty modal shows obsolete values when cake vault data changes

src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx, src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx, src/views/Pools/components/PoolsTable/Cells/TotalStakedCell.tsx
To review:
https://deploy-preview-1502--pancakeswap-dev.netlify.app/
To reproduce issue:
1. Go to pools open in mobile
2. Go to table view
3. Go to details
4. Check total staked when pool data loading
It also fixes an issue that shows skeleton instead of the value when total staked is exact 0
Before: 
After:
=> fix: (pools) Total staked shows symbol only when loading in pools table mobile

src/hooks/useIntersectionObserver.ts, src/views/Home/components/EarnAPRCard.tsx
This feature is mainly for mobiles (where earn apr card is not visible at first sight), if user does not scroll down after opening the page, requests drops to 27 from around 600 at opening.
=> feat: (earnaprcard) Lazy load farms data to reduce amount of requests

src/views/Lottery/components/Hero.tsx
"Learn more" string is linked to the voting site in Lottery page, so I updated it to link to Medium article.
Similar change with #1532.
https://determined-bassi-fc8beb.netlify.app/
=> chore: Update lottery link on Lottery page

src/components/Balance.tsx, src/components/Timer/index.tsx, src/views/TradingCompetition/components/Countdown/index.tsx
- Add prefix & suffix props & text components
- Add handling for not rendering DD/MM/HH if any values are missing
**Notes**
Using a condition like
```
{days && (
...
)}
```
Results in a 0 being rendered, if the value is 0 (falsey), i.e.
Hence wrapping this evaluation in a `Boolean()` - so that nothing is rendered
=> style(timer): Improvments to generic Timer component

src/views/Pools/components/PoolCard/CardActions/HarvestActions.tsx, src/views/Pools/components/PoolCard/Modals/CollectModal.tsx, src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx, src/views/Pools/components/PoolsTable/Cells/EarningsCell.tsx
To review
https://deploy-preview-1557--pancakeswap-dev.netlify.app/
1. Go to pools
2. Click harvest when earning token price is being loaded
3. See NaN
=> fix: (collectmodal) NaN shown in usd price when earning token price is loading

src/components/Menu/config.ts, src/config/localization/translations.json
1. Check sidebar menu
3. Check translation of 'New' tag
=> fix: (menu) Add missing translation in menu

src/views/Pools/components/PoolCard/CardActions/HarvestActions.tsx, src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx, src/views/Pools/components/PoolsTable/Cells/EarningsCell.tsx
To review:
https://deploy-preview-1556--pancakeswap-dev.netlify.app/
1. Go to pools
2. See one of the pools (except cakes) earning token price loading
3. Check usd  (see below)
With this solution it will not show anything regarding to usd price (like in farm cards) until usd price is loaded
=> fix: (poolcard) Earning token dolar balance shows usd text only when price is loading

src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx, src/views/Pools/components/PoolsTable/Apr.tsx, src/views/Pools/components/PoolsTable/Cells/AprCell.tsx, src/views/Pools/components/PoolsTable/Cells/TotalStakedCell.tsx
To review:
https://deploy-preview-1562--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to pools
2. Select pool table
3. See issues below in desktop and mobile
Before: 
Space between apr data and icon in mobile
After:
====================
Before: 
Misalignment in apr value and icon in desktop
After:
========================
Before:
Misalignment total staked cell component
After:
=> style: (pools) Fix spaces and alignment for apr and totalstaked cell component

src/config/localization/translations.json, src/views/Farms/Farms.tsx, src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx, src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
- chore: Update farm header text (2ec1cfe)
Typically we use LP in the meaning of "Liquidity Provider". I removed "Liquidity pool" to avoid confusion.
https://goofy-brattain-cbabe7.netlify.app/farms
.
- chore: Update pool card and table text (a2716ed) 
Pool page is linked to Info site with text "Info site", Farm page is linked to there with text "See Pair Info". The latter is descriptive and more user friendly, aligned then ones in Pool page with it.
https://goofy-brattain-cbabe7.netlify.app/pools
=> chore: Update texts in farm header, pool card, pool table

src/components/ApyCalculatorModal/index.tsx
To review:
https://deploy-preview-1574--pancakeswap-dev.netlify.app/
To reproduce the issue (in Firefox, Safari mobile)
1. Go to pools or farms
2. Click apr calculator button on any farm or pool
Check the gap issue has not been reintroduced in Chrome
Before:
After:
=> fix: (Aprcalculatormodal) No space between bullet and text in bullet list

src/views/Pools/components/PoolCard/CardActions/HarvestActions.tsx
To review:
https://deploy-preview-1573--pancakeswap-dev.netlify.app/
There are redundant flex's, you should not see any difference when you run the deployment preview.
1. Go to pools
2. Switch to pool card view
=> fix: (pools) Simplify pool cards harvest actions dom

src/components/Select/Select.tsx
To review:
https://deploy-preview-1551--pancakeswap-dev.netlify.app/
1. Go to pools
2. Click sort by dropdown
3. Then click outside of the element to close it intuitively
4. Dropdown should be collapsed
=> fix: (select) Dropdown is not closed when clicking outside of the element

src/views/Farms/components/FarmTable/Multiplier.tsx
To review:
https://deploy-preview-1590--pancakeswap-dev.netlify.app/
There should not be no difference in view when reviewing
To review:
1. Farms
2. Hover in desktop on question mark next to the multiplier
3. See no difference in tooltip
=> refactor: (multiplier) Remove redundant div in multiplier tooltip

src/views/Home/components/PredictionPromotionCard.tsx
To review:
https://deploy-preview-1597--pancakeswap-dev.netlify.app
1. Change language in homepage (e.g russian, greek, indonesian,... ) both mobile and desktop
2. See it try now button and texts overlaps with card background.
=> fix: (predictioncard) Adapt prediction promotion card to different languages

src/state/achievements/helpers.ts
Achievements could show up on the subgraph before we have added it to our config.
=> fix(achievements): Bail out if we do not have achievement in config

package.json, src/config/abi/lotteryV2.json, src/config/constants/contracts.ts, src/hooks/useApproveConfirmTransaction.ts, src/views/Lottery/components/YourPrizesCard/PrizesWonContent.tsx, src/views/Profile/components/Header.tsx, yarn.lock
- Use latest lottery contract & ABI
- Bring in latest uikit & fix breaking changes (TBC - waiting on deploy)
- Change when `confirm_sending` state change fires to be before `await onConfirm()` within `handleConfirm` - this gives the user immediate feedback 
Before:
https://user-images.githubusercontent.com/79279477/123866183-aa0d9900-d924-11eb-9223-261c03685236.mov
After:
https://user-images.githubusercontent.com/79279477/123866260-b8f44b80-d924-11eb-9bb0-16e91a2aadab.mov
=> chore(lottery-v2): Update contract ABI and tweak handleConfirm hook

src/config/localization/translations.json, src/views/Farms/components/DepositModal.tsx, src/views/Farms/components/FarmCard/HarvestAction.tsx, src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx, src/views/Farms/components/WithdrawModal.tsx
To review:
https://deploy-preview-1621--pancakeswap-dev.netlify.app/
1. Go to farms
2. Click harvest on one of the farms that you staked
3. Then click reject transaction on your wallet 
4. See harvest button still disabled
Same happens for unstake or stake
=> fix: (farms) Stake and harvest buttons stuck when transaction rejected

package.json, scripts/updateLPsAPR.ts
This script was accidentally delete in one of the previous cleanup PRs
=> chore: Bring back updateLPsAPR script

src/utils/contractHelpers.ts, src/utils/multicall.ts, src/utils/types.ts
```
const booleans = await multicall<boolean[]>(abi, calls)
```
`multicallv2` is a little different as it can return null (although doesn't change the typescript message).
We can now type contract functions to make it easier to work with.
=> feat: Add structure to type contract calls

src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
To review:
https://deploy-preview-1644--pancakeswap-dev.netlify.app/
Go to pools
Check confirm button disabled correctly in modal when unstake or stake in auto cake pool.
==============
The pending state call already in handleWithdrawal and handleDeposit functions both. 
https://github.com/pancakeswap/pancake-frontend/blob/3dbb051f13dac7ac85309a2df33df50319ec9c70/src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx#L77
https://github.com/pancakeswap/pancake-frontend/blob/3dbb051f13dac7ac85309a2df33df50319ec9c70/src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx#L122
And I also put comments to correct positions
=> fix: (pools) Remove redundant set pending state calls in vault stake modal

src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
- Modify initial `getMaxPossiblePurchase` logic to factor in discounts on ticket buys
- Add input validation logic, also evaluating whether a users has enough cake based the discount modifier
- Remove some unnecessary functions in `BuyTicketsModal`
- Remove '0' default for input so Cheems no longer accidentally buys 10x the desired tickets
=> feat(lottery-v2): Factor discount into lottery max ticket buying

src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
- Hide ticket-buying shortcut buttons rather than disabling them and showing `0`
- Tested across various balances on testnet
=> fix(lottery-v2): Hide ticket shortcut button when the percentage buy is less than 1

src/views/Lottery/components/BuyTicketsModal/TicketInput.tsx
- The input you're editing should not be covered by the keyboard or other elements anymore (it scrolls into the view when you click on it)
- iOS should show numeric keypad instead of full keyboard
=> fix: Auto scrolling ticket input to view, iOS numeric keypad

src/views/Pools/components/BountyModal.tsx, src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
- Use static gas values for harvest, deposit & withdraw auto pool calls.
- Updated calls to be within try/catch: transaction error handling as-is in a lot of the app doesn't work as intended (to see for yourself - cancel a transaction and notice none of the fail state functions fire), as per: https://pancakeswap.slack.com/archives/C01GL551EF6/p1625483421174300
=> fix(auto-pools): Use static gas values & wrap calls in try/catch to fix error handling

src/state/hooks.ts, src/state/lottery/fetchUnclaimedUserRewards.ts, src/state/lottery/getLotteriesData.ts, src/state/lottery/getUserLotteryData.ts, src/state/lottery/helpers.ts, src/state/lottery/index.ts, src/state/types.ts, src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx, src/views/Lottery/components/ClaimPrizesModal/ClaimPrizesInner.tsx, src/views/Lottery/components/ClaimPrizesModal/index.tsx, src/views/Lottery/components/PreviousRoundCard/Footer.tsx, src/views/Lottery/components/ViewTicketsModal/PreviousRoundTicketsInner.tsx, src/views/Lottery/helpers.tsx, src/views/Lottery/hooks/useGetUnclaimedRewards.ts, src/views/Lottery/hooks/useStatusTransitions.tsx
Preview https://new-node-calls.netlify.app/lottery
**What does it do**
- Fundamentally change two of the base data-fetching queries: `getUserLotteryData` & `getLotteriesData`
- Previously, for all non-current round data, we were reliant on the subgraph. This was problematic particularly when rounds ended, as the subgraph would drift out of sync and return stale data.
- These two queries **now make node calls as well as subgraph calls, for all essential user & public lottery data for the past 4 rounds.**
- The two data sources are blended - in all cases, essential data is being handled by the nodes, and some supplementary UI data comes from the subgraph
- For rounds older than 4 rounds ago - the subgraph is used as normal.
- This PR includes a fallback for where there is no subgraph data …
=> feat(lottery-v2): Use node calls to populate recent User and Public Lottery data

src/state/predictions/helpers.ts
This fixes missing rounds for users with 1000+ bets.
=> fix(predictions): Add sorting to bet history filter

src/views/Farms/components/DepositModal.tsx, src/views/Farms/components/WithdrawModal.tsx
To review: 
https://deploy-preview-1733--pancakeswap-dev.netlify.app/
1. Go to farms
2. Click stake or unstake button
3. Check confirm button when pending transaction 
4. Other places (pools) are using text 'Confirming', so it should be unified.
=> feat: Unify confirm button text when pending transaction

src/views/Home/components/FarmStakingCard.tsx
To Review:
https://deploy-preview-1731--pancakeswap-dev.netlify.app/
To Reproduce:
1. Click harvest all on homepage farm staking card
2. After successful transaction no indicator is seen
=> feat: Add success toast to farm staking card on home page

src/components/Menu/SubNav.tsx
Bug location: https://pancakeswap.finance/liquidity
**Button menu doesn't toggle to the correct item.**
=> fix: Toggle correctly for path /liquidity

src/components/SearchModal/CurrencySearchModal.tsx, src/config/constants/swapWarningTokens.ts, src/config/constants/tokens.ts, src/config/localization/translations.json, src/views/Swap/components/ImportTokenWarningModal.tsx, src/views/Swap/components/SwapWarningModal/Acknowledgement.tsx, src/views/Swap/components/SwapWarningModal/BondlyWarning.tsx, src/views/Swap/components/SwapWarningModal/SafemoonWarning.tsx, src/views/Swap/components/SwapWarningModal/index.tsx, src/views/Swap/components/SwapWarningModal/types.ts, src/views/Swap/index.tsx
Preview: https://exchange-warning-modals.netlify.app/swap
To test, select as either swap SAFEMOON (`0x8076c74c5e3f5852037f31ff0093eeb8c8add8d3`), or BONDLY (`0x96058f8C3e16576D9BD68766f3836d9A33158f89 `)
Steps to add future warnings:
1. Add new entry to `swapWarningTokens` with `symbol` and an `address` object. The key should be similar to the token symbol, lowercased (although honestly this can be anything - it's just used as a key to access the object in step 3). 
```js
safewat: {
symbol: 'WAT',
address: {
56: '0x...',
97: '',
},
},
```
2. Create a warning component which will be passed into the body of the modal. These are super basic and could maybe even be spun up by non-FE engineers, i.e.
```js
const SafeWatWarning: React.FC<DefaultWarningProps> = () => {
return (
<>
<Text …
```
=> feat(swap-warning-modals): Add warning modals for specific tokens when swapping

src/components/Loading.tsx, src/views/Farms/Farms.tsx, src/views/Pools/index.tsx
To review:
https://deploy-preview-1752--pancakeswap-dev.netlify.app/
To reproduce:
1. Connect your account
2. Go to farms or pools
3. Select staked only fast
4. See there is no loading indicator
=> feat: Add loading indicator for staked only when user data is loaded

src/views/Pools/index.tsx
To review: 
https://deploy-preview-1765--pancakeswap-dev.netlify.app/
To reproduce: 
1. Go to pools
2. Change view to card
3. Go to farms
4. See view changed to cards
=> fix: Changing the farm view setting affects view of pool or vice versa

src/components/Balance.tsx
Current logic creates redundant spans
To review:
https://deploy-preview-1773--pancakeswap-dev.netlify.app/
=> refactor: Use Countup prefix and suffix props in Balance component

src/views/Lottery/components/AllHistoryCard/index.tsx
Problem
- `currentLotteryId` hasn't been fetched at the point that this component is loaded, which is causing the app to crash on the lottery page.
- This has been flagged by a recent change whereby the `AllHistoryCard` component is loaded first, rather than `YourHistoryCard`
Fix
- Create an effect to conditionally handle all logic that relies on `currentLotteryId` being truthy
=> fix(all-lottery-history): Fix crash on AllHistoryCard loading

src/views/Farms/components/FarmCard/StakeAction.tsx, src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
Solved by rounding the staked balance to 10 decimal places when it's below `0.0000001`
=> fix(farms): Round farm staking balances below 0.0000001 to 10dp

src/config/constants/farms.ts, src/config/constants/pools.ts
The Syrup Pool:
Stake CAKE tokens to earn WIN tokens!
Total Tokens: 3,137,000,000 WIN
Distribution duration: 60 days
Start block: 9569400 (approx. 9am UTC on July 29th)
Finish block: 11297400 (approx. 9am UTC on September 30th)
Token rewards per block: 1,815.39 WIN
=> feat(pool): WIN

src/config/constants/farms.ts, src/config/constants/pools.ts
The Syrup Pool:
Stake CAKE tokens to earn BTT tokens!
Total Tokens: 454,500,000 BTT
Distribution duration: 60 days
Start block: 9677600 (approx. 5am UTC on August 2nd)
Finish block: 11405600 (approx. 5am UTC on October 3rd)
Token rewards per block: 263 BTT
=> feat(farm/pool): BTT

src/components/Menu/UserMenu/index.tsx
- Users without nft profile pictures will now experience an app crash as it attempts to access `.nft.images` which is undefined
- Add `profile.nft` to the avatarSrc ternary
=> fix(user-menu): Catch for when user doesn't have an nft profile pic

src/state/user/actions.ts, src/state/user/hooks/index.tsx, src/state/user/reducer.ts, src/views/Farms/Farms.tsx
To review: 
https://deploy-preview-1777--pancakeswap-dev.netlify.app/
To reproduce: 
1. Go to farms
2. Toggle staked only
3. Refresh the page
4. See the new setting is not persistent
This fix also keeps the feature of showing staked only farms when finished farms selected (until user toggles a new setting)
=> fix: Staked only setting persistent storage missing in farms

src/views/Lottery/components/TicketNumber.tsx
**Environment:**
Device and OS: Any
Browser: Any
Reproducibility rate: 100%
**Steps to reproduce:**
1. Open view your tickets modal on the lottery page
2. Check console in dev tool
By calling `_uniqueId()` we will get rid of the same key problem. I think the devs forgot to call it.
=> fix: Should call _uniqueId in view ticket modal lottery

src/state/lottery/getLotteriesData.ts, src/state/lottery/getUserLotteryData.ts
- Add `skip`, `first` & `where` to `getGraphLotteryUser` func
- Add `skip` & `first` to `getGraphLotteries` func
- Required for lottery NFT & lottery subgraph pagination
=> chore(lottery): Add first and skip query params to lottery subgraph responses

src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx, src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx, src/views/Pools/components/PoolsTable/ActionPanel/styles.ts
To review:
https://deploy-preview-1892--pancakeswap-dev.netlify.app/
To reproduce:
Go to pools table
Click details of a pool except auto cake
Check stake and harvest action components excessive height
=> fix: (pools table) Manual pools action panel components have excessive height

src/views/Home/components/MetricsSection/StatCardContent.tsx
To review:
https://deploy-preview-1803--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to homepage with mobile Safari
2. Check the numbers in Used by millions. Trusted with billions.
3. See that compact option could not be applied there
It is not supported in mobile safari until 14.7
https://caniuse.com/?search=numberformat%20notation
Before:
After:
=> fix: Numberformat compact not shown properly in mobile safari (below 14.7)

src/components/Menu/GlobalSettings/GasSettings.tsx, src/components/Menu/GlobalSettings/TransactionSettings.tsx, src/components/QuestionHelper/index.tsx
To review: 
https://deploy-preview-1916--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to website in mobile
2. Open global settings
3. Check tooltips visibility
=> fix: Global settings tooltips not visible correctly in mobile

src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx, src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx, src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx, src/views/Pools/components/PoolsTable/Cells/AutoEarningsCell.tsx, src/views/Pools/components/PoolsTable/PoolRow.tsx
To review: 
https://deploy-preview-1913--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to pools table
3. You should not see any difference
=> refactor: Separate auto pool row components to not make redundant calculations in manual pool rows

src/state/lottery/getLotteriesData.ts, src/state/lottery/helpers.ts, src/state/lottery/hooks.ts, src/state/lottery/index.ts, src/views/Lottery/components/AllHistoryCard/index.tsx, src/views/Lottery/components/NextDrawCard.tsx, src/views/Lottery/components/PreviousRoundCard/Body.tsx, src/views/Lottery/components/PreviousRoundCard/Footer.tsx, src/views/Lottery/components/PreviousRoundCard/FooterExpanded.tsx, src/views/Lottery/components/RewardBrackets.tsx, src/views/Lottery/components/YourHistoryCard/index.tsx
Our lottery subgraph request returns the most recent 100 lotteries. Soon we'll have over 100 past rounds, which will cause issues in history when viewing rounds >100 ago
- Renamed variables throughout lottery so it's clear when it's node data vs graph data being used
- Add fetch for when graph data isn't found for a selected round
=> feat(lottery-history): Fetch additional data from graph when lottery history is missing rounds

src/views/Home/components/Banners/FarmAuctionsBanner.tsx
To review:
https://deploy-preview-1923--pancakeswap-dev.netlify.app/
To reproduce: 
1. Go to homepage in mobile
2. See farm auction text last part overlaps with background image and it is hard to read
Before:
After:
It also fixes the formatting issue when browser width is around 576px (sm breakpoint)
=> fix: Farm auction banner text not visible overlaps with background image

src/config/localization/translations.json, src/views/Home/components/UserBanner/EarningsText.tsx, src/views/Home/components/UserBanner/HarvestCard.tsx
When earnings amount is being loaded but user staked farms data available, depending on the time that query returns, user will see NaN on the screen. (usually it is couple of milliseconds but it can be noticed)
To review: 
https://deploy-preview-1937--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to homepage
2. Restart the page
3. Check harvest card NaN is visible couple of seconds or half a second
=> fix: (harvestcard) NaN shown in harvest card when earnings being loaded

src/views/Lottery/components/HowToPlay.tsx
To review:
https://deploy-preview-1933--pancakeswap-dev.netlify.app/
To reproduce: 
2. Go to prize funds section
3. Change language to french
4. Check pool allocation table
Before:
After:
=> fix: (lottery) How To Play Pool Allocation not shown properly in other languages

src/views/Lottery/components/AllHistoryCard/RoundSwitcher.tsx
To review:
https://deploy-preview-1932--pancakeswap-dev.netlify.app/
To reproduce:
2. Go to finished rounds section
3. Try to enter non-numeric values 
In mobile
1. Check which type of keyboard shown when typing input
2. It should show keyboard with number only
=> fix: Round switcher input accepts non-numeric values

src/components/Menu/GlobalSettings/SettingsModal.tsx
To review:
https://deploy-preview-1921--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to global settings in mobile (iphone8 size phones and especially mobile safari)
2. Try to scroll down
=> fix: Scrolling global settings in mobile 

src/views/Pools/components/PoolsTable/Cells/AutoAprCell.tsx, src/views/Pools/components/PoolsTable/PoolRow.tsx
Currently each pool row has to deal with auto cake vault calculations
To review:
https://deploy-preview-1925--pancakeswap-dev.netlify.app/
=> refactor: Separate pools row manual apr cell from auto one to not make redundant calculations

src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx, src/views/Pools/components/PoolsTable/PoolRow.tsx
To review:
To reproduce:
1. Open pools in larger screen (width> 1080px)
2. See columns are missing
=> fix: (pools) Pools table layout in larger screens

src/components/SearchInput/SearchInput.tsx
To review:
https://deploy-preview-1966--pancakeswap-dev.netlify.app/
1. Go to pools or farms
2. Check search input
3. There should be no difference
=> refactor: Remove unused toggle prop on search input

src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
To review: 
To reproduce:
1. Go to lottery 
2. Click buy ticket without connect your account
3. See skeletons and warnings when entering amount
Before:
After:
=> fix: (lottery) Ticket modal shows skeletons for balance and warnings when no account is connected

src/hooks/useAuth.ts
To review: 
To reproduce: 
1. Go to webpage
3. Disconnect from dropdown menu
4. Refresh page
5. See eager connection happens
=> fix: (auth) Eager connection happens even after successful logout

src/state/lottery/getUserLotteryData.ts, src/state/lottery/index.ts, src/views/Lottery/components/YourHistoryCard/FinishedRoundTable.tsx, src/views/Lottery/components/YourHistoryCard/index.tsx, src/views/Lottery/hooks/useShowMoreUserRounds.ts, src/views/Lottery/index.tsx
- Conditionally render a 'See More' button within Finished Rounds > Your History when the max number of lotteries returned by the subgraph is equal to the number of lotteries being displayed.
- Currently will only appear for users who have entered 100+ rounds
- On click, an additional 100 are fetched. 'See More' will continue to display while the total number of lottery rounds shown matches the max number of lotteries requested.
- As the `numUserRoundsRequested` needs to be persisted outwith the component - I made a small hook to handle the logic and keep the `lottery/index.tsx` file clean.
=> feat(lottery): Add 'See More' button & request additional lotteries when user has hit subgraph lottery limit

src/config/localization/translations.json, src/state/lottery/getLotteriesData.ts, src/state/lottery/getUserLotteryData.ts, src/views/Lottery/components/PreviousRoundCard/FooterExpanded.tsx, src/views/Lottery/components/YourHistoryCard/index.tsx
Preview https://adoring-golick-c9fee3.netlify.app/lottery
- Fix crash when expanding details of a past round without `totalUsers` data
- Improve logic appending subgraph data to node data for user-entered and public lotteries
- Add notice for subgraph delay to user history
=> fix(lottery): Fix lottery page crash

src/config/localization/translations.json, src/views/Lottery/components/YourHistoryCard/index.tsx
Only merge when the lottery subgraph is stable.
- Remove 'due to a delay in the BSC Subgraph, lotteries after round 108 may temporarily show incomplete data.' notice
=> chore(lottery): Restore original lottery history user notice

src/state/predictions/hooks.ts, src/state/predictions/index.ts, src/views/Predictions/History.tsx, src/views/Predictions/components/CollectRoundWinningsModal.tsx
- Temporarily disabled fetching history from the subgraph
- Fixed issue when opening claim modal before opening history
=> fix(predictions): History not loaded on collect winnings

src/views/TradingCompetition/index.tsx
Contract cannot be called without an account. It gives an error. 
`Uncaught (in promise) Error: unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.4.1)`
It has to be set CLAIM by default for now until there has a new campaign
Fixes #2016 
To review: 
https://deploy-preview-2020--pancakeswap-dev.netlify.app/
=> fix: Trade battle shows live without account connected

src/views/Farms/components/FarmCard/CardHeading.tsx
To review:
https://deploy-preview-2047--pancakeswap-dev.netlify.app/
To reproduce:
1. Go farms card
2. Check empty purple multiplier tag when loading
Before: 
After:
=> fix: (farms) Empty multiplier tag in farms card when loading

src/components/Menu/config.ts
To review:
https://deploy-preview-2048--pancakeswap-dev.netlify.app/
To reproduce:
1. Click trade in menu
2. Click Liquidity
3. See menu item doesn't indicate the active page.
=> fix: (menu) Menu item active highlight for liquidity not working

src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx
To review:
https://deploy-preview-2049--pancakeswap-dev.netlify.app/
To reproduce: 
1. Go to pools card
2. Go to auto vault card
3. Click details
4. See performance fee shows 0 when data loading
=> fix: Pools card performance fee shows 0 when loading

src/config/localization/translations.json
can be merged after https://github.com/pancakeswap/pancake-toolkit/pull/257 merged to toolkit and bumped version up in frontend
To reproduce: 
1. Go to homepage without connecting your account
3. Click connect wallet
4. See the modal is not translated
=> feat: Adapt wallet modal hook usage for translation support

src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
It contains duplicate catch statements
To review
https://deploy-preview-2061--pancakeswap-dev.netlify.app/
Go to pools
Try unstake/stake on any pool that you staked
There should be no difference
=> refactor: Stake modal confirm logic

src/components/Layout/Page.tsx, src/views/Home/index.tsx
Fixes #2066 
To review: 
https://deploy-preview-2068--pancakeswap-dev.netlify.app/
=> fix: Page title stays the same when switch to Home page from Menu

src/config/localization/translations.json
It is removed by mistake in previous commits, cannot be detected with tests since that component is in toolkit :(
=> fix: Translation key missing for connect modal component

src/components/Menu/UserMenu/WalletInfo.tsx
To review: 
To reproduce: 
1. Connect your account
2. Go to your wallet from user menu top right 
3. See cake and bnb balance shows 0 for a short time
4. It can also be reproducible if you toggle between transactions and wallet on that screen
=> fix: Wallet info shows 0 balance for cake and bnb when fetching

src/views/Lottery/components/HowToPlay.tsx
Somehow safari mobile doesn't take the height proportions correctly that we have to manually define it
To review:
To reproduce:
1. Go to lottery with iOS Safari 
2. Check bottom
3. See bunny logo height is not correct and image looks stretched
=> fix: Lottery bunny resize at footer in safari mobile

src/config/constants/types.ts, src/views/FarmAuction/components/AuctionDetailsCard/AuctionFooter.tsx, src/views/FarmAuction/components/AuctionDetailsCard/AuctionSchedule.tsx, src/views/FarmAuction/components/AuctionDetailsCard/index.tsx, src/views/FarmAuction/components/CongratulationsCard.tsx, src/views/FarmAuction/helpers.tsx
We ended up launching farms ASAP instead of planned 12h after auction end, so farm schedule is not needed.
=> fix: Remove farm schedule from farm auctions

src/__tests__/utils/index.test.ts, src/components/SearchModal/ImportToken.tsx, src/hooks/useSwapCallback.ts, src/utils/index.ts, src/views/Info/Tokens/TokenPage.tsx, src/views/Info/components/InfoTables/TransactionsTable.tsx, src/views/Swap/components/SwapModalHeader.tsx
Remove duplicated function to shorten hex-string. One being more widely used (`truncateHash`), I choose to keep this one. The other one (`shortenAddress`) seems to have been added along .info migration. Both functions do have tests.
=> chore: Remove duplicated helper function

src/views/Predictions/components/Label.tsx, src/views/Predictions/components/Menu.tsx
To review: 
https://deploy-preview-2139--pancakeswap-dev.netlify.app/
1. Go to prediction in mobile
2. See leaderboard button is missing above the prediction cards
=> fix: Prediction Leaderboard button missing in mobile

src/views/AddLiquidity/index.tsx
To review:
To reproduce:
1. Go to add liquidity
2. Select token from first input panel
3. See undefined in browser address bar
=> fix: Add liquidity shows undefined in address bar when selecting token

src/views/Predictions/components/Menu.tsx
To review:
https://deploy-preview-2149--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to prediction in mobile (iphone 8 size)
2. See button are moving in top menu above cards when timer is counting down
=> fix: (prediction) Buttons moving when larger digits in timer on menu in prediction mobile

src/views/AddLiquidity/index.tsx
To review:
https://deploy-preview-2148--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to add liquidity page
2. Select token for first input or second or both
3. Enter input amount 
4. Change the page
5. Enter again
6. See token amount shown without any token selected
=> fix: (liquidity) Old token amount input shown when re-open the add liquidity page

src/views/FarmAuction/components/AuctionCakeBurn.tsx
To review:
https://deploy-preview-2133--pancakeswap-dev.netlify.app/
To reproduce: 
1. Go to https://pancakeswap.finance/farms/auction in mobile phone (iphone 8 size)
2. Go to cake burned so far section
3. Change language to german
4. See Burned text is too long that cause scroll-x bar to appear
=> fix: (auction) Auction cake burned font size too large for different languages in mobile

src/components/CurrencyInputPanel/index.tsx, src/config/localization/translations.json
To review:
https://deploy-preview-2160--pancakeswap-dev.netlify.app/
To reproduce: 
1. Go to swap with your account
2. Select token
3. See balance inside the input panel shows "-" a few time without loading indicator
=> fix: Balance loading indicator missing when user selects token in swap input

src/App.tsx, src/state/nftMarket/hooks.ts, src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts, src/views/Nft/market/Collectibles/index.tsx, src/views/Nft/market/Home/index.tsx, src/views/Nft/market/index.tsx
- Adds a loading state so we can fetch the collections before rendering. This will ensure that it is available on all sub-routes
- Moved routes into the `views/Nft/market`
=> refactor(nft): Move routes inside index

src/state/collectibles/hooks.ts, src/state/collectibles/index.ts, src/state/profile/helpers.ts, src/state/profile/hooks.ts, src/state/profile/index.tsx, src/views/Collectibles/components/NftCard/LotteryNftCard.tsx, src/views/Collectibles/components/NftList.tsx
Fixes broken out of nft-market PR as they can go directly into master https://github.com/pancakeswap/pancake-frontend/pull/2154
A recurring 'unknown account' error fires in some pages in the app
```
Error: unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.4.1)
```
The impact is sometimes limited to a console error (farm auctions), but on occasion it causes an app crash.
=> fix(unknown-account): Add account checks to Profile/Collectibles calls that require accounts 

cypress/integration/predictions/predictions.test.ts, src/utils/getRpcUrl.ts
`+` fix cypress test if prediction is paused
=> chore: Bring back custom node

src/config/localization/translations.json, src/state/burn/hooks.ts, src/views/RemoveLiquidity/index.tsx, src/views/Swap/index.tsx
To review:
To reproduce:
1. Go to remove liquidity page (e.g https://pancakeswap.finance/remove/BNB/0xE0e514c71282b6f4e823703a39374Cf58dc3eA4f)
2. See To receive... header and button translations missing
3. Swap page button translation for price impact is missing too
=> fix: Missing translations in remove liquidity and swap

src/state/nftMarket/helpers.ts, src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts
- Add `getNftMetadataFromTokenIdApi` fetch for specific token metadata
- Rename `NftToken` subgraph response type -> `NftTokenSg`
- Add optional props `mp4`, `webm`, `gif` to the `Image` type
- Add optional prop `attributes` to the 'NFT' type to reflect the api response data, eg
https://nft.pancakeswap.com/api/v1/collections/0x60935F36e4631F73f0f407e68642144e07aC7f5E/tokens/60
```json
"id": "123",
"tokenId": "60",
"name": "Pancake Bunnies #60 - Twinkle",
"description": "Three guesses what's put that twinkle in those eyes! (Hint: it's CAKE)",
"image": {
"original": "ipfs://Qme6aiY9GLvaT6v5KY42VqLEUNNsNurYzVtSTr16HEAMmU/blur_twinkle.png",
"thumbnail": "ipfs://Qme6aiY9GLvaT6v5KY42VqLEUNNsNurYzVtSTr16HEAMmU/blur_twinkle.png",
"mp4": null,
"webm": null,
"gif": null
},
"attributes": [
{ …
```
=> feat(nft-metadata-api): Add nftMetadata fetch and update types

src/components/Menu/GlobalSettings/SettingsModal.tsx
To review: 
https://deploy-preview-2204--pancakeswap-dev.netlify.app/
To reproduce: 
Issue mainly seen in latest develop
1. Go to global settings modal in mobile (iphone 8 size)
2. See it is not scrollable to the bottom
=> fix: Global Settings modal scroll in mobile

src/config/localization/translations.json, src/state/mint/hooks.ts
To review:
https://deploy-preview-2200--pancakeswap-dev.netlify.app/
To reproduce: 
1. Go to trade>liquidity
2. Click add liquidity
3. Change language
4. Do some invalid operations like adding insufficient amount or selecting invalid pair.
5. See button translation is not working
=> fix: (liquidity) Missing translations in add liquidity

src/state/nftMarket/helpers.ts, src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts, src/views/Nft/market/Profile/index.tsx
- Remove data transformation for NFT collection id (previously `NFT.collectionAddress`, now `NFT.collection.id`)
- Add `tokenId` to NFT type - the 'id' returned by the API isn't the tokenId
- Add fetch to return multiple NFTs' metadata
=> chore(nft-market-sg): Remove data transformation of NFT entity's collection address

src/state/nftMarket/helpers.ts
Remove duplicate API helpers, `getNftsFromDifferentCollectionsApi` & `getNftApi` do the same things
=> chore(nft-market-helpers): Remove duplicate helpers

src/views/Pools/components/HelpButton.tsx
To review:
https://deploy-preview-2227--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to pools
2. See Help button in the header can be clicked beyond its size to the left
=> fix: (pools) Help button can be clicked beyond its size

src/components/Menu/GlobalSettings/index.tsx
It can be more noticeable in mobile. 
To review:
https://deploy-preview-2221--pancakeswap-dev.netlify.app/
Before:
After:
=> fix: Global settings icon smaller than language icon

src/views/Pools/components/HelpButton.tsx
My bad for removing this, that creates issues on iphone 5 size devices since xs min width is 370px and iphone 5 is 320px
To review: 
To reproduce: 
1. Check latest develop
2. Go to pools in iphone 5 size
3. Help should not show the text
=> fix: Put back xs check for help button for smaller devices

src/state/nftMarket/helpers.ts, src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts, src/views/Nft/market/Profile/components/UserNfts.tsx
- Return `NFT` from fetchUserNfts fetch (instead of `NftTokenSg`) and attach the `NftTokenSg` to the `NFT.tokens` object instead. So for each nft a user owns, an object like this is stored to `nftMarket.data.users.nfts` state:
=> feat(user-nfts): Add metadata fetch to fetchUserNfts reducer

src/hooks/useAuth.ts
To review:
https://deploy-preview-2245--pancakeswap-dev.netlify.app/
To reproduce:
1. Do some transactions
2. Logout
3. Login with another account
4. Go to recent transactions
5. See transactions from previous account still visible
=> fix: Recents transactions can be seen from another account on the same device

src/components/App/Transactions/TransactionsModal.tsx
To review:
https://deploy-preview-2247--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to https://pancakeswap.finance/swap without connecting your wallet
2. Click recent transaction icon
3. See it shows empty modal
4. Instead it should have connect wallet button
=> fix: Recents transactions modal shows empty when no wallet connected

src/components/App/AppHeader.tsx
To review:
To reproduce: 
1. Go to https://pancakeswap.finance/add in mobile (iphone 8 size)
2. Click tooltip question marker
3. See tooltip is off the screen
=> fix: Wrong Tooltip placement in add liquidity in mobile

src/components/Menu/Footer.tsx, src/config/localization/translations.json
To review:
https://deploy-preview-2261--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to swap/liquidity
3. See V1(old) button in bottom left is not translated
=> fix: Add missing translation in footer of swap/liquidity pages

src/views/Profile/ProfileCreation/Mint.tsx
To review:
https://deploy-preview-2265--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to make a profile with an account that doesn't have profile https://pancakeswap.finance/profile
2. Complete first step
3. See We couldn’t find any Pancake Collectibles in your wallet. in the next step
=> fix: Make a profile doesn't show collectible after minting in set profile picture

src/views/Predictions/components/History/PnlTab/PnlTab.tsx
In the PnL Tab of the history of predictions the USD value of the best round is displayed incorrectly. Instead of showing the USD value of the gains is showing the USD value of the multiplier. This PR fixes the problem.
=> Fix: Display the correct USD amount for the best round in PnL tab of the Prediction's History

src/views/Home/hooks/useGetTopFarmsByApr.tsx
To review:
https://deploy-preview-2283--pancakeswap-dev.netlify.app/
To reproduce cake pool error:
1. Go to main page
2. Check top farms by apr
3. Then go to farms (which fetches the cake pool public data)
4. Go back to main page and check top farms 
To reproduce finished farms error:
1. Go to main page
2. Check top farms by apr
3. See finished farms in the list
=> fix: Top farms by apr shows finished farms and cake pool

src/state/nftMarket/hooks.ts, src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts, src/views/Nft/market/components/CollectibleCard/CardBody.tsx
Proof of concept for how this could be stored in redux and accessed in components (for PBs).
It works, but it has two dependencies that won't scale well. 
1. It relies on us retrieving and storing an array of all token IDs for each NFT. As an example - Sleepy's tokens array will have 98k ids on mainnet.
2. It relies on sorting the market data for _all_ tokens of an NFT type. When thousands of tokens are on sale - we would need to gather this data over many requests.
And another thing:
- The `useGetLowestPricedPB` hook will only work for PBs because it uses the PB attributes to access the nft in the `collections` redux.
Success:
But not scalable:
=> feat(nft-market): Move lowestPriceToken logic into redux

src/views/Nft/market/Profile/hooks/useFetchUserNfts.tsx
Don't fetch userNfts with an empty collections state
=> fix(nft-market-fetch): Add check for collections not being empty object

src/hooks/useScrollOnRouteChange.ts, src/views/Home/components/Hero.tsx, src/views/Home/components/SalesSection/index.tsx, src/views/Home/components/WinSection/LotteryCardContent.tsx, src/views/Home/components/WinSection/PredictionCardContent.tsx
To review:
https://deploy-preview-2314--pancakeswap-dev.netlify.app/
To reproduce: 
1. Click trade now or play buttons on homepage and see the website refreshes completely
2. In firefox we have to give small timeout in order to scroll to work
=> fix: Links on homepage refreshes the website and firefox scroll to top

src/views/Nft/market/Profile/components/UserNfts.tsx
If certain bunny id was never on sale seems like marketData can be undefined here and crash the page
=> fix: Guard for possible undefined marketData

src/components/Menu/GlobalSettings/SettingsModal.tsx
Fix from toolkit is merged so we can remove that wrapper
To review: 
https://deploy-preview-2323--pancakeswap-dev.netlify.app/
=> refactor: Remove pancake toggle redundant wrapper in global settings

src/__tests__/utils/utils.test.ts, src/components/Menu/utils.ts
Previous logic uses `.find()` & return the first match for `pathname.includes(menuItem.href)` which means that if you have an array of menuItems like `/nfts`, `/nfts/collection/0x...`, and a pathname  `/nfts/collection/0x...` - it returns `/nfts` as the active item.
This fixes it. Interested in what @0xCorgi thinks though. It doesn't feel particularly elegant.
=> chore(menu-items): Improve getActivesubMenuItem specificity

src/__tests__/utils/utils.test.ts, src/components/Menu/utils.ts
This fix also contains https://github.com/pancakeswap/pancake-frontend/pull/2355 fixes by @ChefHutch to nftmarket branch.
Fixes #2214 as well
To review:
https://deploy-preview-2354--pancakeswap-dev.netlify.app/
1. Go to info https://pancakeswap.finance/info
2. Click pools on its own tab bar
3. See farms pools(which is syrup pools) tab bar shown above that
=> fix: (info): Wrong tab bar in info

src/components/App/Transactions/TransactionsModal.tsx, src/components/Menu/UserMenu/WalletTransactions.tsx
To review:
https://deploy-preview-2363--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to wallet modal -> transaction
2. See transactions
3. Go to liquidity or swap
4. Click transactions icon
5. See the discrepancy between this modal and the wallet one
=> fix: Recent transaction modals discrepancy in transaction lists

src/views/Info/components/TopTokenMovers/index.tsx
Interval inside top token movers is never cleared after detaching. I also added a feature to scroll back to first when it reaches to last. 
To review:
https://deploy-preview-2391--pancakeswap-dev.netlify.app/
=> fix: (info): Interval leakage in top token movers

src/components/HashRoute.tsx, src/hooks/useScrollOnRouteChange.ts, src/views/Nft/market/Collection/Header.tsx, src/views/Nft/market/Collection/index.tsx
A proposition to use `#` for same page navigation.
It relies on a new component `HashRoute` that just wrap `Route` from react-router and check a `hash` prop to render its component.
This would allow us to keep the existing behavior while landing on a page and ignore it afterward while using internal tabs navigation.
=> fix: Scroll top behaviour

src/config/localization/translations.json, src/state/nftMarket/helpers.ts, src/state/nftMarket/hooks.ts, src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts, src/views/Nft/market/Collection/IndividualNFTPage/ForSaleTableCard/index.tsx, src/views/Nft/market/Collection/IndividualNFTPage/index.tsx
- Allow users to scroll pages of NFTs (load more on click)
- Every 10 seconds check for new NFTs with the bunny id that you're looking at
- Every 10 seconds update information about displayed NFTs (in case they change price or get bought)
=> fix: Pagination and auto-fetching of NFTs

src/views/Nft/market/components/MarketPageHeader.tsx
=> fix: Dark theme header on nft market

src/config/constants/meta.ts
To review:
https://deploy-preview-2427--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to info
2. Go to tokens
3. Check page title
=> fix: (info): Wrong page title of info tokens

src/views/Home/components/UserBanner/HarvestCard.tsx
To review:
https://deploy-preview-2430--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to main page
2. Connect account with no active pools or farms harvested
3. See Start earning button on harvest card
4. Clicking it refreshing the page completely
=> refactor: (Harvest Card): Use router link to not refresh page

src/views/Nft/market/Collection/IndividualNFTPage/ManageCard.tsx
To review:
To reproduce:
1. Go to https://pancakeswap.finance/nfts/collections/0xdf7952b35f24acf7fc0487d01c8d5690a60dba07/5 without connecting your account
2. Go to manage yours section on left side
3. See it shows skeleton
=> fix: (nft): Manage yours section shows skeleton when no account connected

src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
Use WBNB as the default payment currency to buy an NFT if:
- user doesn't have enough BNB
- user has enough WBNB
=> feat(market): Use WBNB as prefered currency if useful

src/config/index.ts, src/config/localization/translations.json, src/state/nftMarket/helpers.ts, src/state/nftMarket/hooks.ts, src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts, src/views/Nft/market/Collection/IndividualNFTPage/ForSaleTableCard/CountdownCircle.tsx, src/views/Nft/market/Collection/IndividualNFTPage/ForSaleTableCard/UpdateIndicator.tsx, src/views/Nft/market/Collection/IndividualNFTPage/ForSaleTableCard/index.tsx, src/views/Nft/market/Collection/IndividualNFTPage/MoreFromThisCollection.tsx, src/views/Nft/market/Collection/IndividualNFTPage/index.tsx
- Adds update for existing NFTs in the state every 10 seconds (in case they get sold or price gets modified)
- Adds update indicator to the table
- Removes pre-fetching random pancake bunny NFTs into state as they are not used anywhere.
=> feat: Auto update refinement

src/views/Nft/market/components/BuySellModals/BuyModal/ReviewStage.tsx
To review:
https://deploy-preview-2449--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to http://pancakeswap.finance/nfts/collections/0xdf7952b35f24acf7fc0487d01c8d5690a60dba07/10
2. Click Buy button without connecting your account
3. See skeleton in bnb in wallet
=> fix: (nft): Review stage shows skeleton in amount wallet when no account connected

src/state/nftMarket/helpers.ts, src/state/nftMarket/reducer.ts, src/views/Nft/market/Collection/IndividualNFTPage/ForSaleTableCard/index.tsx, src/views/Nft/market/Collection/Items/CollectionNfts.tsx, src/views/Nft/market/Collection/Items/PancakeBunniesCollectionNfts.tsx, src/views/Nft/market/Collection/Items/index.tsx, src/views/Nft/market/Profile/components/ActivityHistory/index.tsx, src/views/Nft/market/components/PaginationButtons.tsx
- Split `CollectionNfts` into two as they have very distinctive logic - `PancakeBunniesCollectionNfts` & `CollectionNfts`
- Paginate API & NFT requests for `fetchNftsFromCollections`
- Paginate FE `CollectionNfts`
Compatible with existing collection setup in prod
=> feat(nft-collections): Paginate collections frontend and requests

src/__tests__/config/translations.test.ts
Instead of failing at the first unknown key occurence, take all the unknown keys and then throw error with list
=> feat: (test): Add list of unknown translation keys instead of one per  file

src/views/Info/components/InfoSearch/index.tsx
To review:
To reproduce:
2. Click search pools or tokens input
3. Then click another page from menu without closing the dropdown 
4. See click listener stays active by getEventListeners(document) on console
=> fix: (info): Click listener stays active after unmount

src/views/Nft/market/Collection/Items/FilteredCollectionNfts.tsx
To review:
https://deploy-preview-2533--pancakeswap-dev.netlify.app/
To reproduce:
1. Go squad nft collections
2. Select all and select trait filter
3. Select order by token id
4. See order is wrong that is first shows non listed items then shows tradable items
=> fix: (nft): Sorting by token id with trait filter

src/utils/achievements.ts, src/views/Nft/market/Profile/components/Achievements/AchievementRow/index.tsx
To review:
https://deploy-preview-2517--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to profile page
2. Connect an account that has claimable achievements
3. See the error on console when fetching claimable achievements
Uncaught (in promise) Error: invalid address (argument="address", value=5, code=INVALID_ARGUMENT, version=address/5.4.0) (argument=null, value=5, code=INVALID_ARGUMENT, version=abi/5.4.0)
=> fix: (profile): Claimable achievements throws error when fetching

src/views/Nft/market/Collection/TopBar.tsx
To review:
https://deploy-preview-2546--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to https://pancakeswap.finance/nfts/collections/0x0a8901b0E25DEb55A87524f0cC164E9644020EBA
2. Click All Collections top right
3. See it points to Overview instead of Collection list
=> fix: (collections): All collections link points to overview instead of collection list

src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/index.tsx
To review:
https://deploy-preview-2548--pancakeswap-dev.netlify.app/
To reproduce:
1. Go to an individual nft token page that owned by you
2. Then go to another token page (which the token is not owned by) from more from collection component
3. See page crashes
Reason is the component is rerendered with updated params but not remounted when we change the route params.  We have to clear the state.
=> fix: (nfts): Page crash on individual nft page after visiting an nft page that owned by user

src/config/localization/translations.json, src/views/Nft/market/components/BuySellModals/SellModal/TransferStage.tsx
Fix  typo in the text in NFT transfer modal:
[typo] This action will send your wallet to the address you have indicated above.
[fixed] This action will send your NFT to the address you have indicated above.
=> chore: Fix typo at NFT marketplace

src/state/profile/index.tsx
To reproduce:
1. Open incognito browser with no account is connected at first
2. Go to ifo
3. See ifo cards skeletons doesn't disappear even after data loaded
To review: 
https://deploy-preview-2680--pancakeswap-dev.netlify.app/
=> fix: (ifo): Skeleton in ifo card not disappear when no account is connected

package.json
[x] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[x] If your PR is work in progress, open it as `draft`
[x] Before requesting a review, all the checks need to pass
[x] Explain what your PR does
I made the clear issue that causes by different pattern usage on Windows OS.
=> fix(pkg): Pattern change for windows developer

src/state/lottery/index.ts
@Chef-Cheems That reducer is not used anywhere and it could not set the state since it doesn't return the new one. Should we remove it or keep it fixed?
To review:
https://deploy-preview-2657--pancakeswap-dev.netlify.app/
=> refactor: (lottery): Remove unused and broken reducer

src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/GetLpModal.tsx, src/views/Ifos/components/IfoSteps.tsx, src/views/Nft/market/components/BuySellModals/BuyModal/ReviewStage.tsx
Mainly for development to not point to pancake website
To review:
https://deploy-preview-2655--pancakeswap-dev.netlify.app/
=> refactor: Use relative path for exchange links

src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/PercentageOfTotal.tsx
When total amount is zero it falls back to big number 0 which calls toLocaleString with options object that bignumber's function doesn't have that parameters although it doesn't create problem on runtime, just to be on the safe side.
To review: 
https://deploy-preview-2700--pancakeswap-dev.netlify.app/
=> refactor: (ifo): Percentage of total when total amount 0

src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/index.tsx
To reproduce: 
1. Go to nft token page that you own
2. Logout
3. See set profile pic and list buttons still available
To review:
=> fix: (nft): Set profile and list buttons still seen after logout on user nft

public/locales/ru-RU.json
The Russian translation that was used here is English word Reward. I think it is not exact in representing this menu item. Earn - Заработать. Not only my correction is more exact translation and better meaning, it is even more attractive sound in Russian.
=> [Ru-Translation] Sounds more appropriate

public/locales/ru-RU.json
The word harvest in Russian as a noun is different than verb. 
The old translation "Ожидание урожай" means like we wait for crop to grow and ripe. There is not harvest ready to collect but we are waiting for harvest to be ready. 
My version say that there is already a harvest ready and we are waiting not for a harvest itself but for the action to collect it.
=> [Ru-Translation] The meaning is different as verb and noun

public/locales/ru-RU.json
The translation is swimming pool. I think if plural `"Pools": "Пулы"` then should be `"Pool": "Пул"`. This only make sense. I wanted to change this one the most because it is absolutely incorrect translation that does not make any sense. In Russian Бассейн из exactly Swimming pool. And when you read a translation you think, What!!!? What swimming pool?!!
=> [Ru-Translation] It is not a swimming pool

public/locales/ru-RU.json
It sounded like when you trade in NFT for CAKE you lose access to CAKE forever. At leas it is very unclear from the translation, to what asset you are going to lose access CAKE or NFT.
=> [Ru-Translation] Was very confusing

public/locales/ru-RU.json
The word `bet` was used as translation.
=> [Ru-Translation] incorrect word.

public/locales/ru-RU.json
The word used in Russian was something like stash. Not enough in stash.  Although it Souds more or less ok, and perhaps even fit, the word Balance is more clear here. For запас there might be a question, what zapas? Where is that zapas? Because it is a new term. And term balance is clear.
=> [Ru-Translation] change term for balance

src/components/RoiCalculatorModal/RoiCard.tsx, src/components/RoiCalculatorModal/useRoiCalculatorReducer.ts
To reproduce: 
1. Go to pools
2. Click apy calculator button any of the pools
3. Go to expected roi section
4. Change value to something else
5. See error message which shouldn't be there
6. Also Input value accepts non-digit values which shouldn't do
To review:
https://deploy-preview-2658--pancakeswap-dev.netlify.app/
=> fix: (roi): Expected roi input validation and error message

src/App.tsx, src/hooks/useInactiveListener.ts
To reproduce:
With injected wallet
1. Go to your wallet settings (i.e Metamask) set Auto - Lock timer (Settings -> Advanced)
2. Connect to website
3. Wait idle
4. Check redux state from browser that user profile and nft state still visible
With walletconnect
1. Connect to website via WalletConnect
2. Disconnect from the device that you use to scan qr code
3. Check redux state from browser that user profile and nft state still visible
To review:
https://deploy-preview-2732--pancakeswap-dev.netlify.app/
=> fix: User state still visible when wallet disconnects with Auto-Lock or WalletConnect

src/views/Info/components/InfoTables/PoolsTable.tsx, src/views/Info/components/InfoTables/TokensTable.tsx
To reproduce
2. Order pools or token list by liquidity
3. See it doesn't order
To review: 
https://deploy-preview-2753--pancakeswap-dev.netlify.app/
=> fix: (info): Order by liquidity in pools and token list

src/config/localization/translations.json, src/views/Lottery/components/AllHistoryCard/index.tsx, src/views/Lottery/components/PreviousRoundCard/Body.tsx, src/views/Lottery/components/PreviousRoundCard/Footer.tsx
To reproduce: 
1. Go to lottery 
2. Go to history
3. Remove round number to make it empty
4. See skeleton stays there
To review:
https://deploy-preview-2749--pancakeswap-dev.netlify.app/
=> fix: (lottery): Skeleton shown when round number is empty in history

src/views/Nft/market/Collections/index.tsx
To review: 
1. Go collections https://pancakeswap.finance/nfts/collections/
2. Go to second page by scrolling down first to reach pagination
3. Since it has less item than the first one, the item list is not visible you have to scroll up 
To review:
https://deploy-preview-2739--pancakeswap-dev.netlify.app/
=> fix: (nft): Collection list stays at old scroll position when page changes

src/hooks/useContract.ts, src/utils/contractHelpers.ts
To reproduce:
1. Go to webpage without connecting wallet
2. Go to an individual token page on which token is not listed
3. See it shows owner information not available
To review: 
https://deploy-preview-2740--pancakeswap-dev.netlify.app/
=> fix: (nft): Owner info not available for unconnected users when nft is not listed

src/state/swap/hooks.ts, src/views/Swap/components/Chart/PriceChartContainer.tsx
`getLpAddress` throws error when tokens are same
=> fix(swap): Prevent crash on same token address

src/views/Swap/components/Chart/PriceChartContainer.tsx
Although the price in currentSwapPrice object is the same, the object itself is different than the previous one, that causes rerender frequently unnecessarily.
To review: 
https://deploy-preview-2778--pancakeswap-dev.netlify.app/
=> refactor: (price-chart): Reduce amount of render when props are the same

src/views/Predictions/Desktop.tsx, src/views/Predictions/components/Container.tsx
To reproduce:
1. Go to prediction on desktop
2. See chart button and bar at the bottom not visible completely
To review:
https://deploy-preview-2798--pancakeswap-dev.netlify.app/
=> fix: (prediction): Charts button not visible at first sight on desktop

src/state/swap/fetch/fetchPairPriceData.ts, src/state/swap/hooks.ts, src/utils/requestWithTimeout.ts, src/views/Info/utils/infoQueryHelpers.ts
When graphql is unresponsive fetching operation keeps sending new request on each render, (possibly it is because heavy operation to keep all the function call data in memory) that makes browser hard to scroll or other things.
To review:
https://deploy-preview-2791--pancakeswap-dev.netlify.app/
=> fix: (swap-chart): Add timeout when graphql server is unresponsive

src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
To reproduce:
1. Go to IFO
2. Go to past ifos
3. Click one that doesn't have basic pool unlimited pool distinction
4. See price per fee shown NaN
To review:
https://deploy-preview-2794--pancakeswap-dev.netlify.app/
=> fix: (ifo): Price per fee shown NaN in old ifos

src/views/Farms/components/DepositModal.tsx, src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx, src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
To reproduce:
1. Go to pools
2. Click stake button when apr is loading
3. See NaN on annual roi calculation
=> fix: Annual roi calculation shows NaN when apr is loading in stake modal

src/views/Ifos/components/IfoFoldableCard/Achievement.tsx
To reproduce:
1. Go to ifo on mobile
2. See excessive margin on ifo info links (learn more about token and see contract)
To review:
https://deploy-preview-2813--pancakeswap-dev.netlify.app/
=> fix: (ifo): Excessive margin on info links in mobile

src/views/Pools/components/PoolsTable/Cells/EndsInCell.tsx
To reproduce:
1. Go to pools table
2. Check one pools that has starts in countdown
3. See it shows infinite skeleton until pool started
To review:
=> fix: (pools): Blocks cell in rows shows infinite skeleton when starts in countdown

src/hooks/useContract.ts, src/views/Nft/market/hooks/useNftOwner.tsx
Currently it uses wallet rpc to check ntf ownership when account is connected
=> refactor: (nft owner): Use simple rpc provider even when account connected

src/views/Swap/components/AdvancedSwapDetails.tsx
To reproduce:
1. Go to swap in mobile
2. Put amount to see swap details
3. See tooltips of swap details are not visible completely
To review:
https://deploy-preview-2846--pancakeswap-dev.netlify.app/
=> fix: (swap): Tooltips are not visible completely in mobile

src/views/Ifos/components/IfoFoldableCard/Timer.tsx
When day hour or minute is 0 it shows pure zero text without time indicator
=> fix: (ifo): Timer shows 0 without time indicator and translations

src/views/Nft/market/Home/Collections.tsx
Since currently there are more collections than 5, we don't need that placeholder anymore imho
To review:
https://deploy-preview-2869--pancakeswap-dev.netlify.app/
=> fix: (nft overview): Remove placeholder on hot collections

src/views/Swap/index.tsx
1. Go to (https://pancakeswap.finance/swap/0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d) (USDC Token)
2. See import warning modal
3. Click x button
4. See 404 Page
It should return to default swap page.
=> fix: (import token):  Cancel button on Import token modal redirects to 404 not found page

src/state/index.ts
not 100% sure why lodash cloneDeep messed up the token list `current`
=> fix(token-list): Token list messed up on localstorage redux

src/views/TradingCompetition/index.tsx
To reproduce:
1. Go to https://pancakeswap.finance/competition without account connected
2. See Starting Soon although competition finished
To review:
https://deploy-preview-2922--pancakeswap-dev.netlify.app/
=> fix: (competition): Competition page without account shows to start battle

src/config/constants/meta.ts
We could separate the pages, but it would be a overkill just for the title, therefore it is better to have generic title.
To review:
https://deploy-preview-2976--pancakeswap-dev.netlify.app/
=> fix: (profile): Page title is wrong when viewing other account profile

src/views/Pools/components/CakeVaultCard/VaultCardActions/index.tsx
When user has zero balance, showing 0,00$ instead of loading.
=> fix(ifo): Show zero balance instead of loading

src/views/Ifos/components/IfoLayout.tsx
when `grid` div contains `margin-x: auto`, it would resize the section somehow which leads to unexpected resize section.
=> fix(ifo): Avoid resize ifo section when loading

src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/MainNFTCard.tsx, src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/OwnerCard.tsx, src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/ForSaleTableRows.tsx, src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx, src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ManagePancakeBunniesCard.tsx, src/views/Nft/market/components/BuySellModals/BuyModal/styles.tsx, src/views/Nft/market/components/CollectibleCard/styles.tsx
This pr will limit precision to 5 visually for all the places that price is represented
Before:
After:
=> fix: (nft): Nft details page price precision distorts display when too many

src/components/RoiCalculatorModal/index.tsx, src/state/pools/hooks.ts, src/state/pools/index.ts, src/views/Ifos/components/IfoPoolVaultCard.tsx
Currently ifo card mobile staking loading indicator is using pool state userdata loading (which never gets false because all pools data fetch is not triggered), should use vault user data loading flag instead
To reproduce component issue:
1. Go to ifo page in mobile and connect account
2. See ifo card staking component loading gets stuck
To reproduce roi issue: 
1. Click apr calculator in mobile
2. Click my balance
3. See NaN
—————————-
Cake pool calls reduced from 4 to 2 multicall request
To review:
https://deploy-preview-3048--pancakeswap-dev.netlify.app/
=> fix: (ifo): Mobile Pool card staking component loading gets stuck and NaN in roi calculator balance

src/views/Nft/market/components/Activity/ActivityRow.tsx, src/views/Nft/market/components/Activity/MobileModal.tsx, src/views/Nft/market/components/NFTMedia.tsx
1. Go to nft activities (https://pancakeswap.finance/nfts/collections/0xC448498DDC536ad6F5d437325725dCf504d2d964#activity)
2. See items thumbnails not shown if there is no image file
To review:
https://deploy-preview-2865--pancakeswap-dev.netlify.app/
=> fix: (nft-activity): Gif or Video thumbnails not shown in activity row

src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/MainNFTCard.tsx, src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx, src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
To reproduce:
Go to pb bunny details page
Then change to another one by using more from collection component
See nft media doesnt change and previous countdown has to be waited for for sale table and lowest price
=> fix: (nft): PB nft media gets stuck and countdown has to be waited for sale data

src/hooks/useContract.ts, src/views/FarmAuction/components/AuctionCakeBurn.tsx, src/views/FarmAuction/hooks/useAuctionHistory.tsx, src/views/FarmAuction/hooks/useCongratulateAuctionWinner.tsx, src/views/FarmAuction/hooks/useCurrentFarmAuction.ts, src/views/FarmAuction/hooks/useReclaimAuctionBid.ts, src/views/FarmAuction/hooks/useWhitelistedAddresses.ts
To reproduce:
1. Go directly to Farm Auction page with account connected eagerly (https://pancakeswap.finance/farms/auction)
2. See `unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, ...` errors
To review:
https://deploy-preview-2944--pancakeswap-dev.netlify.app/
=> fix: (farm auction): Unknown account error when accessing page directly with account

src/views/Nft/market/ActivityHistory/ActivityHistory.tsx, src/views/Nft/market/ActivityHistory/utils/fetchActivityNftMetadata.tsx, src/views/Nft/market/Profile/components/ActivityHistory/index.tsx
No need to fetch pb metadata for each nft in the list that have same type of nfts
=> perf: (activity): Reduce nft metadata calls for PB nfts

src/state/pools/index.ts
It's hard to reproduce the exact RPC node error when unstable
to reproduce similar situation: 
1. go to https://pancakeswap.finance/pools 
2. Setting network to offline to simulate when RPC node is not stable
3. scroll or wait for it hangs
Lesson learned: thunk that is not created by `createAsyncThunk` must handle error properly 🧐
=> fix(pools): Catch error on Pools thunk action

src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx
Root cause: 
When cheapest nft being loaded (with valid tokenId), placeholder nft is used (nothingForSaleBunny) of which the tokenId is the token name. Cheapest nft with tokenId makes component rerender
=> fix: (nft): Image flickers in pb nft details page

sentry.client.config.js
Let's ignore global errors for reduce the noise. We are still capturing errors from `logError` and ErrorBoundary
=> chore(sentry): Ignore global errors

src/views/Nft/market/Profile/index.tsx
To reproduce:
1. Connect your account
2. Go to others users profile
3. See under the avatar connected user account address is shown
=> fix: (profile): Connected account path is shown when viewing other users profile in profile header

src/views/Swap/components/SwapWarningModal/SafemoonWarning.tsx
They yeeted old tweet & updated & shared again.
Was forwardin to blank space & updated with new one.
old tweet: https://twitter.com/safemoon/status/1470078043469275141?s=20
new tweet: https://twitter.com/safemoon/status/1477770592031887360
=> fix(swap): SAFEMOON warning's misdirection

src/state/farms/index.ts
`builder.addMatcher` on extraReducer matching global action instead of farm specific action
=> fix(farm): Only match farm loading key instead of global

src/config/constants/tokenLists/pancake-default.tokenlist.json
we yeeted from /toolkit https://github.com/pancakeswap/pancake-toolkit/pull/388
but still in default token list, please yeet from also here
from preview:
no safemoon finally
if you import, you will see 2 warnin (anyone create and special safemoon warnn)
seems fine.
=> fix(swap): Remove SAFEMOON from frontend default list

src/state/nftMarket/reducer.ts, src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx, src/views/Nft/market/Collection/Traits/PancakeBunniesTraits.tsx, src/views/Nft/market/hooks/useGetCollectionDistribution.tsx
To reproduce
1. Go to pb collection page
2. See total count on header
3. It shows old api data
=> fix: (nft): PB Bunny total count shows old api data on page header

src/hooks/Tokens.ts, src/state/lists/hooks.ts, src/state/user/hooks/index.tsx
Default token lists should be added when searching user lp tokens in liquidity page
=> fix: (remove liquidity): Many lp tokens not visible by default in liquidity page

package.json, yarn.lock
Recent update of Nextjs broke integration with Sentry and requires update for Sentry package.
https://github.com/vercel/next.js/issues/33726
Issue was fixed here: https://github.com/getsentry/sentry-javascript/pull/4467
Examples of failing CI for open PRs:
https://github.com/pancakeswap/pancake-frontend/pull/3155
https://github.com/pancakeswap/pancake-frontend/pull/3157
https://github.com/pancakeswap/pancake-frontend/pull/3159
https://github.com/pancakeswap/pancake-frontend/pull/3166
They all fail due to the same reason:
```js
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: res.once is not a function
```
=> build: Bump up @sentry/nextjs version to fix failing builds

src/pages/_app.tsx
Showing ErrorBoundary on development does not provide any help to debug
=> chore: Only enable ErrorBoundary on prod

src/state/nftMarket/reducer.ts, src/views/Nft/market/Collection/Items/ClearAllButton.tsx, src/views/Nft/market/Collection/Items/Filters.tsx, src/views/Nft/market/Collection/Items/SortSelect.tsx
To reproduce:
1. Go collection items page
2. Change filter by all and order by
3. Filter by trait
4. Click clear
5. See sort and order options defaulted although it is not visible to user on options
=> fix: (nft): Sort and order options defaulted when clicking filter clear button

src/pages/nfts/collections/[collectionAddress].tsx
The whole `initialReduxState` will override the persist state
=> fix(nft): Collection ssg redux state overrided

src/components/SubgraphHealthIndicator/index.tsx
Issue mainly happens on mobile where user has to hold down pressing in order to see tooltip text.
1. Go to nfts on mobile
2. See subgraph indicator
3. Press down the component to see tooltip
4. It selects the text if you press down the text area and shows action menu depending on the browser
=> fix: Make subgraph health indicator text not selectable

src/state/nftMarket/hooks.ts, src/state/nftMarket/reducer.ts, src/state/nftMarket/types.ts, src/views/Nft/market/components/NFTMedia.tsx
To reproduce: 
1. Set your phone to low power mode (iphone preferred)
2. Go to nft activity
3. Set collection to pancake bunnies (this is where the most video media )
4. See thumbnails are not shown
=> fix: (nft): Nft Media with video not shown when low power mode enabled in mobile

src/components/Balance.tsx, src/views/Pools/components/BountyCard.tsx
the result 
I also tried Framer-motion [AnimatePresence](https://www.framer.com/docs/animate-presence/) component to make a transition between the Balance component and Skeleton component, but as the screenshot,
this is a more complex way to apply this to the codebase.
So, I decide to wrap the Blanace  componet to AnimatedBlanace.
=> chore: Shared component AnimatedBlanace

src/views/Predictions/Desktop.tsx, src/views/Predictions/Mobile.tsx, src/views/Predictions/components/CollectWinningsPopup.tsx, src/views/Predictions/components/Container.tsx, src/views/Predictions/context/SwiperProvider.tsx
Using `React.memo` for components not receiving props to avoid redundant re-render in Prediction page.
```
<>
<PageMeta />
<SwiperProvider>
<Container>
{isDesktop ? <Desktop /> : <Mobile />}
<CollectWinningsPopup />
</Container>
</SwiperProvider>
</>
```
=> perf(prediction): Avoid redundant re-render

src/state/farms/fetchMasterChefData.ts, src/state/farms/hooks.ts, src/state/farms/index.ts, src/state/types.ts, src/views/Farms/Farms.tsx, src/views/Home/hooks/useFarmsWithBalance.tsx
It's weird get pool info using multicallv2 with `requireSuccess = false` will result out of gas issue when pid is not found 🤔 
Has to fetch poolLength and filter out the farm isn't there
=> feat(farms): Add poolLength check

src/views/Teams/components/TeamListCard.tsx
To review:
1. Go to leaderboard page
2. See team points are 0 instead of coming soon
=> fix: Remove 0 teams point in leaderboard page

src/views/Ifos/components/Hero.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
**Steps to reproduce:**
1. Go to IFO Finished page `/ifo/history` 
2. Press on `How does it work?` button
3. The button doesn't do anything
Another link that doesn't work is in `/ifo/history` page on "Sale Finished!" card detail when any warning message is shown. By that, I mean in the `IfoCardTokens` component where the link was not working as well. 
This PR attempts to fix these link issues.
=> fix(ifo): Fix how does it work buttons

src/hooks/useSWRContract.ts
swr `data`, `isValidating`, `error` are lazy getter, follow the pattern to prevent re-render when no need for checking all these values.
=> perf: Lazy get swr status

src/components/CurrencyInputPanel/index.tsx
To reproduce:
1. Go to swap
2. Select token with amount
3. Change language
4. See max button not translated
=> fix: Missing max button translation on swap

src/pages/nfts/collections/[collectionAddress].tsx, src/pages/nfts/collections/[collectionAddress]/[tokenId].tsx, src/pages/teams/[id].tsx
fallback undefined will override the default fallback `{}`
most likely happens when you access to the url directly, client side navigation works fine.
=> fix: SWR fallback undefined override

src/views/Voting/components/DatePicker/DatePickerPortal.tsx
=> fix: Add DarkTheme for TimePicker

src/views/Nft/market/hooks/useCollectionNfts.tsx
To reproduce:
1. Go to one of the collection items page
2. Order by lowest price
3. Select filter by all
4. See result size shows filtered number instead of all items
=> fix: (nft): Wrong result amount in collection listing

src/hooks/useApproveConfirmTransaction.tsx, src/hooks/useContract.ts, src/hooks/useTokenBalance.ts, src/utils/requiresApproval.ts, src/views/FarmAuction/components/PlaceBidModal.tsx, src/views/FarmAuction/components/ReclaimBidCard.tsx, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx, src/views/Ifos/components/IfoFoldableCard/index.tsx, src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx, src/views/Nft/market/Profile/components/EditProfileModal/ApproveCakeView.tsx, src/views/Nft/market/Profile/components/EditProfileModal/StartView.tsx, src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx, src/views/Nft/market/components/BuySellModals/SellModal/index.tsx, src/views/Nft/market/hooks/useCompleteNft.tsx, src/views/Nft/market/hooks/useNftOwner.tsx, src/views/PancakeSquad/components/Buttons/BuyTickets.tsx, src/views/Pools/hooks/useApprove.tsx, src/views/ProfileCreation/ConfirmProfileCreationModal.tsx, src/views/ProfileCreation/Mint.tsx
For better ux if users wallet rpc node is laggy. This also extracts commonly used requiresApproval function
=> refactor: Move reader cake contract calls to pcs nodes for better ux

src/views/Voting/components/DatePicker/DatePickerPortal.tsx
=> fix(proposal): Fix time select on light theme

src/components/EasyMde/index.tsx
=> fix: Update cursor color in editor

src/views/Nft/market/hooks/useCollectionNfts.tsx
To reproduce: 
1. Go to any collection items
2. Select filter by all
3. Select order by token id
4. Go to bottom and load more
5. At first click nothing happens, user has to click twice to get more items
=> fix: Collection listing order by token id load more

src/hooks/useActiveIfoWithBlocks.ts
It returns ethers bignumber instead of number which makes comparisons against currentblock always true
=> fix: Ifo banner keeps being alive after ifo ends

src/utils/localStorageOrders.ts, src/views/LimitOrders/components/LimitOrderTable/index.tsx, src/views/LimitOrders/hooks/useFormattedOrderData.ts, src/views/LimitOrders/hooks/useGelatoLimitOrdersHistory.ts, src/views/LimitOrders/types.ts
Currently when open orders from gelato returns empty array, orders in local storage don't get updated
=> fix: (limit-orders): Order still visible after executed in open orders tab

src/utils/clearUserStates.ts, src/utils/getLocalStorageItemKeys.ts, src/utils/localStorageOrders.ts
To reproduce:
1. Connect account that has limit orders
2. Go limit order page
3. Go to order history
4. Disconnect account 
5. See data still available in web storage
=> fix: Remove limit order local storage data after disconnect

src/views/LimitOrders/index.tsx
=> fix(limit-orders): Avoid showing incorrect price format in confirm modal

src/hooks/useSWRContract.ts
Thanks @chef-jojo for finding the root cause. 
Root cause: 
When cloning the object destructuring makes all the lazy getters get called thus it causes rerendering as if it is used in hooks
=> fix: Swr hooks rerenders before fetch although isValidating is not used

src/views/Lottery/components/BuyTicketsModal/TicketInput.tsx
=> fix: Fix color for Lottery Input

src/components/Menu/utils.ts, src/state/info/queries/tokens/priceData.ts, src/state/swap/fetch/fetchDerivedPriceData.ts, src/state/wallet/hooks.ts, src/utils/localStorageOrders.ts, src/views/FarmAuction/helpers.tsx, src/views/Info/components/InfoSearch/index.tsx, src/views/Info/components/InfoTables/TokensTable.tsx, src/views/Info/hooks/useBlocksFromTimestamps.ts, src/views/LimitOrders/hooks/useGelatoLimitOrdersHistory.ts, src/views/Lottery/components/ViewTicketsModal/PreviousRoundTicketsInner.tsx, src/views/Nft/market/ActivityHistory/utils/sortActivity.tsx, src/views/Nft/market/Collection/Traits/PancakeBunniesTraits.tsx, src/views/Nft/market/Collections/index.tsx, src/views/Nft/market/Profile/utils/sortUserActivity.tsx, src/views/TradingCompetition/components/TeamRanks/index.tsx
Orderby should be used where sort is applied on direct array references to not sort the array that is passed
=> refactor: Use orderBy instead of sort

src/state/predictions/config.ts, src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
Currently buffer phase is not working correctly which let users to bet until the very end of open round which results transaction failures on onchain side when submitting a transaction exceeds lock timestamp
@Chef-Cheems can you confirm ?
=> fix: (prediction) Wrong buffer phase let users to bet until the very end of the open round

src/views/Pool/index.tsx
To reproduce:
1. Go to liquidity with an account that has lp
2. See it shows no lp's found message for a short time when lp's loading
=> fix: (liquidity): No Lp found message when lp's are loading

src/views/Predictions/components/RoundCard/SetPositionCard.tsx
To reproduce:
1. Go to prediction on mobile
2. Connect account
3. Go to open round
4. Select up or down
5. Tap back button
6. See swiper doesn't work anymore
=> fix: (prediction): Swiper doesn't work after clicking back button on round card on mobile

src/state/lottery/index.ts
To reproduce: 
2. Buy ticket
3. See Your tickets section on main page not updated that you have to refresh the page to see it or wait for the next cycle of fetchcurrentround
=> fix: Lottery selectors not trigger rerender after user tickets fetch

src/views/Predictions/components/ChainlinkChart.tsx, src/views/Predictions/components/Label.tsx, src/views/Predictions/components/RoundCard/LiveRoundCard.tsx, src/views/Predictions/components/RoundCard/LiveRoundPrice.tsx, src/views/Predictions/hooks/usePollOraclePrice.ts
Although rounds in here are just visual representation and it is not affecting predictions, this issue is complaint by users that seeing different price after round closes. To mitigate the price discrepancy, it will send price fetching right before round closes.
=> fix: (prediction): Mitigate discrepancy between last price of live round card and expired round card

src/views/LimitOrders/components/LimitOrderTable/TableNavigation.tsx, src/views/LimitOrders/components/LimitOrderTable/index.tsx
=> fix: (limit-order): Missing subgraph health indicator when no order

src/state/lottery/helpers.ts, src/views/Home/components/Banners/LotteryBanner.tsx, src/views/Home/components/Banners/hooks/useIsRenderLotteryBanner.tsx, src/views/Home/components/Banners/hooks/useNextEventCountdown.ts, src/views/Lottery/hooks/useGetNextLotteryEvent.ts
Currently there is a graph data and additional onchain lottery requests being made which we don't need it when we show lottery banner
=> refactor: (lottery-banner): Use swr for to fetch current lottery without fetching graph data

src/state/user/hooks/index.tsx
The pairs that doesn't contain tracked base such as Duet-Cake or Gmt-usdc not visible by default in the list when removing liquidity therefore user has to import it.
=> fix: (liquidity): Farm pairs that doesn't contain tracked base is not visible when removing liquidity

package.json, yarn.lock
Although we are already using it, it is better to set this version in package json
=> chore: Bump up easymde

src/state/predictions/hooks.ts, src/state/predictions/index.ts, src/state/predictions/selectors.ts, src/views/Predictions/Positions.tsx, src/views/Predictions/components/PrevNextNav.tsx, src/views/Predictions/hooks/useOnNextRound.ts, src/views/Predictions/hooks/usePollPredictions.ts
Before: 
https://user-images.githubusercontent.com/2213635/159758997-d4f1e562-bb8e-4896-b93c-9336f5f5c9f8.mov
After:
https://user-images.githubusercontent.com/2213635/159759096-333cdef6-7575-47a3-b900-8d97eb6f9066.mov
This fix will also reduce the calls, the size of swr cache of prediction and rerenders
=> fix: (prediction): Round card transition on prediction

src/state/nftMarket/helpers.ts, src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ManagePancakeBunniesCard.tsx, src/views/Nft/market/hooks/useNftsForAddress.tsx
Root cause is laggy middleware shows the last data after key changes. We should keep this behaviour and resolve the account changes in the fetcher
To reproduce:
1. Go to pb nft token detail page that account has bunny
2. See nfts on manage yours
3. Logout
4. See it is still visible
=> fix: Manage nft cards still shows user nfts after logout

next.config.js
`window.SENTRY_RELEASE` doesn't get the latest commit
=> chore: Update Sentry Version on Prod

src/views/Predictions/hooks/useOnNextRound.ts
To reproduce: 
2. Wait for the round transition happens to new live round
3. Switch to another round from live one
4. See after the next refresh cycle it will move to the round next to the switched one
=> fix: Swiper moves to next round card from currently focused after removing earliest card

src/views/Predictions/components/ChainlinkChart.tsx
To review:
2. Go to chainlink chart
3. See colors of round dots on the chart on both themes
=> refactor: Use more visible colors for chainlink chart round dots

src/state/predictions/index.ts
`Collect Win` button is not showned when history after polling. 
Reproduce:
1. Win a bet
2. Open history tab
3. `Collect Win` is disappeared
=> fix: Not show collect win after polling predictions

packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap, packages/uikit/src/components/Footer/config.tsx
"Datch" seems to be typo of "Dach".
"Dach" means the areas where people speak German (Deutschland+Austria+Confoederatio Helvetica).
As a language label, "Deutsch"(German) is more clear.
=> chore: Use Deutsch as a language label

src/views/Predictions/components/RoundCard/SetPositionCard.tsx
No need to have that high dust for gas prices.
=> fix: Reduce prediction dust by tenth and set max balance to zero if it is lower than

src/state/nftMarket/helpers.ts, src/state/nftMarket/types.ts, src/views/Nft/market/hooks/useCompleteNft.tsx, src/views/Nft/market/hooks/useNftOwner.tsx
Because of the delays on graph api, users will not able to see actual market data on token detail and user profile page for long times.
To reproduce on token detail page:
1. Go to any collection 
2. Buy one item 
3. After successful transaction it still shows the old price and it will be still on sale
To reproduce issues on profile page:
1. Change sell price of nft that is on market
2. See market data is not updated if graph data is delayed
------------------------
1. Remove nft from the market
2. See it shows the same nft twice on the list until graph api is updated
------------------------
1. List nft to the market
2. User has to wait until graph api is updated (and until that time that nft is not shown in the user nft list)
=> fix: (nft): Token detail and user profile pages not show updated market data

src/views/Nft/market/hooks/useCollectionNfts.tsx
Currently user has to refresh the page in order to update nft collection listings
To reproduce:
1. Go to one collection listings
2. Then go to another collection item listing
3. Then go back to the first collection listings
4. See it shows the old data since it is not revalidated
=> fix: (nft): Collection listings not updated in user session

packages/uikit/src/components/Skeleton/Skeleton.tsx, packages/uikit/src/components/Skeleton/index.tsx, packages/uikit/src/components/Skeleton/types.ts, src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
using SkeletonV2 to add a skeleton to avoid layout shift after data load
SkeletonV2 will handle the transition between Skeleton and content automatically
before:
after:
[desktop]
[Mobile]
=> feat: add skeleton for lock cake table view

src/hooks/useIsWindowVisible.ts
This hook is used in useCountdown hook which runs in every second (on prediction for example) as a result of this window visible default value calculated every second unnecessarily.
=> fix: UseIsWindowVisible hook initial state value calculated on each render

src/components/ScrollToTopButton/index.tsx
It renders on each scroll event which puts load on while user visiting the page
=> fix: (nft): Collection listing page scroll to top button renders on each scroll event

src/hooks/useContract.ts
https://github.com/pancakeswap/pancake-frontend/blob/2d1c22c99035d319cf118019d0968776e7295b0c/src/components/GlobalCheckClaimStatus/index.tsx#L73
When loading the page for the first time, it renders twice since reference from contract hook changes (because of wallet login) even the signer is not used. In here it makes requests twice unnecessarily.
=> fix: Contract hooks cause unnecessary rerenders and requests even signer not used

src/hooks/useContract.ts
Currently there is no issue since abi and address are not null or if it is error will be fetched in catch block below but it is good to fix it
=> fix: Can return contract check in useContract hook

src/views/Info/components/CurrencyLogo/index.tsx
=> chore: Change default trustwallet logo url

src/views/Home/components/Banners/hooks/useIsRenderLotteryBanner.tsx
No need to refresh on focus or on reconnect eagerly which puts pressure on nodes
=> perf: Reduce banner check calls by only making with intervals

src/state/farms/fetchFarms.ts, src/state/farmsV1/fetchFarms.ts, src/utils/bigNumber.ts
Currently it creates ~200 same bignumber objects when fetching farms
=> refactor: Use cached big number in farms fetching

src/views/Nft/market/Collections/index.tsx
It will reduce the amount of requests drastically, currently there is 54 price requests (2 per collection least and most) when user visits the collection page by default which is not needed.
To reproduce 
1. Go to collection list page
2. See the graphql network requests
=> perf: Don't make price requests when view mode is card and not sorted by price

src/state/pools/index.ts, src/state/types.ts, src/views/Migration/components/MigrationStep2/NewPool/PoolRow.tsx, src/views/Migration/components/MigrationStep2/NewPool/index.tsx, src/views/Pools/components/CakeVaultCard/VaultCardActions/VaultStakeActions.tsx, src/views/Pools/components/LockedPool/Buttons/AddCakeButton.tsx, src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx, src/views/Pools/components/PoolsTable/ActionPanel/AutoHarvest.tsx, src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx, src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx, src/views/Pools/components/PoolsTable/Cells/EarningsCell.tsx, src/views/Pools/components/PoolsTable/Cells/StakedCell.tsx, src/views/Pools/components/PoolsTable/PoolRow.tsx, src/views/Pools/components/PoolsTable/PoolsTable.tsx, src/views/Pools/index.tsx
Introducing userdataloaded flag per pool, which is beneficial if only one pool needed in page
To reproduce: 
1. Go to pools
2. Go to finished pools 
3. Click migration page
4. Since it opens page in new tab there is no state in redux
5. Go to second step
6. See add cake button is not loaded (if user already has cakes in locked pool)
=> fix: Migration page new cake pool add cake button gets stuck and use userdataloaded per pool

src/state/info/queries/tokens/transactions.ts
fix: wrong query condition for token transaction info page.
=> fix: wrong query condition in token transaction

src/views/Home/components/UserBanner/UserDetail.tsx
Currently both components inside the home page user detail component are rendered and then hidden by css which causes performance degradation
=> perf: Make User detail component render only one component based on device

src/views/FarmAuction/components/PlaceBidModal.tsx, src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
To reproduce: 
1. Go to lottery buy ticket
3. See max button translation not applied
=> fix: Missing translation on modals max button

src/utils/formatBalance.ts, src/views/Pools/components/LockedPool/utils/formatRoi.ts
Root cause of the issue is, the return value is converted back to number which causes the issue if user device language is other than english
To reproduce
1. Go to locked pool with a device language german
2. Click add cake
3. Enter value to make expected roi higher than 1k
4. See it shows wrong value
=> fix: (cake pool): Expected roi calculation in other languages

packages/uikit/src/components/Svg/Svg.tsx
https://ethanclevenger.com/Filter-Bug-Turns-SVGs-Invisible-on-iOS-Browsers/
To reproduce:
1. Go to prediction on ios safari
2. See red,green or gray arrows on round cards
3. Send browser to background and back to foreground again
4. See sometimes arrows are getting invisible
=> fix: (prediction): Round card arrow svgs disappears on ios browsers after making app on foreground again

src/components/Menu/hooks/useCompetitionStatus.ts
https://user-images.githubusercontent.com/2213635/168925279-6bade896-f9ec-4f60-b3a0-debba94c3062.mov
Other issue is currently competition banner will be flashed after competition ends when loading page
=> fix: Trading competition menu shows soon when loading page

packages/uikit/src/widgets/Modal/ModalContext.tsx, packages/uikit/src/widgets/Modal/useModal.ts, src/views/Swap/components/SwapWarningModal/index.tsx, src/views/Swap/index.tsx
To reproduce: 
1. Go to prediction after cleaning the cache
2. See risk disclaimer
3. Click the overlay
4. See modal is closed though it shouldn't be
=> fix: Modal close on overlay click cannot be disabled

src/views/Pools/components/LockedPool/Buttons/AddCakeButton.tsx, src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx, src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx, src/views/Pools/components/LockedPool/types/index.ts
fixing when 1 week locked cake trying to renew the extension, there're some seconds gaps between firing the txn and confirmation.
Add 30s buffer in this case
=> fix: Locked Pool min duration extend

src/views/Home/components/Footer.tsx
Currently it is done by css visibility property which renders component and loads images regardless of dimension
=> perf: Dont load floating pancakes wrapper on mobile

packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx, packages/uikit/src/widgets/Menu/components/UserMenu/types.ts, src/components/Menu/UserMenu/WalletUserMenuItem.tsx, src/components/Menu/UserMenu/index.tsx
It will reduce the calls where only place of bnb account balance call is in user dropdown menu (such as home page, pools, farms etc.). Other places that uses bnb account balance will not be effected from this since it is only related to dropdown menu.
=> perf: (menu): Make bnb account balance call only when dropdown user menu open

src/hooks/useAccountEventListener.ts, src/hooks/useAuth.tsx, src/utils/clearUserStates.ts, src/views/Home/index.tsx
According to this [PR](https://github.com/pancakeswap/pancake-frontend/commit/3f6beff0ecdf7701b7caaf1b4431be991a311982). We only call `tryLogin` function  when is Dapp browse.
So that we should not remove `connectorIdv2` when switching account.
Before:
https://user-images.githubusercontent.com/98292246/169635771-edfe8484-16c2-40ec-9b62-7e85b91ebbe0.mov
After:
https://user-images.githubusercontent.com/98292246/169635825-affe56cb-c5f1-4add-80e0-3955c340aa3d.mov
=> fix: Don't clear connectorIdv2 when user switching account

package.json, yarn.lock
This version moves dev related dependencies into devDependency thus saves size
=> chore: Bump up recharts

src/views/Nft/market/hooks/useCompleteNft.tsx, src/views/Nft/market/hooks/useNftOwner.tsx
Ownerof request triggeered twice in completeaccount hook because of marketdata changes the key, and it also requested twice in nftowner because of this. 
So it reduces 4 calls to 1
=> perf: Reduce owner of onchain requests

src/views/Farms/Farms.tsx, src/views/Voting/components/Footer.tsx, src/views/Voting/components/Hero.tsx
Imo those links should not be prefetched (i think they are not frequently visited) when they are visible anyways it will still be prefetched when they are hovered. @chef-jojo Maybe all next links visible prefetch should be false wdyt?
=> perf: (auction-voting): Make visible prefetch false for links

src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
Every time, open Add Cake modal need delete the zero in input.
Before:
https://user-images.githubusercontent.com/98292246/170952930-4be5c30f-8568-4455-8d6d-63f84d04201e.mov
After:
https://user-images.githubusercontent.com/98292246/170952941-b08ba128-a80c-4ef0-8aa0-fbf384c3d4a3.mov
=> feat: Add cake modal input empty

src/state/farms/selectors.ts
No need to deserialize whole farm where raw data is enough
=> perf: Remove redundant deserialize farm in farm selector hooks

src/views/Nft/market/ActivityHistory/ActivityHistory.tsx, src/views/Nft/market/ActivityHistory/utils/fetchActivityNftMetadata.tsx, src/views/Nft/market/Profile/components/ActivityHistory/index.tsx
Reduces calculation in collections activity by half
To review
1. Go to nft collection activity and see metadata loading properly
There is a bug as well that if two nfts with same id with different collections, metadata of one of them loaded with wrong or cannot be loaded.
=> fix: (nft): Nft activity metadata uniq function iteratee

packages/uikit/src/react-app-env.d.ts, src/hooks/useEagerConnect.ts, src/react-app-env.d.ts
Some dapp browser not allowing open new tab, when you accidentally click coinbase wallet, it will redirect to app store everytime on eager connect, causing not allowing switch wallet
=> fix(wallet): Coinbase eager connect keep deeplink on mobile

src/config/constants/farmAuctions.ts
Should we remove projects `HeroesTD` & `Everdome` on config?
Or just filter both in `Total whitelisted bidders`.
Cos if we delete from config, whoever wins before, in `Archive` will show `Unknown`.
=> feat: List Farm Auction 23

src/config/constants/farms.ts
@ChefMomota Sorry, I was wrong about removing auction hosting property for community farms, I remember that it is needed to show auction hosting ends info for them.
=> fix: Missing auction hosting ends info in community farms

packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
To reproduce:
1. Click connect wallet on wide mobile screens (higher than 320px)
2. See alignment of inner components is broken
=> fix: Alignment of connect wallet modal in wide mobile screens

src/state/wallet/hooks.ts
Reduces serialization operations in trade components, 
https://github.com/pancakeswap/pancake-frontend/blob/cb158e544df04dbac559516bcb6c932a283b9e18/src/state/multicall/hooks.ts#L59 
calls dependency that is passed by useBNBBalances will be memoized thus serialization operation will not be processed on each render
=> perf: Use memo in bnb balances hook to not serialize on each render

src/config/constants/info.ts
currently these constants not used but it is better to update them
=> fix: Treasury and buyback fee constants

packages/uikit/src/components/BottomNav/BottomNav.tsx
To reproduce:
1. Switch language to portuguese in mobile
2. Switch back to english
3. See leftover item in bottom navigation menu
=> fix: Leftover items from previous language in mobile menu navigation

src/contexts/Localization/Provider.tsx
It reduces memoized function memory footprint and calculations when language change
=> perf: Use key instead of translated text for include variable check

src/hooks/usePairs.ts
Each render creates a new array that triggers additional calculation and adding new generated key to multicall listeners
=> perf: Reduce calculations in import lp pool finder

packages/uikit/src/components/CoinSwitcher/CoinSwitcher.tsx, src/views/Predictions/Mobile.tsx, src/views/Predictions/components/Container.tsx, src/views/Predictions/components/Label.tsx
To reproduce: 
1. Go to prediction in mobile with a wallet browser that has its own toolbar (metamask) in iphone7-8 size phone
2. See it doesn't show the top and bottom of the prediction card container
=> fix: Prediction height in mobile

src/hooks/useInterval.ts, src/index.tsx, src/state/lists/updater.ts
This will save 2-3 mb of data when visiting other pages that does not contain currency search thus token list is not needed
=> perf: Run lists updater only when the page has currency search

src/views/Predictions/components/Label.tsx, src/views/Predictions/components/LabelPrice.tsx, src/views/Predictions/components/RoundCard/LiveRoundPrice.tsx
It rerenders too much when counting up and calls translation and other functions unnecessarily
=> perf: Separate label price countup from label component to reduce rerender

src/__tests__/views/predictions/helpers.test.ts, src/state/types.ts, src/views/Predictions/components/RoundCard/LiveRoundCard.tsx, src/views/Predictions/components/RoundResult/styles.tsx, src/views/Predictions/context/config.ts, src/views/Predictions/helpers.ts
To review: 
2. See price difference in open/expired rounds shows 4 digit precision
Before :
After:
=> feat: Use 4 digit precision when showing prediction price difference

src/state/lists/updater.ts
If it is accessed directly, token lists will not be fetched thus some of the lp's will not be seen by default, if user access the page with no cache
=> fix: Add liquidity overview page to the token list fetchers

src/views/Predictions/components/PositionTag.tsx
To reproduce: 
1. Go to prediction 
2. See position tags backgrounds not visible
3. In light theme mode nothing is visible
=> fix: Position tag background

src/views/Predictions/components/PositionTag.tsx
=> fix: (prediction): To burn tooltip position in round card in mobile

src/config/localization/translations.json, src/views/Predictions/components/RoundCard/OpenRoundCard.tsx
To reproduce:
2. Bet down
3. Refresh the page
4. See it displays 'Up entered'
=> fix: (prediction): Open round card shows wrong entered position after refresh

packages/uikit/src/hooks/useMatchBreakpoints.ts
@memoyil  Can you help to double check?
Width - `969px` & `967px` will show Profile & banner style was correct
Width - `968px` will jump to next breakPoint.
Before:
After:
=> fix: UseMatchBreakPoint prevMinWidth

src/views/Predictions/components/History/BetResult.tsx
To reproduce:
1. Go prediction history
2. Go to non claimed winning bets 
3. Expand the row
4. See colelct winnings button not displayed
=> fix: (prediction): Collect winnings button not displayed in bet results

src/views/Nft/market/components/Activity/MobileModal.tsx
This only happens on production build though. @chef-jojo I couldn't find the root cause of this issue, do you have an idea?
=> fix: (activity): Invisible view bscscan button text on mobile nft activity transaction details

src/views/AddLiquidity/components/common.tsx
To reproduce:
1. Go to add liquidity in firefox
2. Add liquidity
3. See circle graph in modal shows only one pair instead of showing 2 pieces
=> fix: Circle svg distribution issue in firefox

src/config/localization/translations.json, src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx, src/views/Pools/components/LockedPool/Buttons/ExtendDurationButton.tsx, src/views/Pools/components/LockedPool/Common/ExtendEnable.tsx, src/views/Pools/components/LockedPool/Common/LockDurationField.tsx, src/views/Pools/components/LockedPool/Common/LockedActions.tsx, src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx, src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx, src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx, src/views/Pools/components/LockedPool/hooks/useExtendEnable.tsx, src/views/Pools/components/LockedPool/types/index.ts, src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx, src/views/Pools/components/Vault/VaultRoiCalculatorModal.tsx, src/views/Pools/helpers.tsx
Extend duration check currently being done based on current duration (instead of left current duration) which causes issue when extending.
To reproduce
1. Go to locked pool
2. Click extend 
3. Put value that should not extend 52 weeks (if you have 10 weeks of locked pool and only 2 weeks left to put 50 weeks should not give an error)
4. See error and confirm button is disabled
=> fix: (pool): Extend duration check based on current duration causes locked vault to not extend

src/components/PhishingWarningBanner/index.tsx, src/views/Home/components/CompositeImage.tsx
Some browsers (safari, firefox i.e) still has a issue to load fallback even the original image is already available if picture tag is used, this causes to increase bandwidth.
It saves ~400kb data if page loaded without cache
=> perf: Use img onerror for fallback instead of picture tag to not load fallback always

packages/uikit/src/components/Box/Box.tsx
for now, MotionBox is only used by ModalContainer
and in ModalContext there's a LazyMotion wrapper
=> chore: use lazy motion in MotionBox

packages/localization/src/config/translations.json, src/__tests__/translations.test.ts, src/components/Menu/UserMenu/TransactionRow.tsx, src/hooks/useSwapCallback.ts, src/state/transactions/actions.ts, src/state/transactions/hooks.tsx, src/state/transactions/reducer.ts
This creates confusion to the users where there is discrepancy between onchain data and pcs website
=> fix: Transaction description in recent trxs can be off if slippage is too high and add translation support

src/views/Pottery/components/FinishedRounds/AllHistoryCard/Winner.tsx
=> fix: (pottery): Undefined nickname is displayed when winner has no profile

packages/uikit/src/hooks/useTooltip/types.ts, packages/uikit/src/hooks/useTooltip/useTooltip.tsx, src/views/Farms/components/YieldBooster/components/ActionButton.tsx
To reproduce: 
1. Go to mobile
2. Go to boosted farm
3. Tap yield booster tooltip
4. Link cannot be tapped because it disappears so quickly
=> fix: Link inside Booster tooltip cannot be clicked in mobile

packages/uikit/src/widgets/WalletModal/WalletCard.tsx, src/state/pools/helpers.ts, src/utils/apr.ts, src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx, src/views/Pottery/components/Pot/Deposit/index.tsx, src/views/Profile/components/ActivityHistory/index.tsx
Locale lowercase might return unexpected results when it is used in address or non-text variables
=> refactor: Use locale lowercase only in translations

packages/uikit/src/components/BottomNav/BottomNav.tsx
No need to use reduce that checks all the items
=> perf: (bottomnav): Use some instead of reduce

src/components/CurrencyInputPanel/index.tsx, src/components/RoiCalculatorModal/index.tsx, src/views/Pottery/components/WinRateModal/ButtonMenu.tsx
toLocaleUppercase uses locale of system default unless explicitly passed which results wrong conversion on some languages, therefore css text transform is better option
=> refactor: Use css text transform for uppercase instead of toLocaleUppercase

src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
When lp rewards apr is 0, it displays as minus zero because of the diff between display apr and apr has fractions
=> fix: Minus zero displayed in lp rewards apr in roi calculator in farms

src/views/Farms/components/FarmCard/FarmCard.tsx, src/views/Farms/components/FarmTable/Apr.tsx, src/views/Farms/components/FarmTable/FarmTable.tsx, src/views/Farms/components/FarmTable/Row.tsx, src/views/Farms/components/YieldBooster/components/BoostedApr.tsx, src/views/Migration/components/MigrationStep2/NewFarm/index.tsx
I am not sure on this but boosted apr should be calculated based on cake rewards apr not the total apr which includes lp rewards apr.
=> fix: Make Boosted Apr calculation based on cake rewards apr

src/views/TradingCompetition/EasterCompetition.tsx, src/views/TradingCompetition/FanTokenCompetition.tsx, src/views/TradingCompetition/MoDCompetition.tsx, src/views/TradingCompetition/MoboxCompetition.tsx, src/views/TradingCompetition/components/BattleCta/index.tsx, src/views/TradingCompetition/easter/components/YourScore/EasterYourScore.tsx, src/views/TradingCompetition/types.ts
Currently it blinks and shows the registration components depending on the users internet connection speed until it fetches the actual trading state.
To reproduce crash: 
1. Go to competition with registered account
2. Change to unregistered account
3. See it crashed
=> fix: (trading-competition): Crash when changing accounts, avoid flashing and set inital state statically

src/__tests__/views/predictions/components/History/helpers.test.ts, src/__tests__/views/predictions/helpers.test.ts, src/state/types.ts, src/views/Predictions/components/History/BetResult.tsx, src/views/Predictions/components/History/HistoricalBet.tsx, src/views/Predictions/components/History/PnlTab/PnlTab.tsx, src/views/Predictions/components/History/PnlTab/SummaryRow.tsx, src/views/Predictions/components/History/helpers.ts, src/views/Predictions/components/RoundCard/EnteredTag.tsx, src/views/Predictions/components/RoundCard/LiveRoundCard.tsx, src/views/Predictions/components/RoundCard/OpenRoundCard.tsx, src/views/Predictions/components/RoundResult/RoundResultHistory.tsx, src/views/Predictions/components/RoundResult/styles.tsx, src/views/Predictions/context/config.ts, src/views/Predictions/helpers.ts
Bet result history shows 3 digit decimals instead of 4
=> fix: Bet results history displayed decimal amount and make it configurable

packages/localization/src/config/translations.json, src/views/Swap/components/ConfirmSwapModal.tsx, src/views/Swap/components/SwapModalFooter.tsx, src/views/Swap/components/SwapModalHeader.tsx, src/views/Swap/index.tsx
To reproduce:
1. Go to swap
2. Try swap with exact output 
3. On swap modal if your input balance is lower than the amount of trade input after the price change, there is no indicator that your swap may fail.
Issue can happen slippage adjusted amount can exceed the token balance if slippage is set to very high. 
So in both cases we should warn the user but let user to decide whether to continue to swap or not
=> fix: Swap modal doesn't show insufficient input token info after price change

src/views/Predictions/Leaderboard/components/Filters/index.tsx
Net Winnings can't get token symbol when initializing, so change the sort sequence to solve this bug
fix #4544
=> fix(Prediction): Fix Leaderboard sort

src/state/farms/index.ts
To reproduce: 
Harvest any farm when multiple farms staked
See only the farm that is harvested userdata is available until the next userdata fetch
=> fix: (farms): Farms userdata reset after harvest until next fetch

packages/uikit/src/widgets/Modal/ModalContext.tsx
1. use latest version of `imToken` app.
2. open browser with https://pancakeswap.finance
3. click `trade` tab
4. click `token` 
**expected**
the token list modal opened
**now**
the token list not shown
https://user-images.githubusercontent.com/10740043/186350940-1361022b-f4bc-43dd-bf6e-e304f36a7c19.mov
the modal context will initialize the `--vh` css variable, but the handle function under `useEffect` scope which will not triggered after repaint. So the result of `window.innerHeight` will be `zero` or other some value in some device as the figure shows below.
for DOM measurement reason, should use `useLayoutEffect` to replace `useEffect`.
=> fix: modal context initial value

src/config/constants/priceHelperLps/farms/1.ts, src/config/constants/priceHelperLps/farms/5.ts, src/config/constants/priceHelperLps/farms/56.ts, src/config/constants/priceHelperLps/farms/97.ts, src/config/constants/priceHelperLps/index.ts, src/config/constants/priceHelperLps/pools/1.ts, src/config/constants/priceHelperLps/pools/5.ts, src/config/constants/priceHelperLps/pools/56.ts, src/config/constants/priceHelperLps/pools/97.ts, src/state/farms/index.ts, src/state/farmsV1/index.ts, src/state/pools/index.ts
Currently we fetch the price helper lps twice when in pools page
=> refactor: Separate price helper lps

packages/localization/src/config/translations.json, src/components/NetworkSwitcher.tsx, src/hooks/useSwitchNetwork.ts
Switch network will fail if user ignores the request from wallet and keep clicking it
Now just show an error toast whenever in catch error
=> feat: Add switch network error toast

src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
To reproduce:
1. Go to pools
2. Find a pool with staking limit with staked value
3. See when clicking max button it sets max staking limit on top of staked balance which results exceeding limit
4. See user balance shows staking limit wrongly if it is higher than that
=> fix: (pools): Stake modal max sets to wrong value and balance shows staking limit instead of user balance when there is limit 

src/state/farms/hooks.ts
User data loaded twice when first access to the page
=> perf: (farms): Don't fetch farm user data until proxy address fetched and dont fetch proxy farm data when proxy is not created

src/views/Farms/components/FarmCard/FarmCard.tsx
=> fix(Farm): CardView APR use tooltipText

.github/workflows/farmConfig.yml
It causes build of https://github.com/pancakeswap/pancake-frontend/pull/4723 to fail
=> fix: Changes on logic files cause pr to run farm config workflow

src/components/SearchModal/CurrencySearch.tsx
To review:
1. Go to currency search on swap
2. Type bnb on bsc chain
3. Press enter
4. It is expected to select native currency of the chain
=> fix: (currency-search): Currency search handle enter keyboard event for native currency of different chains

src/views/Farms/components/YieldBooster/hooks/useYieldBoosterState.ts
we had a logic return true for "shouldUseProxyFarm" while lock-end 
but there's a possibility that we created a proxy for the user and the user deposited it into the proxy contract
and then the lock cake expired, the user withdraw, and decide no lock anymore.
so there's a miss match for the origin code 
in this case, we still need to use the proxy contract not the MCv2 contract
=> chore: fix shouldUseProxyFarm issue

src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
It shows staking token balance in user account instead of staked balance when withdraw
=> fix: (pools): Balance in stake modal when withdraw

src/state/farms/hooks.ts
If the result is used in some hook that triggers a render too, then there will be infinite renders. 
This fix also reduces the call to the memoized selector since no new selector is created on each render.
=> fix: (farms): Memoize farm selector to avoid infinite rerenders

src/state/lists/hooks.ts, src/views/Swap/components/AccessRisk/RiskMessage.tsx, src/views/Swap/components/AccessRisk/index.tsx, src/views/Swap/components/SwapForm.tsx
It is easier for user to know risks of input token (especially for air-drops) without switching to output first
=> feat: (swap): Add scanning risks for input token

src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
The flexible cake contract did not have `withdrawByAmount` methods,
so will cause an error when the user did not withdraw all the amount.
=> fix: Flexible cake withdraw bug

src/components/GlobalCheckClaimStatus/index.tsx
Only check when chainId is BSC, if not other chain providers will error
=> perf: Global claim only run in BSC chain

src/components/GlobalCheckClaimStatus/index.tsx, src/hooks/useContract.ts
It happens when network change from eth to bsc
Uncaught (in promise) Error: underlying network changed (event="changed", network={"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, detectedNetwork={"name":"bnb","chainId":56,"ensAddress":null,"_defaultProvider":null}, code=NETWORK_ERROR, version=providers/5.6.8)
=> fix: Anniversary error when network change

src/config/constants/exchange.ts, src/hooks/useActiveWeb3React.ts, src/state/lists/updater.ts
To reproduce:
1. Go to a swap page that contains output&input currency params
http://pancakeswap.finance/swap?chainId=56&inputCurrency=0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82&outputCurrency=BNB
2. Change network
3. See default tokens of new network not get loaded correctly
=> fix: (swap): Query params from previous network causes to tokens to not get loaded

src/components/GlobalCheckClaimStatus/index.tsx
To reproduce:
1. Set wallet chain to bsc in wallet app
2. Access homepage via with chainId query https://pancakeswap.finance/?chainId=1
3. See error in console
=> fix: (anniversary): Anniversary check throws error when wallet network and page network is not the same

src/components/NetworkModal/PageNetworkSupportModal.tsx
To reproduce:
1. Switch network to bsc on wallet
2. Go to bsc only page with query id indicates wrong network such as https://pancakeswap.finance/nfts?chainId=1
3. See switch button in modal doesn't work
=> fix: Cannot switch network when accessing page via url with query

src/views/Pottery/components/FinishedRounds/AllHistoryCard/Winner.tsx
=> fix: (pottery): Winner row height in winners component when no profile

packages/uikit/src/components/TabMenu/TabMenu.tsx, packages/uikit/src/components/TabMenu/types.ts
=> fix(TabMenu): Tab active should highlight when active

package.json, src/views/Info/components/InfoCharts/BarChart/index.tsx, src/views/Info/components/InfoCharts/LineChart/index.tsx, src/views/Predictions/components/ChainlinkChart.tsx, src/views/Swap/components/Chart/SwapLineChart.tsx, yarn.lock
New version of recharts doesn't allow to use jsx component as a formatter in tooltip
To review:
Check swap, info and prediction chainlink charts
=> chore: Bump up recharts and remove hover updater

src/views/Info/Overview/index.tsx
some data from the subgraph is having high volume but the name is unknown
and trace it from BSCScan and found that the price is always 0 
we decide to filter this kinds of data
{
"derivedBNB": "0.0000000000000000005399776316480660036970204318",
"derivedUSD": "0.0000000000000001462857753025194595650165684457",
"id": "0x0cbac702884945d32c6fc2915973f7fe3b232861",
"name": "unknown",
"symbol": "unknown",
"totalLiquidity": "128253562332102915701",
"totalTransactions": "23078",
"tradeVolumeUSD": "29986571.04851145127928378612487"
},
{
"derivedBNB": "0.000000000000000000493639438629802371325083840195",
"derivedUSD": "0.0000000000000001337323062032550852673599219884",
"id": "0xeb6a3e241bf6bef35f22241d91e74604a65ade13",
"name": "unknown",
"symbol": "unknown",
"totalLiquidity": …
=> chore: filter unknown tokens and pools from top token and pools

src/views/Farms/components/YieldBooster/components/BoostedAction.tsx
To reproduce:
Go to farms
Boosted farms boost button not redirecting to pools when clicking outside of the text
=> fix: (farms): Boost button not fully clickable

src/state/block/hooks.ts, src/views/Swap/hooks/useRefreshBlockNumber.ts
Refresh button in swap pages doesn't work
Root cause is there is multiple swr hooks (useCurrentBlock, useChainCurrentBlock(depending on chainId is different than the wallet's) ) therefore when mutate function is called swr picks one of it (although both fetcher's should be undefined when wallet is in bsc network) because of the deduping interval and it never calls the actual fetcher. Making the fetcher hook with unique key solves the problem
=> fix: (swap): Refresh block number hook doesn't call the block number swr hook

package.json, yarn.lock
It contains a fix related to ssr https://github.com/glennreyes/react-countup/releases/tag/v6.3.2
=> chore: Bump up countup

apps/web/src/views/Swap/hooks/useWarningImport.tsx
To reproduce:
1. Set wallet network other than bsc and eth
2. Access http://pancakeswap.finance/swap directly
3. See behind the unsupported network modal there is import token modal and still appears after switching to correct network
=> fix: (swap): Import token modal appears if accessing swap page with unsupported network

apps/web/src/views/Ifos/components/IfoFoldableCard/index.tsx, apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
Since all cards using the same swr key there is a race condition between them when new block comes
To reproduce:
Go to ifo history
See ifo infos load takes time
=> fix: (ifo): Ifos data in history page fetch delaying and vesting information not updated on history page

apps/web/src/state/nftMarket/helpers.ts, apps/web/src/views/Nft/market/hooks/useGetCollectionDistribution.tsx
Check nft collection listing with all items and ordered by token id works properly.
=> perf: (nft): Don't use object entries to reduce memory footprint

apps/web/src/components/NetworkSwitcher.tsx
Appearing on the left will block other buttons, I think it should appear below
Before:
After:
=> chore(NetworkSwitcher): Change tooltip placement to bottom

apps/aptos/components/Pools/transformers/transformPool.ts
User first-time stake, `UserInfo` no have that type, so this cause we can't get the token balance.
=> fix: Aptos pool staking balance

apps/web/src/views/Pools/components/LockedPool/Common/LockDurationField.tsx, apps/web/src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx, apps/web/src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx, apps/web/src/views/Pools/components/LockedPool/types/index.ts, apps/web/src/views/Pools/components/Vault/VaultRoiCalculatorModal.tsx
To reproduce
1. Go to cake pool
2. Click extend
3. Click max
4. See it flickers because boost factor and apy counts up again
=> fix: (pools): Vault Extend modal flickers when max selected

apps/web/src/views/Pools/components/LockedPool/Common/ConvertToLock.tsx, apps/web/src/views/Pools/components/LockedPool/hooks/useAvgLockDuration.tsx
Root cause is avglockduration hook returns NaN (which we use that value in vault apr hook) when there is no public cake vault data. It happens on ifo more than pools page, since we fetch cake user data and cake public data at the same time there and there is a possibility that we have vault user data (which triggers to add convertlock component) but no public data
=> fix: Ifo and pools page crash intermittently when cake vault is in flexible mode

.changeset/neat-adults-brush.md, apps/aptos/state/lists/index.ts, apps/aptos/state/lists/updater.tsx, apps/web/src/state/lists/lists.ts, apps/web/src/state/lists/updater.ts, packages/token-lists/react/lists.ts, turbo.json
using another derived atom state to get the `EMPTY` state where it's not loaded from indexeddb yet to prevent fetch token list before it loads
=> fix(token-list): Not updating from indexeddb from version bump

apps/aptos/components/SearchModal/ManageLists.tsx
Link to `https://tokenlists.org/token-list` will show empty page.
We can just redirect to the token list url
=> perf(aptos): Token list external url

apps/web/src/__tests__/views/predictions/helpers.test.ts, apps/web/src/state/types.ts, apps/web/src/views/Predictions/components/RoundCard/EnteredTag.tsx, apps/web/src/views/Predictions/components/RoundCard/LiveRoundCard.tsx, apps/web/src/views/Predictions/components/RoundCard/OpenRoundCard.tsx, apps/web/src/views/Predictions/components/RoundResult/styles.tsx, apps/web/src/views/Predictions/context/config.ts, apps/web/src/views/Predictions/helpers.ts
When there is no bet Prize pool of open round shows <0.0010 instead of <0.0001. With this pr instead of using constant, min displayed price/amount calculation will be done dynamically based on decimals and displayedDecimals.
=> fix: (prediction): Min token displayed decimals is in wrong precision

apps/web/src/hooks/limitOrders/useGelatoLimitOrdersLib.ts, apps/web/src/hooks/useContract.ts, apps/web/src/hooks/useProviderOrSigner.ts, apps/web/src/utils/addressHelpers.ts, apps/web/src/utils/contractHelpers.ts, apps/web/src/views/AddLiquidity/index.tsx, apps/web/src/views/RemoveLiquidity/index.tsx
If user is in another chain than bsc, it uses contract address of bsc chain but uses the provider of active chain which results errors and mismatch requests. It also enables zap to be used with bsc testnet
=> fix: Contract errors when accessing bsc only supported page with another chain

apps/web/src/hooks/useApproveCallback.ts, packages/localization/src/config/translations.json
approve callback hook is also used in liquidity so it is better to use this error text when estimate gas failure
=> chore: Change error text for approve callback estimate gas

apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx, apps/web/src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
Instead of wbnb/weth it should be shown as bnb where farm has bnb/eth quotetoken or token, to be consistent with it is name shown in the list
=> chore: Show native symbol of token's of staked lp in farms staked component

package.json
recently the Cl had an error 
`Error: Cannot get farm config packages/tokens/src/helpers.ts(2,33): error TS2307: Cannot find module '@pancakeswap/token-lists' or its corresponding type declarations.`
=> fix: updateLPsAPR package deps issue

packages/uikit/src/hooks/useTooltip/useTooltip.tsx
To reproduce:
1. Go to farms in mobile
2. Tap apr to show tooltip
3. See action panel opens
=> fix: (tooltip): Tap to tooltip causes other elements to react

apps/web/src/state/pools/hooks.ts
To reproduce: 
1. Go to ifo with account
2. Change account from wallet
3. See it still shows previous account wallet data until the next interval
=> fix: (ifo): Trigger wallet data fetch when account change

.github/workflows/updateAptosLPsAPR.yml
Make sure the branch name won't be conflict while open PR
=> chore: update Aptos github action setting

apps/aptos/components/SearchModal/ManageTokens.tsx, apps/web/src/components/SearchModal/ManageTokens.tsx
Before:
After:
I think it's more intuitive to put the LinkExternalIcon next to the token.
=> style(TokenManage): Change LinkExternalIcon position

apps/web/src/views/Info/index.tsx
To reproduce: 
1. Try to access page without account
https://pancakeswap.finance/info/eth?type=stableSwap
2. Access page when account is connected to eth
https://pancakeswap.finance/info/eth/pairs?type=stableSwap
=> fix: (info): Info page shows wrong info when access stableswap page with different chain name

apps/web/src/components/ApproveConfirmButtons.tsx, apps/web/src/views/Pools/components/LockedPool/Common/BalanceField.tsx, apps/web/src/views/Pools/components/LockedPool/Common/ExtendEnable.tsx, apps/web/src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx, apps/web/src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx, apps/web/src/views/Pools/components/LockedPool/Modals/LockedStakeModal.tsx
Approve button when there is no cake allowance is missing in add/extend modals
=> feat: (pools): Add allowance approve button to lock modals

apps/web/src/views/AddLiquidity/components/ConfirmAddLiquidityModal.tsx
Add Liquidity confirm modal pair distribution chart currently based on amount which results one currency shown larger than the other on the chart 
To reproduce
1. Add liquidity
2. Select bnb and cake
3. Add amount to both
4. See chart in confirm modal
=> fix: (liquidity): Add liquidity pair distribution

apps/aptos/components/Pools/transformers/transformPool.ts
APR shows incorrectly for pairs with different decimals
=> fix(aptos-pool): Avoid APR mismatch for pairs with different decimals

apps/web/src/views/Nft/market/Collection/Items/Filters.tsx
The theme of filterButton should be unified.
Before:
After:
=> chore(NFT): Change filter theme

apps/bridge/package.json, apps/web/package.json, apps/web/src/config/wallet.ts, packages/wagmi/package.json, yarn.lock
It contains one breaking change 
`Breaking: The useSigner hook now always returns undefined when no signer is present. Previously, it returned null.`
which is ok since there is no explicit null check in codebase
It contains a fix which improves performance 
`Fixed an issue where useSigner would broadcast to other useSigners unnecessarily.`
=> chore: Bump up wagmi

apps/web/src/state/predictions/index.ts, apps/web/src/views/Predictions/components/RoundCard/SoonRoundCard.tsx, apps/web/src/views/Predictions/hooks/usePollPredictions.ts, apps/web/src/views/Predictions/index.tsx
It also reduces calls when first access. (currently when page is accessed it does initializepredictions then swr interval fetch prediction call). It is now refactored to use only interval fetch calls therefore when page is accessed it will only do that
=> fix: (prediction): Soon cards entry start time

apps/bridge/components/Menu.tsx
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>
Which is converted to
`<a><a></a></a>
`
=> fix(bridge): Menu item

apps/aptos/components/Pools/hooks/usePoolsList.ts, apps/aptos/components/Pools/transformers/transformPool.ts, apps/aptos/components/Pools/utils/getSecondsLeftFromNow.ts
To avoid user to see wrong pool and pending reward info when client/device time is wrong
=> fix: (pools): Use ledger timestamp for aptos pools instead of client timestamp

apps/web/src/views/Farms/components/YieldBooster/components/BCakeCalculator.tsx
Clicking "MY BALANCE" on a mobile device will be blocked by the tooltip, so I think it should be independent as a helpIcon.
Before:
After:
=> feat(BoosterROICalculator): Use the helpicon for the cake locked tooltip

apps/web/src/config/wallet.ts
When provider is undefined, it causes error
=> fix: Avoid undefined from provider

apps/aptos/utils/maxAmountSpend.ts
APT `currency?.isNative` always return false.
So when clicked max will not minus 0.02 APT, cause the error when swap native token to other token.
=> fix(Aptos): Max button on swap page

apps/aptos/pages/swap.tsx
To reproduce
Go to aptos exchange
Click pencil button next slippage tolerance
Close the modal with close button
See overlay still appears
=> fix: (aptos): Overlay still visible after closing the settings with button

apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx, packages/uikit/src/widgets/Farm/components/FarmCard/DetailsSection.tsx
I think the placement of ViewContract should be consistent with pools.
Before:
After:
=> chore(Farms): Adjust the placement of the ViewContract

apps/web/src/views/Pottery/components/Banner/index.tsx
=> fix(Pottery): Fix prize being cut on mobile

packages/uikit/src/widgets/Farm/components/FarmTabButtons.tsx, packages/uikit/src/widgets/Liquidity/AddLiquidity/ChoosePairView.tsx, packages/uikit/src/widgets/Liquidity/AprRow.tsx, packages/uikit/src/widgets/Liquidity/LiquidityCardHeader.tsx, packages/uikit/src/widgets/Liquidity/PercentSlider.tsx, packages/uikit/src/widgets/Pool/AprRowWithToolTip.tsx, packages/uikit/src/widgets/Pool/Cells/AprCell.tsx, packages/uikit/src/widgets/Pool/Cells/TotalStakedCell.tsx, packages/uikit/src/widgets/Pool/CollectModal.tsx, packages/uikit/src/widgets/Pool/PoolCard.tsx, packages/uikit/src/widgets/Pool/withCollectModal.tsx, packages/uikit/src/widgets/Pool/withStakeActions.tsx, packages/uikit/src/widgets/Swap/ExpertModal.tsx, packages/uikit/src/widgets/Swap/TradePrice.tsx
Using library instead of path can cause issues especially on dev builds
=> refactor: Use path instead of uikit library for all widgets

apps/aptos/views/Ifos/components/IfoFoldableCard/Timer.tsx
At present, aptos does not have the block time page, so Link should not be used, and it is better to use tooltip to display time instead.
=> feat(Aptos-IFO): StartTime and endTime use tooltip

packages/uikit/src/widgets/Swap/TradePrice.tsx
When swap from A to B, the default price display should also be A→B.
Before:
After:
=> chore(Swap): Change default price display

apps/aptos/components/Pools/hooks/usePoolsList.ts
When 'watch: true' used it tries to pool onchain data very frequently which some of the calls results in error if so many users trying to fetch therefore it shows the default value for userdata which is 0
=> fix: Aptos pool reset to 0

apps/aptos/components/Swap/AdvancedSwapDetails.tsx, apps/aptos/components/Swap/SwapModalFooter.tsx, apps/web/src/views/Swap/MMLinkPools/components/SwapModalFooter.tsx, apps/web/src/views/Swap/SmartSwap/components/SwapModalFooter.tsx, apps/web/src/views/Swap/StableSwap/components/StableSwapModalFooter.tsx, apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx, apps/web/src/views/Swap/components/SwapModalFooter.tsx
=> fix(Swap): Fix confirmSwap's tooltip placement on mobile

apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/ReleasedTokenInfo.tsx
=> fix(aptos-IFO): Fix vesting balance display decimals

apps/web/src/state/user/hooks/index.tsx, apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallback.ts
gasPrice return undefined, which block the Stake/Unstake farms on Ethereum flow
=> revert: "chore: Remove gas price on Ethereum (#6091)"

apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx, apps/web/src/views/Pools/components/MaxStakeRow.tsx, apps/web/src/views/Pools/components/PoolStatsInfo.tsx
=> feat(Pools): When two EndsBlock are the same, only one is displayed

apps/aptos/components/Menu/WalletModal.tsx, apps/web/src/components/Menu/UserMenu/WalletModal.tsx
Displaying Welcome here is not only strange but also blocks the tooltip.
=> chore(Wallet): No show "Welcome!"

apps/aptos/utils/index.ts
There is an extra '/' in the URL and return 403.
=> fix(aptos-exploreLink): Remove extra "/"

.changeset/unlucky-schools-compare.md, packages/token-lists/package.json, packages/token-lists/react/getTokenList.ts
`Failed to get list at url https://tokens.coingecko.com/uniswap/all.json Error: Token list failed validation: .tokens[2301].symbol should NOT be shorter than 1 characters; .tokens[2301].symbol should match pattern "^[a-zA-Z0-9+\-%/$.]+$";  should match "else" schema`
=> fix: Coingecko list cannot be loaded in eth

packages/farms/src/farmPrices.ts
- Remove BUSD assumption in quoteTokenUSD logic to support non-stablecoin pairs
=> fix(stableswap-farm): Correct LP USD price for non-stablecoin farms

apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
=> fix(aptos-Pools): Stake limit endTime

apps/web/src/views/Swap/MMLinkPools/components/ConfirmSwapModal.tsx
This will fix the issue "Confirm Popup displays although the users completed transaction"
=> fix: add txHash cache for mm confirm model

apps/aptos/state/user/phishingBanner.ts, apps/web/src/state/user/hooks/index.tsx
Phishing banner will affect phishing bot to detect our preview domain.
=> fix: Only show banner when domain is canonical

apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
=> fix(Farms): Fix BoostedActionPanel broken on mobile

apps/web/src/views/Predictions/Mobile.tsx
=> chore(Prediction): Modify ChainLink image placement on mobile

apps/web/src/views/Farms/Farms.tsx
It is multiplier is currently 0 therefore no hardcoded filter is needed
=> chore: Remove abnbc hardcoded farm filter

apps/web/src/views/Swap/MMLinkPools/hooks/useMMOrderBookTrade.ts
To reproduce: 
1. Fetch an mm trade
2. Go to settings 
3. Turn off mm linked pools
4. See mm trade is still there
=> fix: MM Trade cannot be turned off after fetched

apps/web/src/views/Nft/market/ActivityHistory/ActivityFilters.tsx, apps/web/src/views/Nft/market/Collection/Items/Filters.tsx
Displaying filter rows without wrapping onto a new line on mobile devices is a more user-friendly operation.
Before:
After:
=> chore(NFT): Filter row noWarp on mobile

apps/web/src/state/farms/index.ts
To reproduce: 
1. Go to farms
2. Click enable farm that is not approved
3. See after successful approval it still shows enable contract until the full fetch (which is every 60 seconds)
=> fix: (farms): Enable contract couldn't refresh view after approval

apps/web/src/pages/liquidity/[tokenId].tsx
1) Modify icon placement
2) Make time a part of the Link, so that users can click more easily
Before:
After:
=> chore(Liquidity): V3 history's timestamp improvement

packages/uikit/src/widgets/Pool/PoolTabButtons.tsx
The arrangement of filters in Pools should be the same as that in Farms.
Before:
After:
=> chore(Pools): Modifty filters placement

apps/web/src/views/Profile/components/EditProfileModal/StartView.tsx
When there is no CAKE in the wallet, the Enable flow for ChangeProfilePic will appear, causing users to mistakenly think that they need to Enable first before being able to RemoveProfilePic. Therefore, the marginTop of RemoveProfilePic has been increased.
Before:
After
=> chore(Profile): Modify ChangeProfilePicFlow margin

apps/web/src/state/swap/hooks.ts
seems like a tiny copy mistake. But can cause price charts not working when input and output tokens are only available on different subgraph instances (v2/v2/stable) for pricing.
=> fix: Wrong token address being used for price query

apps/web/src/state/transactions/updater.tsx
When multiple transaction happens in short period, it will try to fetch already fetching (retrying) transactions again since it doesnt have the receipt yet. Therefore duplicate receipts shown as toast
=> fix: Transaction updater duplicate receipts

packages/canonical-bridge/src/modules/wallet/BridgeWalletProvider.tsx, packages/canonical-bridge/src/views/index.tsx
=> perf: Memoize bridge props to avoid triggering effect logic on each render
