- src/state/profile/helpers.ts
To test: 
1. Go to nft activity and see profile avatars loading correctly
> perf: (profile): Reduce profile calls

- src/hooks/useSWRContract.ts
- src/views/Ifos/components/IfoSteps.tsx
- src/views/Pools/hooks/useApprove.tsx
- Add Enable Pool Button in IFO step
- Apply SWR for `useCheckVaultApprovalStatus` hook
> fix(ifo): check approval before showing stake in

- src/components/Menu/config/config.ts
- src/views/Home/components/Banners/IFOBanner.tsx
just in case we don't move ifo menu
> chore: Menu ifo live

- src/config/constants/farms.ts
- src/config/constants/pools.ts
Farm info:
LP address: 0x1Ce76390Dd210B9C9ae28373FDf79714206ECb73
LP Symbol: FROYO-BNB
Pool info:
Token address: 0xe369fec23380f9F14ffD07a1DC4b7c1a9fdD81c9 
Pool contract address: 0x1c9E3972fdBa29b40954Bb7594Da6611998F8830
Pool token rewards per block: 2.893
> feat(pool&farm): Add FROYO

- src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
- src/views/Ifos/components/IfoFoldableCard/index.tsx
- src/views/Ifos/hooks/useIfoApprove.ts
To reduce the traffic in wallet rpc nodes
> fix: (ifo): Use simple rpc provider to check ifo currency allowance of account

- src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
- src/views/PancakeSquad/components/Buttons/BuyTickets.tsx
Issue: 
After successful approval of cake spending from contribute modal, there is no feedback given to user.
To review:
https://deploy-preview-3087--pancakeswap-dev.netlify.app/
> fix: (ifo): Ifo contribute modal approve success toast is missing

- src/state/profile/helpers.ts
- src/views/Nft/market/Collection/Items/CollectionNfts.tsx
- src/views/Nft/market/hooks/useCompleteNft.tsx
To reproduce:
1. Go to nft collection items page
2. Intermittently one nft is failed to be fetched that causes to whole list to not be shown
> fix: (nft): Handle nft api error

- src/pages/nfts/profile/[accountAddress].tsx
- src/state/profile/hooks.ts
- src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/MainNFTCard.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/ManageNFTsCard.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/OwnerCard.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/ForSaleTableRows.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ManagePancakeBunniesCard.tsx
- src/views/Nft/market/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
- src/views/Nft/market/Profile/components/EditProfileModal/PauseProfileView.tsx
- src/views/Nft/market/Profile/components/EditProfileModal/index.tsx
- src/views/Nft/market/Profile/components/UserNfts.tsx
- src/views/Nft/market/Profile/index.tsx
- src/views/Nft/market/components/BuySellModals/SellModal/SellStage.tsx
- src/views/Nft/market/components/BuySellModals/SellModal/index.tsx
- src/views/Nft/market/components/ProfileNftModal.tsx
To reproduce:
1. Change profile picture
2. See picture not changed and user nfts not updated in profile page
We only need refresh profile trigger when in user profile page since profile data is fetched by useProfileByAddress hook instead of redux.
> fix: (profile): Handle edit profile update properly

- src/hooks/useApproveConfirmTransaction.tsx
- src/hooks/useSWRContract.ts
- src/state/nftMarket/hooks.ts
- src/utils/multicall.ts
- src/views/Nft/market/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
Avoid re-enabling NFT when re-selecting profile pic.
> fix(profile): Avoid re-enable for approval nfts

- src/views/Home/components/CakeDataRow.tsx
2 less calls if user doesn't go to bottom when visiting the home page
> perf: (home): Make request only when visible for cake token data component

- src/state/nftMarket/hooks.ts
- src/utils/constantObjects.ts
It will create infinite rerender if these data is used as useEffect dependency, unless we do stringify to JSON and use that which can be forgotten.
> fix: (hooks): Make default values constant to avoid infinite rerendering

- src/config/localization/translations.json
- src/views/Nft/market/Home/config.ts
- src/views/Nft/market/Home/index.tsx
you can't click to apply link, you can't copy apply link via right click. you shodl select + ctrl c, impossible for mobile users.
this link useless now
current:
updated:
please feel free yeet this request if it will integrate to *FoldableSection* via typescript (I can't🥺), thanks!
> feat(nft-market): Update FAQs + add Apply link

- scripts/updateLPsAPR.ts
Script fails when checking the format which requires empty line at the end of the file
> fix: (script): updateLPsAPR script

- src/views/Farms/components/DepositModal.tsx
To reproduce:
1. Go to farms
2. Click stake on farm
3. See infinite skeleton in 'Annual ROI at current rates:'
> fix: (farm): Annual roi calculation in deposit modal

- src/config/localization/translations.json
- src/views/Pools/index.tsx
Reverts pancakeswap/pancake-frontend#3185
> Revert "chore: Update text"

- src/config/localization/translations.json
- src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
> feat: (pools): Emergency withdraw option on stake modal

- src/views/FarmAuction/helpers.tsx
update outdated farm auction apply link:
old: https://docs.google.com/forms/d/e/1FAIpQLScUkwbsMWwg7L5jjGjEcmv6RsoCNhFDkV3xEpRu2KcJrr47Sw/viewform
new: https://docs.google.com/forms/d/e/1FAIpQLSfQNsAfh98SAfcqJKR3is2hdvMRdnvfd2F3Hql96vXHgIi3Bw/viewform
verify: https://docs.pancakeswap.finance/contact-us/business-partnerships
> chore(farm-auction): update auction apply link

- sentry.client.config.js
- sentry.server.config.js
Remove sentry performance check
> chore: Remove sentry txn trace

- src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx
> fix: (ifo): Ifo private sale tooltip li position

- src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardActions.tsx
- src/views/Ifos/hooks/v3/useGetWalletIfoData.ts
- src/views/Ifos/types.ts
Fix following bugs: 
- Should show Claim button when ineligible users need to claim
- Should not minus committed credit in Private Sale from IFO credits
- Should show Commit button in Live mode when user has not enabled the pool yet
> fix(ifo 3.1): Fix bugs in Live and Finished phases

- src/views/Ifos/index.tsx
- src/views/Nft/market/Collection/index.tsx
- src/views/TradingCompetition/index.tsx
1. Go to nft collection or ifo or trading competition
2. See page title missing in tab
> fix: (ifo nft) Fix missing page titles

- src/state/predictions/hooks.ts
- src/views/Predictions/components/Label.tsx
> fix(predictions): Prevent crash when missing currentRound

- src/config/constants/farms.ts
- src/config/constants/pools.tsx
Farm info:
LP address: 0x53a63ac301d6410915385294527f947aff616599
LP Symbol: ERA-BNB
Pool info:
Token address: 0x6f9F0c4ad9Af7EbD61Ac5A1D4e0F2227F7B0E5f9	
Pool contract address: 0x260F95f5b7FD8eda720ED9d0829164dE35B048ab
Pool token rewards per block: 1.608
> chore(pool&farm): Add ERA-BNB farm and pool

- src/config/constants/farms.ts
- src/config/constants/pools.tsx
Pool info:
Token address: 0x9fd87aefe02441b123c3c32466cd9db4c578618f	
Pool contract address: 0xD1D03A3D4C27884a8703Cdb78504737C9E9A159e
Pool token rewards per block: 0.1620
Start Block: https://bscscan.com/block/countdown/15363100
> chore(pool): Add new THG pool

- next.config.js
> chore: Allow Sentry sourcemap next file

- src/components/ClaimNftModal/ClaimNftModal.tsx
- src/components/GlobalCheckClaimStatus/AnniversaryAchievementModal.tsx
- src/components/Menu/UserMenu/WalletInfo.tsx
- src/components/Menu/UserMenu/WalletWrongNetwork.tsx
- src/components/SearchModal/CurrencySearchModal.tsx
- src/components/TransactionConfirmationModal/index.tsx
- src/views/FarmAuction/components/PlaceBidModal.tsx
- src/views/Farms/components/DepositModal.tsx
- src/views/Farms/components/WithdrawModal.tsx
- src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/ContributeModal.tsx
- src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
- src/views/Lottery/components/ClaimPrizesModal/index.tsx
- src/views/Nft/market/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
- src/views/Nft/market/Profile/components/EditProfileModal/PauseProfileView.tsx
- src/views/PancakeSquad/components/Buttons/Mint.tsx
- src/views/PancakeSquad/components/Modals/Confirm/index.tsx
- src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
- src/views/Pools/components/PoolCard/Modals/CollectModal.tsx
- src/views/Pools/components/PoolCard/Modals/StakeModal.tsx
- src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
- src/views/Predictions/components/ChartDisclaimer.tsx
- src/views/Swap/components/ImportTokenWarningModal.tsx
onDismiss is nullable so we have to check it before calling
> fix: Add null check to onDismiss before calling it

- src/components/Select/Select.tsx
- src/config/localization/translations.json
- src/state/nftMarket/hooks.ts
- src/views/Nft/market/Collections/index.tsx
To review:
1. Go to /nfts/collections page 
2. It uses collections cards in grid instead of table
> feat: (nft): New look for collections page

- src/pages/_document.tsx
> chore: Disable translate

- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/components/Menu/UserMenu/CopyAddress.tsx
- src/config/localization/translations.json
- src/utils/copyText.ts
> chore: Add eventId on ErrorBoundary

- src/views/Nft/market/Profile/components/EditProfileModal/ChangeProfilePicView.tsx
Fixed issues:
Fixes no nft warning in modal is shown after updating the profile picture 
Fixes no nft warning is shown in modal when inital load instead of skeleton
Fixes no nft warning not shown when nft wallet doesnt have nfts but has on sale or as profile picture
> fix: (profile): No Nft warning in Change profile modal

- src/components/CurrencyInputPanel/index.tsx
To review:
1. Go to swap page
3. Select token
4. See add to metamask icon next to the balance
> feat: Add add to metamask icon to swap page

- .github/workflows/lintPrTitle.yml
Add Lint PR. It should only work after merged
> ci: Add lint pr title

- src/config/localization/translations.json
- src/views/Voting/components/CastVoteModal/DetailsView.tsx
- src/views/Voting/components/CastVoteModal/index.tsx
- src/views/Voting/components/VoteDetailsModal.tsx
> feat: Make it clear that voting power includes CAKE before XX block

- .github/workflows/integrationTests.yml
- cypress.json
- cypress/integration/nfts/nfts.test.ts
- cypress/support/commands.js
- next.config.js
- package.json
- src/utils/graphql.ts
- src/views/Nft/market/Collections/index.tsx
- yarn.lock
Fix nft collection test, after https://github.com/pancakeswap/pancake-frontend/pull/3244
Cypress is unstable when accessing remote url. 
Add retry and ignore info test temporally
> ci: Cypress test vercel preview link 

- .github/workflows/integrationTests.yml
Looks like deployement_status is not working well with forked PR
> revert: Cypress vercel

- src/config/localization/translations.json
- src/hooks/useParsedQueryString.ts
- src/hooks/useSwapCallArguments.ts
- src/hooks/useSwapCallback.ts
- src/state/mint/hooks.ts
- src/state/swap/hooks.ts
Handle swap error message fix PAN-222
Remove useParsedQueryString fix PAN-227
Handle getLiquidityMinted Error fix PAN-220
> feat(swap): Error message and handle

- .github/.kodiak.toml
Add Kodiak to help auto merge and keep PR update when ready
> chore: Add kodiak

- src/components/Tags.tsx
- src/config/localization/translations.json
- src/views/Farms/components/FarmCard/CardHeading.tsx
- src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
- src/views/Voting/components/Proposals/tags.tsx
> chore: Add tooltip for community farms and reword

- src/pages/voting/proposal/[id].tsx
- src/views/Voting/Proposal/Overview.tsx
When snapshot api is not stable, some CORS issue. we should handle it properly
> fix(voting): Handle voting error when api is not stable

- src/config/constants/farms.ts
- src/config/constants/pools.tsx
Farm info:
pid 491	HIGH-BUSD
Pool info:
Token address: 0x5f4bde007dc06b867f86ebfe4802e34a1ffeed63	
Pool contract address: 0x60c4998C058BaC8042712B54E7e43b892Ab0B0c4
Pool token rewards per block: 0.09756
Start Block: https://bscscan.com/block/countdown/15563970
> chore(pool): Add HIGH pool

- src/config/abi/sousChefV2.json
- src/config/localization/translations.json
- src/state/pools/fetchPools.ts
- src/state/pools/helpers.ts
- src/state/pools/index.ts
- src/state/types.ts
- src/views/Pools/components/MaxStakeRow.tsx
- src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx
- src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
> feat: (pool): Add max stake limit ends block countdown

- src/state/voting/helpers.ts
related #3341 
Showing closed proposals order by recently end makes more sense
> fix(voting): Closed proposals orderDirection

- src/config/constants/tokenLists/pancake-default.tokenlist.json
Update default list logo uri to match checksummed because of vercel policy
> fix: Default list token logo checksum

- src/hooks/useSwapCallback.ts
> fix: Error message from estimatedCalls missing

- src/components/CopyButton/index.tsx
- src/components/CurrencyInputPanel/index.tsx
- src/components/Menu/UserMenu/CopyAddress.tsx
To review 
1. Go to swap
2. Select token from list
3. See copy address button
> feat: Add copy token address button to currency input panel

- src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx
- src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
Max stake per user still shown if pool is finished earlier than usual
> fix: Max stake per user shown when pool is finished

- src/hooks/useIntersectionObserver.ts
> fix: Check IntersectionObserver 

- src/views/Ifos/components/IfoPoolVaultCard.tsx
- src/views/Pools/components/AutoEarningsBreakdown.tsx
- src/views/Pools/components/CakeVaultCard/RecentCakeProfitBalance.tsx
- src/views/Pools/components/CakeVaultCard/RecentCakeProfitRow.tsx
- src/views/Pools/components/CakeVaultCard/index.tsx
- src/views/Pools/components/PoolsTable/Cells/AutoEarningsCell.tsx
To review:
1. Go to pool cards
2. See tooltip of recent cake profit value  has auto earnings interest breakdown like pool table rows
> feat: (pool): Add auto earnings interest breakdown to pool cards

- package.json
- packages/uikit/src/widgets/WalletModal/config.tsx
- packages/uikit/src/widgets/WalletModal/types.ts
- src/components/Menu/UserMenu/WalletWrongNetwork.tsx
- src/hooks/useAuth.ts
- src/react-app-env.d.ts
- src/utils/wallet.ts
- src/utils/web3React.ts
- yarn.lock
Close https://github.com/pancakeswap/pancake-frontend/pull/2767
> feat: Add Coinbase Wallet and Blocto Wallet

- packages/uikit/src/hooks/useMatchBreakpoints.ts
> fix: Avoid undefined call matchMedia

- src/contexts/ToastsContext/Provider.tsx
- src/hooks/useAuth.ts
- src/hooks/useEagerConnect.ts
- src/utils/wallet.ts
- src/utils/web3React.ts
Since we already have Wrong Network Indicator https://github.com/pancakeswap/pancake-frontend/pull/3179
We don't need to keep asking for `setupNetwork` each time when navigating the pages.
> feat: Only attempt to setup network once

- src/components/CurrencyInputPanel/index.tsx
small UX improve the focus area should be the whole input panel 
https://user-images.githubusercontent.com/94336009/156696367-58693c23-141e-4872-af6d-703c1bbc3796.mp4
> feat(swap): Pass focus when clicking currency input panel

- next.config.js
- src/hooks/useSessionStorage.ts
- src/views/Voting/components/Proposals/Proposals.tsx
Save proposals filter in session storage manage to keep the selection between navigation
> feat(voting): Proposals filter in session

- src/state/farms/index.ts
- src/state/global/actions.ts
- src/state/index.ts
- src/state/pools/index.ts
- src/utils/clearUserStates.ts
After logout redux still contains userdata from previous account
To reproduce:
1. Go to farms
2. Connect account
3. See harvest amount on farms
4. Logout
5. Harvest amount still visible
> fix: Remove user data from farms and pools after logout

- src/hooks/useEagerConnect.ts
Not gonna dive in why web3-react has stale connection on local. just setTimeout to throw login to event loop
https://github.com/NoahZinsmeister/web3-react/blob/v6/packages/core/src/manager.ts#L141-L143
> fix(wallet): Local injected eager connect

- packages/eslint-config/lib/index.js
- packages/uikit/src/components/CakePrice/CakePrice.tsx
- packages/uikit/src/widgets/Menu/Menu.tsx
- src/components/ConnectWalletButton.tsx
- src/components/Menu/UserMenu/index.tsx
- src/config/localization/translations.json
- src/hooks/useSWRContract.ts
- src/state/profile/helpers.ts
- src/state/profile/hooks.ts
- src/views/PancakeSquad/components/Header/index.tsx
- Improve RWD on user menu
- localstroage cache profile: Add `localStorageMiddleware` for save key in swr. Use it in caution though
> feat: UserMenu improve

- package.json
- src/state/types.ts
- src/state/voting/helpers.ts
- src/views/Voting/Proposal/Overview.tsx
- src/views/Voting/Proposal/Results.tsx
- src/views/Voting/Proposal/Votes.tsx
- src/views/Voting/helpers.ts
- yarn.lock
Remove snapshot.js, we only use getScores that is just a fetch api function
> perf(voting): Remove snapshot.js

- package.json
- packages/uikit/package.json
- packages/uikit/src/widgets/Modal/ModalContext.tsx
- yarn.lock
https://user-images.githubusercontent.com/99634186/157085989-a2b6a76e-27bc-43dd-a733-14a44d5709fa.mp4
https://user-images.githubusercontent.com/99634186/157089224-e66c69d2-7d16-4133-bea1-c76a851555dc.mp4
> chore: Add transition for UIKit Modal

- src/state/pools/selectors.ts
Currently pools selectors not memoize correctly
> fix: Pools selectors memoization

- .env.development
Reverts pancakeswap/pancake-frontend#3320
> revert: Revert "chore: Use Public rpc on dev"

- src/components/SearchModal/ImportRow.tsx
> fix: Select token mobile css

- src/state/lists/updater.ts
> perf: Token list remove useless code

- src/state/farms/hooks.ts
- src/state/farms/selectors.ts
Thanks @chefilip that gave me the idea on pools, now I applied that to farms
> perf: Use selectors for farms

- src/views/Home/components/Banners/MultipleBanner.tsx
https://user-images.githubusercontent.com/2213635/157502567-480cdae1-e130-4a1a-97a1-b60b269bcb18.mov
> fix: Multiple banner still shows fade effect when only one item

- packages/uikit/src/widgets/Modal/ModalContext.tsx
Modal animation performance optimization 
for biiiiiiiiiig token list in CurrencySearchModal
> perf: Modal animation performance optimization

- src/components/SearchModal/CommonBases.tsx
- src/views/AddLiquidity/ConfirmAddModalBottom.tsx
- src/views/Swap/components/ConfirmRemoveLiquidityModal.tsx
> fix: Liquidity page css

- src/config/localization/translations.json
- src/views/Voting/components/CastVoteModal/MainView.tsx
- src/views/Voting/components/CastVoteModal/index.tsx
- src/views/Voting/hooks/useGetVotingPower.tsx
> chore: Handle Error on getting vote power

- src/state/pools/selectors.ts
Currently selector combiner is called everytime something changes in ifo pool
> refactor: Ifo user credit selector

- src/utils/localStorageOrders.ts
- src/views/LimitOrders/components/LimitOrderTable/index.tsx
- src/views/LimitOrders/hooks/useFormattedOrderData.ts
- src/views/LimitOrders/hooks/useGelatoLitmitOrdersHistory.ts
- src/views/LimitOrders/types.ts
Revert Limit Order fix because some unstable behaviours
> revert: Order still visible after executed 

- src/state/index.ts
> fix: Redux migration

- cypress/integration/exchange/liquidity.test.ts
> test(cypress): Tmp increase pool timeout

- src/components/Menu/config/config.ts
> chore: Update IFO Live

- src/config/constants/farms.ts
- src/config/constants/pools.tsx
Farm info:
LP address: 0xbDF0aA1D1985Caa357A6aC6661D838DA8691c569
LP Symbol: DUET-CAKE
Pool info:
Token address: 0x95EE03e1e2C5c4877f9A298F1C0D6c98698FAB7B	
Pool contract address: 0xA581349F26dE887700045F9B7d148775d422fDA2
Pool token rewards per block: 0.4861
> chore(earn): Add Duet farm and pool

- src/config/constants/lists.ts
- src/config/localization/translations.json
- src/views/Home/components/Banners/IFOBanner.tsx
- src/views/Home/components/Banners/LotteryBanner.tsx
- src/views/Home/components/Banners/Styled.tsx
add text-shadow and adjustment for text format
> chore: Details of banner UI

- src/state/nftMarket/helpers.ts
> fix: Prevent TypeError in Nft Collection

- src/components/Menu/config/config.ts
- src/components/Menu/index.tsx
- src/hooks/useMenuItems.ts
- src/hooks/useMenuItemsStatus.ts
- src/views/Home/components/Banners/hooks/useIsRenderIFOBanner.tsx
Feature for Menu item tags (currently for ifo only) to be placed automatically based on component status
> feat: Dynamic status tags for menu items

- src/config/constants/ifo.ts
Current articleURL forwards to proposal is voted NO (old one)
old one: https://pancakeswap.finance/voting/proposal/QmPdotYCM5cz8hYY1NEa3CvxK2xHBZJRYehWCbWVqqKGrY
new one: https://pancakeswap.finance/voting/proposal/QmXwoYYd8rkahVbxiGKsTa4rYRRFWPxhRGAHy3hVwK3Q2z
verify: https://twitter.com/PancakeSwap/status/1500010724499734532
> chore:(ifo): Update DUET ifo's articleUrl

- src/state/farms/fetchFarms.ts
- src/state/farms/selectors.ts
- src/state/types.ts
- src/views/Farms/Farms.tsx
- src/views/Farms/components/FarmCard/CardActionsContainer.tsx
- src/views/Farms/components/FarmCard/FarmCard.tsx
- src/views/Farms/components/FarmCard/StakeAction.tsx
- src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
- src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx
- src/views/Farms/components/FarmTable/Actions/StakedAction.tsx
- src/views/Farms/components/FarmTable/Row.tsx
- src/views/Farms/components/StakedLP.tsx
- src/views/Farms/components/types.ts
- src/views/Home/hooks/useGetTopFarmsByApr.tsx
> feat: (farms): Show token amounts inside LP

- src/views/Lottery/components/PreviousRoundCard/Body.tsx
> fix: Prevent undefined TypeError in lottery

- src/state/nftMarket/helpers.ts
- src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
- src/views/Nft/market/Collection/Traits/PancakeBunniesTraits.tsx
- src/views/Nft/market/Collections/index.tsx
- src/views/Nft/market/hooks/useCollectionNfts.tsx
> fix: Avoid totalSupply undefined

- src/state/nftMarket/hooks.ts
- src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/MainNFTCard.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/ManageNFTsCard.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ManagePancakeBunniesCard.tsx
- src/views/Nft/market/Collection/Items/PancakeBunniesCollectionNfts.tsx
- src/views/Nft/market/Profile/components/UnconnectedProfileNfts.tsx
- src/views/Nft/market/Profile/components/UserNfts.tsx
- src/views/Nft/market/components/Activity/ActivityRow.tsx
- src/views/Nft/market/components/Activity/MobileModal.tsx
- src/views/Nft/market/components/BuySellModals/BuyModal/ReviewStage.tsx
- src/views/Nft/market/components/BuySellModals/SellModal/EditStage.tsx
- src/views/Nft/market/components/BuySellModals/SellModal/SellStage.tsx
- src/views/Nft/market/components/BuySellModals/SellModal/TransferStage.tsx
- src/views/Nft/market/components/CollectibleCard/CardBody.tsx
- src/views/Nft/market/components/ProfileNftModal.tsx
> fix: Avoid sentry undefined collectionName

- src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/MainNFTCard.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/ManageNFTsCard.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/OwnerCard.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ForSaleTableCard/ForSaleTableRows.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/MainPancakeBunnyCard.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/ManagePancakeBunniesCard.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/shared/MoreFromThisCollection.tsx
- src/views/Nft/market/Collection/Items/CollectionNfts.tsx
- src/views/Nft/market/Home/Newest.tsx
- src/views/Nft/market/Profile/components/UnconnectedProfileNfts.tsx
- src/views/Nft/market/Profile/components/UserNfts.tsx
- src/views/Nft/market/components/BuySellModals/BuyModal/index.tsx
- src/views/Nft/market/components/BuySellModals/SellModal/EditStage.tsx
- src/views/Nft/market/components/BuySellModals/SellModal/index.tsx
> fix: Avoid TypeError undefined marketData.currentAskPrice

- packages/uikit/src/widgets/Modal/ModalContext.tsx
Thanks for @ChefMomota  to finding this case and reporting this transition issue to me 
when two modals are continuously opened, there's a transition bug.
> fix: Modal transition issue

- src/components/SearchModal/CurrencySearch.tsx
> fix: Token list sorting ref

- src/state/lottery/helpers.ts
- src/state/lottery/hooks.ts
- src/state/lottery/selectors.ts
Reduces rerenders significantly
> refactor: (lottery): Use memoized selectors in lottery hooks

- next.config.js
- src/components/ErrorBoundary/ErrorBoundary.tsx
- tsconfig.json
> chore: Try enable sourcemap

- packages/uikit/src/components/Image/BackgroundImage.tsx
- packages/uikit/src/hooks/useMatchBreakpoints.ts
> chore: Avoid matchMedia not function error

- src/state/lists/hooks.ts
To reproduce: 
1. Go to swap
2. Open token search
3. Search any token
4. See initial token search freezes the app for a couple of second
> fix: (swap): Initial token search freezes the app couple of second

- src/views/Nft/market/ActivityHistory/ActivityFilters.tsx
- src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
> fix: Fix address undefined TypeError

- src/views/Predictions/components/Label.tsx
> fix: Avoid null TypeError null

- src/views/Nft/market/Collection/Items/CollectionNfts.tsx
> fix: Avoid collection.address error

- packages/uikit/src/components/Image/Image.tsx
> chore: Fix IntersectionObserver

- src/hooks/useEagerConnect.ts
> fix: Avoid getItem undefined error

- src/state/lists/hooks.ts
> fix: Avoid Object.fromEntries error

- src/views/Nft/market/Collection/Items/CollectionWrapper.tsx
- src/views/Nft/market/Collection/Items/Filters.tsx
> fix: Avoid address undefined in nft

- src/state/lottery/index.ts
> fix: Avoid tickets.map undefined

- src/hooks/useAuth.ts
- src/hooks/useEagerConnect.ts
- src/utils/clearUserStates.ts
> fix: Avoid localstorage null called

- src/hooks/useSWRContract.ts
> chore: Avoid getItem null

- src/hooks/usePairs.ts
> chore: Add debug for Pair.getAddress

- src/state/lottery/hooks.ts
- src/views/Home/components/Banners/hooks/useIsRenderLotteryBanner.tsx
To reduce calls when accessing home page
> perf: Fetch public data only for lottery banner

- packages/uikit/src/components/Card/CardRibbon.tsx
- packages/uikit/src/theme/base.ts
- packages/uikit/src/theme/types.ts
Since types have been defined for theme values. We should enforce this by using these types
> chore: Add types for base in theme

- src/views/Ifos/components/IfoContainer.tsx
was no any apply or docs link in whole page,  added. 
href: https://docs.pancakeswap.finance/contact-us/business-partnerships#ifos-token-sales
> style(ifo): Add "Apply to run an IFO!"

- src/views/Ifos/components/IfoFoldableCard/Achievement.tsx
+add a redirect icon by pulling the site url from `ifo.token.projectLink` 
+new icon for bscscan link
+reorder
before:
after:
> style(ifo): Update links related to the IFO project

- src/config/constants/snapshot.ts
- src/views/Voting/helpers.ts
super quick fix where snapshot api now limit to 8 strategies per request
> fix: Hot fix snapshot limit 8 strategies

- src/views/Voting/helpers.ts
> fix: Also fix cakeBnbLpBalance

- src/views/Voting/helpers.ts
> fix(voting): Pool balance acc

- src/config/constants/farms.ts
- src/config/constants/pools.tsx
Farm info:
LP address: 0x1ccc3cc95c8148477afd18a552f03835be9d182a
LP Symbol: FROYO-CAKE
Pool info:
Token address: 0xe369fec23380f9F14ffD07a1DC4b7c1a9fdD81c9	
Pool contract address: 0x84e3208578eE7db397a3d584d97Fea107b15bF35
Pool token rewards per block: 3.404
Start Block: https://bscscan.com/block/countdown/16363420
> feat: List FROYO

- packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
> chore: Avoid getItem called from undefined

- src/state/lottery/hooks.ts
- src/state/lottery/selectors.ts
- src/views/Lottery/components/ViewTicketsModal/PreviousRoundTicketsInner.tsx
> chore: Avoid totalTickets undefined

- src/contexts/Localization/Provider.tsx
Thanks @chefilip for this suggestion
> refactor: (translation): Use memoize for translation regex check

- src/utils/truncateHash.ts
> fix: Avoid truncateHash throw null error

- src/views/Farms/components/DepositModal.tsx
- src/views/Farms/components/WithdrawModal.tsx
> feat: Add farm modal button animation

- packages/uikit/src/hooks/useTooltip/StyledTooltip.tsx
- packages/uikit/src/hooks/useTooltip/useTooltip.tsx
> chore: Add transition for useTooltip

- src/views/Home/components/Banners/LotteryBanner.tsx
- src/views/Home/components/Banners/MultipleBanner.tsx
- src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
To fix the blinking issue swiper observer is used.
> fix: (lottery banner): Missing current lottery fetch causes banner always shows preparing

- src/views/Farms/components/FarmTable/Farm.tsx
> style: Farm token width set to 32px

- next.config.js
> chore(sentry): Clean up release setup

- packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
- packages/uikit/src/widgets/WalletModal/WalletCard.tsx
- packages/uikit/src/widgets/WalletModal/config.tsx
- packages/uikit/src/widgets/WalletModal/types.ts
- src/hooks/useEagerConnect.ts
- deeplink metamask, or go to metamask website as fallback
- try eager connect with injected first time
> feat(wallet): Deeplink metamask

- src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
Merge it after Trading Competition end.
> chore: Turn off trading competition banner

- src/components/Menu/config/config.ts
Merge it after Trading Competition end.
> chore: Trading competition menu remove live status

- src/hooks/limitOrders/useGasOverhead.ts
> chore: Avoid undefined error in limit order

- src/__tests__/utils/apr.test.ts
- src/state/farms/fetchMasterChefData.ts
- src/state/farms/index.ts
- src/state/farms/selectors.ts
- src/state/types.ts
- src/utils/apr.ts
- src/views/Farms/Farms.tsx
- src/views/Home/hooks/useGetTopFarmsByApr.tsx
- src/views/Migration/components/MigrationStep1/OldFarm/index.tsx
- src/views/Migration/components/MigrationStep2/NewFarm/index.tsx
Get regular cakePerBlock from SC
> feat: Get regular cake per block from sc

- packages/uikit/src/components/Skeleton/Skeleton.tsx
- packages/uikit/src/components/Skeleton/index.stories.tsx
- packages/uikit/src/components/Skeleton/types.ts
- packages/uikit/src/index.ts
- packages/uikit/src/util/animationToolkit.ts
- packages/uikit/src/widgets/Modal/ModalContext.tsx
- src/views/Home/components/Banners/MultipleBanner.tsx
> feat: skeleton with transition

- packages/uikit/src/components/Dropdown/Dropdown.tsx
In mobile especially smaller screen size phones when scrolling down language dropdown appears. 
https://user-images.githubusercontent.com/2213635/164975427-f7c3f3ee-6838-4786-ad93-ffcfbfd7029b.mp4
> fix: Language selector dropdown appears when scrolling in mobile

- src/config/localization/translations.json
- src/views/Pools/components/LockedPool/Common/Overview/BalanceRow.tsx
- src/views/Pools/components/LockedPool/Common/Overview/DateRow.tsx
- src/views/Pools/components/LockedPool/Common/Overview/index.tsx
- src/views/Pools/components/LockedPool/LockedStakingApy.tsx
https://user-images.githubusercontent.com/98292246/165025302-74328f01-2464-43bd-8bad-657c14dd3a8c.mov
> feat: Add tooltips at Pool card & Lock Modal

- src/config/localization/translations.json
- src/views/Voting/components/CastVoteModal/DetailsView.tsx
- src/views/Voting/helpers.ts
- src/views/Voting/hooks/useGetVotingPower.tsx
Improve voting display, some balances become invalid, show them depends on the value exist
> fix(voting): Improve voting display after migration

- packages/uikit/src/components/Dropdown/Dropdown.tsx
Sometimes language dropdown appears when tapping its potential visible area in mobile.
> fix: Language Dropdown appears intermittently when tapping its potential visible area

- packages/uikit/src/components/Dropdown/Dropdown.tsx
Thanks @chefilip for the inspection
> fix: Dropdown props dom warning 

- src/config/localization/translations.json
- src/hooks/useVaultApy.ts
- src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx
- src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
- src/views/Pools/components/Stat.tsx
> feat(locked-pool): Add Average lock duration

- src/views/Farms/components/FarmCard/FarmCard.tsx
- src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
- src/views/Farms/components/FarmTable/FarmTable.tsx
- src/views/Farms/components/FarmTable/Row.tsx
- src/views/Pools/components/PoolCard/StyledCard.tsx
Before:
After:
Before:
After:
Before:
After:
> style: Farms Card & Table view

- src/config/localization/translations.json
- src/views/Pools/components/CakeVaultCard/VaultCardActions/HasSharesActions.tsx
- src/views/Pools/components/CakeVaultCard/VaultStakeModal.tsx
- src/views/Pools/components/LockedPool/Common/ConvertToLock.tsx
- src/views/Pools/components/LockedPool/hooks/useAvgLockDuration.tsx
- src/views/Pools/components/PoolCard/CardFooter/ExpandedFooter.tsx
- src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
- src/views/Pools/components/Stat.tsx
> feat(locked-pool): Add Convert To Lock note

- src/config/constants/farms.ts
- src/config/constants/pools.tsx
RPG token Address we added before.
Farm info:
LP address: 0x55cdb14855220b239cf857a03849d96736b9103f
LP Symbol: RPG-BUSD
Pool info:
Token address: 0xc2098a8938119A52B1F7661893c0153A6CB116d5	
Pool contract address: 0xD1c395BCdC2d64ac6544A34A36185483B00530a1
Pool token rewards per block: 0.06794
Start Block: https://bscscan.com/block/countdown/17366040
> feat: List RPG farm and pool

- src/config/localization/translations.json
- src/views/Pools/components/LockedPool/Common/LockedModalBody.tsx
- src/views/Pools/components/LockedPool/Common/Overview/index.tsx
- src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx
- src/views/Pools/components/LockedPool/types/index.ts
> chore(lock-pool): Add withdraw warning

- src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx
- src/views/Pools/components/PoolsTable/ActionPanel/Stake.tsx
- src/views/Pools/components/PoolsTable/ActionPanel/styles.ts
> fix: Excessive space in pool table stake component

- src/views/Pools/components/PoolCard/CardFooter/index.tsx
- src/views/Pools/components/PoolStatsInfo.tsx
- src/views/Pools/components/PoolsTable/ActionPanel/ActionPanel.tsx
- src/views/Pools/components/PoolsTable/ActionPanel/CakeVaultApr.tsx
- src/views/Pools/components/Stat.tsx
- src/views/Pools/components/Vault/VaultPositionTag.tsx
To reproduce: 
1. Go to pools table
2. Expand cake pool
3. See total locked info not visible
> fix: Total locked info not visible in pools table

- src/state/nftMarket/helpers.ts
- src/state/nftMarket/types.ts
- src/views/Nft/market/Profile/utils/sortUserActivity.tsx
UserNftInitializationState is a leftover from redux
> refactor: (nft) Use userActivity interface and remove UserNftInitializationState

- src/state/pools/index.ts
It reduces user data execution time from ~3s to ~1s
> perf: Use promise all to reduce execution time of pools user data fetch

- src/state/pools/index.ts
It reduces public pools data fetch execution time from ~1s to ~500ms
> perf: Use promise all to reduce execution time of pools public data fetch

- src/views/Nft/market/ActivityHistory/ActivityFilter.tsx
- src/views/Nft/market/ActivityHistory/ActivityFilters.tsx
- src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
- src/views/Nft/market/ActivityHistory/ClearAllButton.tsx
- src/views/Nft/market/components/Filters/ListFilter/styles.tsx
https://linear.app/pancakeswap/issue/PAN-466/fix-nft-activity-css
> fix: NFT activity page layout issue

- src/hooks/useLast.ts
It contains function therefore it should be done once
> refactor: Make initial state calculation once in useLast hook

- src/views/Voting/CreateProposal/index.tsx
It contains map call therefore it should be done once
> refactor: (voting): Make create proposal initial state run once

- src/views/Info/components/CurrencyLogo/index.tsx
> chore: Update trust wallet logo asset url

- src/views/Nft/market/hooks/useAllPancakeBunnyNfts.ts
To review
1. Go to https://web-git-fork-memoyil-feature-perfusepromiseallpancakebunnynfts.pancake.run/nfts/collections/0xDf7952B35f24aCF7fC0487D01c8d5690a60DBa07
2. Check lowest prices and order by recently listed works properly
> perf: Use promise all when fetching pb all nfts

- src/views/Predictions/Desktop.tsx
- src/views/Predictions/components/History/PnlTab/PnlChart.tsx
- src/views/Predictions/components/History/PnlTab/PnlTab.tsx
- src/views/Predictions/components/History/PnlTab/SummaryRow.tsx
Before:
<br>
After:
https://user-images.githubusercontent.com/98292246/168741283-e9928c9e-1294-4b0b-9281-45f6e85314c9.mov
> fix: Prediction page UI

- src/views/Pools/components/LockedPool/Common/BalanceField.tsx
https://user-images.githubusercontent.com/98292246/168784066-518878e9-e80a-48fc-a487-34d8a5c8a554.mov
> fix: Cake Pool slider reset after ROI

- src/state/farms/fetchFarmsWithAuctions.ts
Reverts pancakeswap/pancake-frontend#3956
> revert(farms): Keep auction label after end

- packages/uikit/src/components/Svg/Icons/Opera.tsx
- packages/uikit/src/components/Svg/index.tsx
- packages/uikit/src/react-app-env.d.ts
- packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
- packages/uikit/src/widgets/WalletModal/WalletCard.tsx
- packages/uikit/src/widgets/WalletModal/config.tsx
- packages/uikit/src/widgets/WalletModal/types.ts
- src/hooks/useEagerConnect.ts
- src/react-app-env.d.ts
Update priority can be function,
prioritize wallet if condition met
> feat(wallet): Add Opera option

- package.json
- yarn.lock
It mainly contains minor fixes
https://github.com/nolimits4web/swiper/commits/master
> chore: Bump up swiper

- package.json
- yarn.lock
https://github.com/pacocoursey/next-themes/releases/tag/v0.2.0
> chore: Bump up next themes

- src/views/Home/components/WinSection/PredictionCardContent.tsx
> perf: (prediction-card): Fetch bnb price only when visible on home page

- src/components/SearchModal/CurrencySearch.tsx
- src/components/SearchModal/filtering.ts
To reproduce: 
1. Go to swap -> currency search
2. Search luna
3. See token is not on the top of the inactive token list even it is exactly matched
> fix: (currency-search): Exact matched tokens not on top in currency search

- src/views/Home/components/WinSection/LotteryCardContent.tsx
We already have the calls in lottery banner, so lottery card can show the content without making any additional requests
> perf: Reduce lottery card content calls

- src/config/constants/campaigns.ts
Add campaign ids for MoD trading competition
> feat: Add MoD TC campaign ids

- packages/uikit/src/components/BottomNav/BottomNav.tsx
- packages/uikit/src/components/MenuItems/MenuItems.tsx
To avoid rerenders triggered by usePollCoreFarmData hook with fastrefresh
> perf: Memoize menu items

- src/components/SearchModal/CurrencySearch.tsx
> fix: Avoid flashing when searching token by address

- src/config/constants/types.ts
- src/views/Nft/market/Home/Newest.tsx
> refactor: Remove redundant div block

- src/config/constants/farms.ts
- src/config/constants/pools.tsx
Farm info:
LP address: 0x6045931e511ef7e53a4a817f971e0ca28c758809
LP Symbol: CHR-BUSD
Pool info:
Token address: 0xf9CeC8d50f6c8ad3Fb6dcCEC577e05aA32B224FE	
Pool contract address: 0x2d17ec6cd0af737b2ade40ea527d41ceeedc166f
Pool token rewards per block: 1.58
Start Block: https://bscscan.com/block/countdown/18365060
> feat: Sort farm CHR

- packages/uikit/src/hooks/useMatchBreakpoints.ts
Fixes https://github.com/pancakeswap/pancake-frontend/pull/4045#discussion_r887164705
> fix: Media queries off by 1px

- src/hooks/useEagerConnect.bmp.tsx
- src/utils/mpBridge.ts
- src/views/Farms/index.tsx
> feat: Auto connect & fix connect wallet

- src/hooks/useEagerConnect.bmp.tsx
- src/utils/mpBridge.ts
- src/views/Farms/index.tsx
- feat: Auto connect & fix connect wallet
- feat(farm): Intecept link click
> feat(farm): Intercept link click in mp

- src/views/Info/Overview/index.tsx
- src/views/Info/components/InfoCharts/HoverableChart.tsx
Consolidate Info page chart hover over logic and improve performance
resolve #4104
> perf: (info): Consolidate Info page chart hover logic and improve performance

- src/components/PositionCard/index.tsx
To review: 
1. Go to Swap -> Liquidity
2. See dollar value of LP's alongside with lp amount
> feat: (liquidity): Dollar value of LP in liquidity page

- src/views/Pools/helpers.tsx
getPoolBlockInfo used in multiple places so it is better to use memoize instead of useMemo hook
> perf: (pools): Use memoize in getPoolBlockInfo

- src/pages/_app.tsx
- src/utils/mpBridge.ts
- src/views/Farms/MpPageLayout.tsx
> feat: Always show navbar

- src/utils/mpBridge.ts
> feat(farm): Add error handle

- src/utils/mpBridge.ts
- src/views/Farms/components/FarmTabButtons/index.tsx
> feat(farm): Support farm history

- src/utils/mpBridge.ts
> feat: Update mpBridge

- src/utils/getPerpetualLanguageCode.ts
> feat: PerpetualLangs add japanese

- src/components/QuestionHelper/index.tsx
- src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IFORequirements.tsx
> refactor: Remove setting default tooltip option

- src/config/constants/farmAuctions.ts
Merge it before Tuesday, 5 July, 1300 UTC
> feat: List farm auction 25

- src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardTokens.tsx
- src/views/Ifos/components/IfoFoldableCard/Timer.tsx
- src/views/LimitOrders/components/ConfirmLimitOrderModal.tsx
To make it compatible with other languages
> chore: Use css text transform instead of method call

- packages/uikit/src/components/BottomDrawer/styles.ts
- packages/uikit/src/components/Box/Box.tsx
- packages/uikit/src/components/Box/index.tsx
- packages/uikit/src/widgets/Modal/Modal.tsx
- packages/uikit/src/widgets/Modal/ModalContext.tsx
- packages/uikit/src/widgets/Modal/styles.tsx
- src/components/SearchModal/CurrencySearchModal.tsx
> feat: Modal to Bottom action sheet on mobile with swipe down feature

- src/components/Card/index.tsx
https://github.com/pancakeswap/pancake-frontend/pull/4022#issuecomment-1173387006
> fix: Border color of liquidity pool info

- packages/uikit/src/components/BottomDrawer/styles.ts
- packages/uikit/src/components/Box/Box.tsx
- packages/uikit/src/components/Box/index.tsx
- packages/uikit/src/widgets/Modal/Modal.tsx
- packages/uikit/src/widgets/Modal/ModalContext.tsx
- packages/uikit/src/widgets/Modal/styles.tsx
- src/components/SearchModal/CurrencySearchModal.tsx
Reverts pancakeswap/pancake-frontend#4179
> revert: "feat: Modal to Bottom action sheet on mobile with swipe down feature"

- src/pages/_mp/pools/history.tsx
- src/pages/_mp/pools/index.tsx
- src/utils/mpBridge.ts
- src/views/Pools/MpPageLayout.tsx
- src/views/Pools/components/PoolTabButtons.tsx
> feat(pools): support mp

- src/state/pools/hooks.ts
- src/state/pools/selectors.ts
- src/views/Pools/components/PoolsTable/ExpandRow.tsx
- src/views/Pools/components/PoolsTable/PoolRow.tsx
- src/views/Pools/components/PoolsTable/PoolsTable.tsx
Before
https://user-images.githubusercontent.com/97418926/177695111-6d9e3cf0-95e5-4bd9-b0b0-396e267ad66e.mp4
After
https://user-images.githubusercontent.com/97418926/177694946-3667e4b3-1230-4731-aff6-0c26e3a1cc45.mp4
> chore(pools): Reduce re-rendering in PoolRow

- packages/uikit/src/components/Input/Input.tsx
- src/components/Menu/GlobalSettings/TransactionSettings.tsx
avoid deadline crash if set too large
> fix(settings): Add deadline limit

- src/utils/mpBridge.ts
> fix: External link ui error in mp webview

- packages/uikit/src/components/CoinSwitcher/CoinSwitcher.tsx
- src/views/Predictions/components/Label.tsx
> fix: Perdiction switch button style

- src/state/swap/hooks.ts
Reverts pancakeswap/pancake-frontend#4175
> revert: "chore: Temp hide lp aprs"

- src/utils/mpBridge.ts
- src/views/Farms/MpPageLayout.tsx
- src/views/Pools/MpPageLayout.tsx
> feat: Add i18n support

- src/utils/mpBridge.ts
> fix: Fix lang error

- packages/uikit/src/widgets/Modal/styles.tsx
- src/components/RoiCalculatorModal/index.tsx
- src/views/FarmAuction/components/PlaceBidModal.tsx
- src/views/Lottery/components/BuyTicketsModal/BuyTicketsModal.tsx
- src/views/Lottery/components/BuyTicketsModal/EditNumbersModal.tsx
- src/views/Lottery/components/ViewTicketsModal/index.tsx
> fix: Modal bottom style

- src/views/LimitOrders/index.tsx
> style(limit-orders): Set max width

- src/views/AddLiquidity/ChoosePair.tsx
> fix: Add Liquidity connect wallet button been disabled

- package.json
- src/hooks/useTheme.ts
- src/hooks/useThemeCookie.ts
- yarn.lock
Library `js.cookie` value will be encode.
> fix: Remove js.cookie use js-cookie

- src/utils/mpBridge.ts
> fix: Fix swap deeplink

- src/views/Farms/MpPageLayout.tsx
- src/views/Pools/MpPageLayout.tsx
> fix: Fix infinite loop for mp

- src/views/Farms/MpPageLayout.tsx
- src/views/Pools/MpPageLayout.tsx
> feat: Read theme from binance app

- src/views/Voting/components/CastVoteModal/index.tsx
- src/views/Voting/components/CastVoteModal/styles.tsx
- src/views/Voting/components/VoteDetailsModal.tsx
> fix: Vote mobile modal

- src/views/Nft/market/components/Activity/MobileModal.tsx
> fix: Nft modal mobile style

- src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/index.tsx
- src/views/Nft/market/Collection/IndividualNFTPage/PancakeBunnyPage/index.tsx
> fix: Nfts collections style

- src/config/constants/farms.ts
- src/config/constants/pools.tsx
Farm info
Pid: 73
LP symbol: HIGH-BUSD
Pool info
Token address: 0x5f4Bde007Dc06b867f86EBFE4802e34A1fFEEd63
Pool contract address: 0x28cc814be3b994187b7f8bfed10516a84a671119
Pool token rewards per block: 0.1332
Start block: https://bscscan.com/block/countdown/19916070
> feat: List High pool

- src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
- src/config/localization/translations.json
> feat(ROI Calculator): Farms displays both LP and CAKE rewards

- src/config/constants/ifo.ts
- src/views/Home/components/Banners/IFOBanner.tsx
- src/views/Home/components/Banners/hooks/useMultipleBannerConfig.tsx
> chore(ifo): Update ifo banner name

- src/state/pools/fetchPoolsUser.ts
It reduces fetchPoolsUserDataAsync calculation time ~300ms on desktop should be more in mobile devices
> perf: (pools): Reduce fetch pools async calls calculations

- src/components/SearchInput/SearchInput.tsx
- src/views/Farms/Farms.tsx
- src/views/Pools/index.tsx
> feat: Support urlQuery for mp

- src/utils/mpBridge.ts
> fix: payload maybe not an object

- src/config/constants/farmAuctions.ts
https://github.com/pancakeswap/pancake-frontend/commit/360d54e8040e0f2ab152e814e9c04bbc588c69e5
> feat: Remove BBT-BNB

- packages/uikit/src/components/BaseMenu/BaseMenu.tsx
To review:
Go to nft activities page
See collection filter working properly
> perf: Run cleanup function on base menu only once

- cypress/integration/exchange/swap.test.ts
- packages/uikit/src/widgets/Modal/types.ts
- src/components/Menu/GlobalSettings/SettingsModal.tsx
- src/components/Menu/GlobalSettings/index.tsx
- src/components/Menu/GlobalSettings/types.ts
- src/components/Menu/index.tsx
- src/views/LimitOrders/components/CurrencyInputHeader.tsx
- src/views/Swap/components/CurrencyInputHeader.tsx
1) The corresponding options appear in GlobalSettings according to the function.
2) Remove LimitOrder's setting button
> feat(GlobalSettings): Setting button optimization

- src/components/App/AppHeader.tsx
- src/components/Menu/GlobalSettings/SettingsModal.tsx
Fix Liquidity settings content
> fix(GlobalSettings): Fix Liquidity settings content

- src/views/Profile/components/SubMenu.tsx
> fix(Profile): Fix profile subMenu marginBottom

- src/components/Select/Select.tsx
To review:
Go to farms
Check sort by select dropdown works correctly
> refactor: Remove redundant ref in select component

- src/components/Menu/GlobalSettings/SettingsModal.tsx
TransationSpeed move to swapSettings
> fix(SwapSettings): Add transationSpeed option

- src/views/Pottery/components/Banner/index.tsx
- src/views/Pottery/components/Pot/Deposit/index.tsx
Will release today after 12 UTC
> feat: Show pottery timer

- src/views/Voting/config.ts
> perf: Remove Hops address from admins list

- packages/uikit/src/widgets/Modal/ModalContext.tsx
this will fix the modal swipe down issue
> chore: lazy motion feature adjustment

- doc/i18n.md
> docs: Update localization import path

- src/views/Home/components/Banners/MultipleBanner.tsx
- src/views/Predictions/MobileChart.tsx
- src/views/Predictions/Positions.tsx
- src/views/Predictions/components/PrevNextNav.tsx
To reproduce: 
1. Go to mobile prediction
2. Go to charts 
3. Tap yellow dots
4. See error on console
> fix: (prediction): Swiper error on mobile chart when clicking dots

- packages/uikit/src/widgets/Modal/styles.tsx
- packages/uikit/src/widgets/WalletModal/ConnectModal.tsx
- src/components/DisclaimerModal/index.tsx
- src/components/Menu/UserMenu/WalletModal.tsx
- src/views/Lottery/components/ClaimPrizesModal/index.tsx
- src/views/PancakeSquad/components/Modals/BuyTickets/index.tsx
- src/views/PancakeSquad/components/Modals/Confirm/index.tsx
- src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
- src/views/Predictions/components/ChainlinkChartDisclaimer.tsx
- src/views/Predictions/components/ChartDisclaimer.tsx
- src/views/Predictions/components/CollectRoundWinningsModal.tsx
- src/views/Predictions/components/v1/NothingToClaimModal.tsx
- src/views/Swap/components/SwapWarningModal/index.tsx
> fix: Modal container minWidth not recognized in dom warning

- src/components/Menu/GlobalSettings/SettingsModal.tsx
- src/components/SearchModal/CurrencySearchModal.tsx
- src/views/Nft/market/components/ProfileNftModal.tsx
1. fix the global setting mobile modal height
2. fix token list search modal height change issue on mobile
3. fix ProfileNftModal layout issue on mobile
> chore: modal adjustment

- src/views/Home/components/CakeDataRow.tsx
Merge this at today **UTC 12pm**
> feat: Update emissions per block

- src/components/SearchModal/CurrencyList.tsx
- src/components/SearchModal/CurrencySearch.tsx
- src/components/SearchModal/CurrencySearchModal.tsx
calculate the specific height for the virtual scrolling token list (react-window), 
so we can use the max space in different sizes of mobile devices
> chore: cal token list height for react window

- packages/uikit/src/components/Footer/config.tsx
chore(uikit): add india to footer tg shortcuts
हिन्दी :  https://hi.wikipedia.org/wiki/हिन्दी
href: https://t.me/PancakeSwapINDIA
> chore(uikit): add india to footer tg shortcuts

- src/views/Farms/components/YieldBooster/components/CreateProxyButton.tsx
> fix: (farms): Ondone button warning on proxy button

- src/views/Farms/components/BCakeBoosterCard.tsx
> fix: bCake bootedcard tooltip mobile issue

- packages/uikit/src/components/DropdownMenu/styles.tsx
DropdownMenu will overlay BottomNav
> fix(DropdownMenu): DropdownMenu will overlay BottomNav

- next.config.js
- package.json
- sentry.client.config.js
- sentry.server.config.js
- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/hooks/useCallWithGasPrice.ts
- src/hooks/useSentryUser.ts
- src/pages/_error.tsx
- src/utils/clearUserStates.ts
- src/utils/sentry.ts
- src/views/NotFound.tsx
- yarn.lock
> chore: Bump sentry v7

- apps/bridge/components/Menu.tsx
- packages/swap-sdk/package.json
- yarn.lock
> chore(sdk): Publish version

- src/config/constants/farms.ts
> feat: List farm auction 28 winner

- src/views/Home/components/Banners/LotteryBanner.tsx
- src/views/Home/components/Banners/MultipleBanner.tsx
- src/views/Home/components/Banners/PerpetualBanner.tsx
fix the mobile banner layout issue in different lang
> chore: banner layout issue

- src/views/Voting/helpers.ts
Reduce method increases the memory footprint therefore we should avoid using that if it is creating a new object on each iteration. This pr reduces the calculation time from 50ms to 1ms on laptop, should be more in mobile devices
> perf: (voting): Reduce calculations in voting

- src/views/RemoveLiquidity/index.tsx
Instead of making calls to all the possible methods, just return safe gas estimate when the we have it. Current behavior is similar to this but it chooses the first safe gas estimate after making calls for all the methods to the on-chain
> perf: Reduce gas estimate calls to on chain in remove liquidity

- src/state/info/queries/helpers.ts
Reduces calculation time from 60ms in laptop to 0ms per call
> perf: (info): Reduce calculations in info

- src/views/AddLiquidity/ChoosePair.tsx
New visitors or users without wallet can see the rewards apr without connecting the wallet.
> feat: (liquidity): Add lp rewards apr info to the first step of add liquidity

- src/components/AddToWallet/AddToWalletButton.tsx
- src/utils/wallet.ts
SafePalWallet now has both IsMetaMask & IsTrust flags, so it needs to be fixed
> fix(Wallet): SafePal no show "Add to Wallet"

- src/utils/mpBridge.ts
> feat: Support on action

- src/utils/prices.ts
> fix(exchange): Prevent crash when price denominator is 0

- src/hooks/useBUSDPrice.ts
> fix: useBUSDPrice more checking

- packages/uikit/src/components/CoinSwitcher/CoinSwitcher.tsx
> fix(Prediction): Fix tokenSwitch click area

- src/views/Farms/components/FarmCard/ApyButton.tsx
- src/views/Farms/components/FarmCard/FarmCard.tsx
- src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
- src/views/Farms/components/FarmTable/Apr.tsx
> feat(Farms): APR use TooltipText and show deatil of APR

- src/config/constants/farms/56.ts
- src/config/constants/pools.tsx
Details for WOM farm&pool
**Farm info:**
LP Symbol: WOM -BUSD
Address: 0xe68d05418a8d7969d9ca6761ad46f449629d928c
**Pool info:**
Token address: 0xad6742a35fb341a9cc6ad674738dd8da98b94fb1	
Pool contract address: 0xf78db5b635ba108212c9d84c124a52d7b1596b97
Pool token rewards per block: 3.4722
> feat: List WOM

- src/views/Ifos/components/IfoVesting/VestingPeriod/TokenInfo.tsx
> feat(IFO): TokenVesting add priceUsd of claimable

- src/views/LimitOrders/index.tsx
- src/views/Swap/index.tsx
To reproduce: 
1. Go to swap
2. Change tokens
3. Then use switch button to change output and input currency
4. See url is not updated
> fix: (swap): Url is not constructed properly when switch button used

- src/config/constants/farms/56.ts
> chore: Hide SPIN-BNB

- src/components/Menu/hooks/useMenuItems.ts
- src/components/Menu/hooks/useMenuItemsStatus.ts
- src/components/Menu/hooks/usePotteryStatus.ts
> feat: (pottery): Make pottery status pot open in menu when before lock

- packages/wagmi/chains/chains.ts
> fix(wallet): RPC setting overrided

- src/components/AddToWallet/AddToWalletButton.tsx
> fix(Wallet): SafePal&BinanceWallet no show AddToWalletButton

- packages/localization/src/config/translations.json
- src/views/Farms/components/FarmCard/ApyButton.tsx
bCake farm tooltip
normal farm
> feat: farm APR tooltip for bCake

- src/components/App/AppHeader.tsx
Helper should be to prompt title, not subtitle.
Before:
After:
> chore(AppHeader): Move Helper to the end of the Title

- src/views/LimitOrders/components/ConfirmLimitOrderModal.tsx
- src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
> fix(Limit): Fix confirm window UI in Mobile

- src/state/pools/fetchPools.ts
It will reduce the decompression cpu load of the http responses. Thus a performance increase especially for low-end mobile phones
> perf: (pools): Fetch only unfinished pools block limits and profile requirements

- src/views/LimitOrders/index.tsx
- src/views/Swap/components/Chart/PriceChart.tsx
Hide TradingView button:
- This button should be hidden as TradingView is currently unavailable.
- Before:
- After:
---
Fix Limit tokenPairs visable:
- Before:
- After:
> fix(PriceChart): Hide TradingView button and fix Limit tokenPairs visable

- src/views/Info/hooks/useCMCLink.ts
To review:
2. Go to info of some token
3. See cmc logo next to 'view on bscscan' is visible
> perf: (info): Use swr in useCmcLink hook to fetch url

- packages/uikit/src/components/Toast/Toast.tsx
- src/views/Ifos/components/IfoVesting/VestingPeriod/Expand.tsx
- src/views/Ifos/components/IfoVesting/index.tsx
> style: Fix ios IFO vesting card

- src/state/swap/normalizers.ts
To review:
1. Go to swap 
2. Open chart
3. Find a pair that is not direct lp and multihops is necessary
4. See everything is working properly
> perf: (swap): Eliminate intermediate arrays in swap chart normalization

- src/state/achievements/helpers.ts
To review:
1. Go to profile 
2. Go to achievements tab
3. See it is listed properly
> perf: (achievements): Reduce intermediate arrays when getting achievements

- packages/localization/src/config/translations.json
- src/views/Farms/components/FarmCard/ApyButton.tsx
> chore(farm): Restyle tooltip text in boosted farm

- src/views/Ifos/types.ts
Compiler complains when function is called in await Promise.all
> fix: (ifo): Fix ifo function properties return type

- src/components/Modal/ModalActions.tsx
> style: Modal Actions css

- packages/farms/constants/56.ts
Although it will be live tomorrow, but we have a loading function so can merge it anytime.
> feat: List farm auction 30 winners

- src/components/Menu/UserMenu/WalletTransactions.tsx
> style: WalletTransactions add scrollbar

- packages/farms/constants/56.ts
> chore: farm list order adjustment for BCake

- packages/multicall/index.ts
- src/views/Voting/helpers.ts
- src/views/Voting/strategies.ts
Reverts pancakeswap/pancake-frontend#4790
> revert: "revert: Cake locked amount in tooltip"

- packages/farms/constants/56.ts
- packages/localization/src/config/translations.json
- src/config/constants/pools.tsx
Farm info:
LP Symbol: HOOP -BUSD
Address: 0xde8a4f457af12f98db090841579feed384684819
Pool info:
Token address: 0xF19cfb40B3774dF6Eed83169Ad5aB0Aaf6865F25
Pool contract address: 0x6c254e3ab3e4b909a2cfaa3e0b9d2b3f7887cfae
Pool token rewards per block: 2.146
> feat: List Hoop pool and farm

- src/state/teams/helpers.ts
To review:
1. Go to teams page (/teams)
2. See teams and member amounts are listed properly
> perf: (teams): Reduce memory footprint

- src/components/SearchModal/CommonBases.tsx
Go to swap, open currency search modal see warning in console
> fix: Key warning in common bases component

- apps/bridge/package.json
- package.json
- yarn.lock
to fix coinbase connector chain id reset issue
> chore: Update wagmi

- src/views/Swap/components/SwapTab.tsx
> feat(SwapTab): Optimize UI

- packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
- packages/uikit/src/components/DropdownMenu/DropdownMenu.tsx
- packages/uikit/src/components/DropdownMenu/styles.tsx
- packages/uikit/src/components/MenuItem/styles.tsx
- packages/uikit/src/widgets/Menu/components/UserMenu/styles.tsx
- src/components/Menu/config/config.ts
- src/components/Menu/hooks/useMenuItemsStatus.ts
- Perpetual only support bsc
- Hide IFO status
- `pointer-events` set to `none` when `disabled`
> perf: Perpetual only support bsc

- src/state/types.ts
- src/state/voting/helpers.ts
> refactor: (voting): Remove space data from proposal/vote fetch

- packages/uikit/src/__tests__/widgets/modal.test.tsx
- packages/uikit/src/__tests__/widgets/walletModal.test.tsx
- packages/uikit/src/widgets/Modal/styles.tsx
- src/components/Menu/GlobalSettings/ExpertModal.tsx
- src/components/Menu/GlobalSettings/SettingsModal.tsx
- src/components/UnsupportedCurrencyFooter.tsx
- src/views/Nft/market/components/Activity/MobileModal.tsx
- src/views/Pools/components/LockedPool/Modals/AddAmountModal.tsx
Go to swap
Click Settings
Enable expert mode
See modal is wider than usual
> fix: (expert-mode): Expert mode modal width in desktop and remove maxWidth property from modals

- package.json
- packages/uikit/src/components/Toast/Toast.tsx
- yarn.lock
Check console for the error when toast appears
> fix: (toast): Find dom node warning in strict mode in toast and bump up react transition group

- src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
> fix: (activity): Wrong type of value set to width prop when device width is not a isMd

- packages/uikit/src/__tests__/widgets/modal.test.tsx
- packages/uikit/src/__tests__/widgets/walletModal.test.tsx
- packages/uikit/src/widgets/Modal/styles.tsx
- src/views/Swap/StableSwap/hooks/useStableTradeExactIn.ts
before:
https://user-images.githubusercontent.com/94336009/193742554-e8be9e1b-0daa-4601-b268-8dafa7bc5278.mp4
after:
https://user-images.githubusercontent.com/94336009/193742620-d477105b-5084-4af9-9222-116262b2977a.mp4
> perf(stableswap): better interaction when typing value

- src/state/swap/hooks.test.ts
- src/state/swap/hooks.ts
To reproduce
Switch to eth chain
Go to swap
Switch to eth in output currency
Refresh page
See currency not loaded properly
> fix: (swap): Swap url contains with native token of other chains won't work

- packages/farms/constants/56.ts
- src/config/constants/pools.tsx
Pool info
Token address: 0x6679eb24f59dfe111864aec72b443d1da666b360
Pool contract address: 0x420cd06440d8845fbcde9a396d9aa211fe78c03d
Pool token rewards per block: 1335.47
Farm info
LP address: 0xa63e32feefc6590bbf869070fd2e706eb7881bd2
LP symbol: ARV-BNB
> chore(farm): Add ARV Pool

- src/state/info/queries/pools/poolData.ts
- src/state/info/queries/pools/topPools.ts
- src/state/info/queries/tokens/tokenData.ts
- src/state/info/queries/tokens/topTokens.ts
> chore: multichain info adjustment

- src/state/swap/hooks.ts
To review:
Lp7dapr should be working in liquidity page
> refactor: (liquidity): Simplify lp7dApr hook

- packages/localization/src/config/translations.json
- src/state/pottery/fetchPottery.ts
- src/state/pottery/index.ts
- src/state/types.ts
- src/views/Pottery/components/Banner/index.tsx
- src/views/Pottery/components/Timer.tsx
> feat: (pottery): Add next pot lock time countdown to pottery page

- packages/tokens/src/helpers.ts
- src/components/SearchModal/CurrencySearch.tsx
- src/state/lists/hooks.ts
It is not used anywhere and degrades the performance
> perf: (token-search): Remove tag info from wrappedtokeninfo

- src/state/info/queries/search/index.ts
To review
2. Search some pools for example using 'wbnb'
3. See pools listed properly on search component
> perf: (info): Eliminate intermediate arrays when getting ids

- packages/farms/constants/56.ts
- src/config/constants/pools.tsx
Farm info:
LP Symbol: KRS -BUSD
Address: 0xac747ad9d61884986ad7a4a6cc5de998ce21b253
Pool info:
Token address: 0x37b53894e7429f794B56F22a32E1695567Ee9913
Pool contract address: 0x067f926eb8f2a95f260327b01c29b2034a785029
Pool token rewards per block: 4.96
> feat: List KRS

- src/views/Swap/components/SwapForm.tsx
To review:
1. Go to swap
2. Select hay - busd
3. See warning component
> feat: (swap): Add stable swap warning to swap tab

- packages/uikit/src/components/Tooltip/theme.ts
- packages/uikit/src/hooks/useTooltip/useTooltip.tsx
- src/views/Predictions/components/Label.tsx
> style: Tooltip color flip

- src/views/Nft/market/ActivityHistory/utils/fetchActivityNftMetadata.tsx
Avoids multiple filter operations
> perf: (nft): Use partition in nft activity to separate pb collections

- src/state/info/hooks.ts
remove the re-fetch setting for some unchanged data it depends on daily
> chore: reduce unnecessary refetch for info page

- src/state/pools/hooks.ts
To reproduce:
Go to ifo with an account doesn't have stake in cake pool
See apy's in vault card
Click roi calculator
Enter amount
See roi shows 0
> fix: (ifo): Vault card roi calculator doesn't show roi

- src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoCardDetails.tsx
> feat(IFO): Change pricePerTokenWithFee's precision from 2 to 4

- src/state/types.ts
- src/state/voting/helpers.ts
vp seems like can get from endpoint when live now
> perf(voting): VP get from graphql

- packages/ui-wallets/src/WalletModal.tsx
> chore(WalletModal): Remove tab gap

- apps/web/src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
Before: the pagination is inside the scrollable container
After: move the pagination outside of the scrollable container
> fix: missing border on small devices

- packages/uikit/src/widgets/Farm/components/DepositModal/index.tsx
- packages/uikit/src/widgets/Farm/components/WithdrawModal/index.tsx
- packages/uikit/src/widgets/Modal/ModalInput.tsx
> feat(Farms): Stake and unstake add percent input button

- apps/web/src/views/Nft/market/ActivityHistory/ActivityHistory.tsx
- packages/uikit/src/components/Image/BackgroundImage.tsx
Before there happens to have an unexpected scrollbar
After
> style: remove unexpected scrollbar

- apps/web/src/config/constants/pools.tsx
Because now the deposit in the cake pool will call booster SC. so it will need more gas. 
Gas Used: 528,079 
raising gas-limit from 500,000 to 600,000
> chore: Adjust gas-limit for cake pool

- apps/web/src/views/Voting/components/Proposals/Filters.tsx
> fix(Voting): Fix radio UI on mobile

- apps/web/src/views/Nft/market/Home/Collections.tsx
> fix(NFTOverview): Fix ViewAll button minWidth

- packages/uikit/src/components/RoiCalculatorModal/RoiCalculatorFooter.tsx
> fix(Farms): Fix ROICalculator Base APR

- apps/web/src/views/LimitOrders/index.tsx
- apps/web/src/views/Swap/StableSwap/components/StableSwapForm.tsx
- apps/web/src/views/Swap/components/SwapForm.tsx
To reproduce:
First issue: 
1. Go to swap
2. Change output token to bnb
3. See input token switched to cake
4. Refresh the page
5. See input token not visible
Second issue: 
1. Change input token to cake
2. See output token switched to bnb
3. Refresh the page
4. See output token not visible
> fix: (swap): Url construction wrong when output token selected as input token and vice versa

- apps/web/src/views/Info/components/InfoSearch/index.tsx
To review:
2. Click search text search
3. See search component under that is visible
> perf: (info): Don't process info search component to add to dom when show menu is false

- apps/web/src/hooks/useActiveWeb3React.ts
if previous value used in use effect dependency and if multiple render occurs, it triggers a unnecessary render which the previous value is equal to current value therefore it makes two async router replace calls (one is removing queries the other not) causes race condition.
To reproduce:
1. Go to liquidity
2. Change tokens
3. Change network
4. See sometimes default tokens not loaded correctly
> fix: Default liquidity tokens not loaded intermittently when changing network

- apps/web/src/views/TradingCompetition/MoDCompetition.tsx
- apps/web/src/views/TradingCompetition/MoboxCompetition.tsx
- apps/web/src/views/TradingCompetition/components/TeamRanksSection.tsx
> fix(TradingCompetition): Fix TeamRanks section UI

- apps/aptos/hooks/useAuth.ts
return the value for wallet to save the last used wallet
> fix(aptos): Add useAuth return

- apps/web/src/views/Swap/components/Chart/BasicChart.tsx
solution to issue #5194
fixes bug that caused chart to grow infinitely when click on the expand button.
(https://github.com/pancakeswap/pancake-frontend/issues/5194)
> fix: Exchange chart height increases infinitely

- apps/web/src/views/LimitOrders/index.tsx
> feat(Limit): Add scan risk

- packages/multicall/index.ts
- packages/smart-router/evm/onchain/getPairs.ts
Fix uncaught exception when making multicall to non existing address
> fix: uncaught exception when making multicall to non existing address

- packages/smart-router/evm/constants/stableSwap/1.ts
- packages/smart-router/evm/constants/stableSwap/4.ts
- packages/smart-router/evm/constants/stableSwap/5.ts
- packages/smart-router/evm/constants/stableSwap/56.ts
- packages/smart-router/evm/constants/stableSwap/97.ts
- packages/smart-router/evm/constants/stableSwap/index.ts
- packages/smart-router/evm/constants/stableSwap/pools.ts
- packages/smart-router/evm/getStableSwapPairs.ts
- packages/smart-router/evm/index.ts
- packages/smart-router/evm/types/pool.ts
- packages/smart-router/package.json
Extract stable swap config from farms
> fix: use own stable swap pool config instead of depending on farms

- apps/web/src/views/Pottery/components/FAQ.tsx
> chore(Pottery): FAQ answer content style

- apps/web/src/views/Voting/components/CastVoteModal/index.tsx
- apps/web/src/views/Voting/components/VoteDetailsModal.tsx
- apps/web/src/views/Voting/hooks/useGetVotingPower.tsx
To reproduce:
1. Open cast vote
2. Click confirm vote
3. While casting vote click voting power details
4. Wait vote to be casted
5. See crash
> fix: (voting): Crash when voting power details open when in cast vote modal while casting vote

- packages/smart-router/evm/getBestTradeFromV2.ts
- packages/smart-router/evm/getBestTradeWithStableSwap.ts
- packages/smart-router/evm/index.ts
- packages/smart-router/evm/stableSwap.ts
- packages/smart-router/evm/types/index.ts
- packages/smart-router/evm/types/stableSwap.ts
Support exact output for smart router
> feat: add support for exact output

- packages/smart-router/evm/stableSwap.ts
- packages/smart-router/evm/types/stableSwap.ts
- packages/smart-router/evm/utils/pair.ts
Separate stable swap related types with the v2 trade related types
> refactor: clarify stable swap related types

- .changeset/orange-olives-search.md
> chore: add changeset for previous api update

- apps/web/src/components/Menu/UserMenu/WalletInfo.tsx
It is beneficial to show wbnb token balance especially when user's nft is sold
> feat: (wallet): Show wnative token balance in wallet info modal if exist

- apps/web/src/state/predictions/index.ts
To review:
Go to prediction > user round history
Check everything works properly
> perf: (prediction): Don't serialize rounds when fetching them in history

- .changeset/tricky-flies-wonder.md
- apps/web/src/index.tsx
- apps/web/src/pages/_app.tsx
- packages/token-lists/react/lists.ts
Lists from indexeddb loaded after fetch. resulting the requestId not matching..
Moving `ListsUpdater` out of redux persist seems fixed the need of `delayInit`
> fix(lists): Loaded from indexeddb after fetch

- .changeset/tricky-flies-wonder.md
- apps/web/src/index.tsx
- apps/web/src/pages/_app.tsx
- packages/token-lists/react/lists.ts
Reverts pancakeswap/pancake-frontend#5329
> revert: "fix(lists): Loaded from indexeddb after fetch"

- apps/web/src/views/Farms/components/YieldBooster/hooks/useBoosterFarmHandlers.ts
Some users complaining it fails sometimes if it uses wallet estimation
> feat: Set farm booster activate gas limit

- packages/wagmi/connectors/binanceWallet/binanceWallet.ts
The `??` syntax didn't compile correctly, so it may cause a compatibility problem in some mobile browsers.
[x] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[x] If your PR is work in progress, open it as `draft`
[x] Before requesting a review, all the checks need to pass
[x] Explain what your PR does
> fix: Not compatible syntax

- apps/web/src/state/swap/actions.ts
- apps/web/src/state/swap/reducer.ts
- apps/web/src/state/swap/useSwapActionHandlers.ts
- apps/web/src/views/Swap/SmartSwap/index.tsx
- packages/smart-router/evm/getBestTradeWithStableSwap.ts
Unexpected change of trade type after switching currencies with smart router on
> fix: Wrong trade type after switching currencies

- apps/web/src/state/swap/actions.ts
- apps/web/src/state/swap/reducer.ts
- apps/web/src/state/swap/useSwapActionHandlers.ts
- apps/web/src/views/Swap/SmartSwap/hooks/useIsSmartRouterBetter.tsx
- apps/web/src/views/Swap/SmartSwap/index.tsx
Trade type not updated when dynamically switching from v2 to smart swap
> fix: Trade type not updated

- apps/web/src/config/constants/endpoints.ts
- apps/web/src/config/constants/info.ts
- apps/web/src/hooks/useBucket.ts
- apps/web/src/middleware.ts
- apps/web/src/state/info/constant.ts
- apps/web/src/state/info/queries/tokens/priceData.ts
- apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
- apps/web/src/state/swap/fetch/fetchPairPriceData.ts
- apps/web/src/state/swap/hooks.ts
- apps/web/src/utils/graphql.ts
Reverts pancakeswap/pancake-frontend#5416
this should deploy next week, so need to  revert now
> revert: PR #5416

- apps/web/src/config/constants/endpoints.ts
- apps/web/src/config/constants/info.ts
- apps/web/src/hooks/useBucket.ts
- apps/web/src/middleware.ts
- apps/web/src/state/info/constant.ts
- apps/web/src/state/info/queries/tokens/priceData.ts
- apps/web/src/state/swap/fetch/fetchDerivedPriceData.ts
- apps/web/src/state/swap/fetch/fetchPairPriceData.ts
- apps/web/src/state/swap/hooks.ts
- apps/web/src/utils/graphql.ts
Reverts pancakeswap/pancake-frontend#5417
> revert: "revert: PR #5416"

- apps/web/src/state/pools/fetchPoolsUser.ts
- apps/web/src/state/pools/fetchVaultPublic.ts
- apps/web/src/state/pottery/fetchPottery.ts
- apps/web/src/utils/calls/pools.ts
- apps/web/src/utils/multicall.ts
- apps/web/src/views/Home/components/CakeDataRow.tsx
- packages/multicall/index.ts
There will be currently three places that multicallv3 used
To review: 
Go to pools
See apr and user balances loaded correctly
Go to home page 
See cake supply information at the bottom part loaded correctly
Go to pottery
See everything works properly
> perf: Fix multicall v3 and use possible places to reduce calls

- apps/web/src/views/Farms/components/FarmTable/Farm.tsx
> fix(BoosterFarms): "FARMING" not shown

- apps/web/package.json
- yarn.lock
It contains a bugfix occurs when reset
> chore: Bump up react count up

- apps/web/src/views/Swap/components/SwapWarningModal/Acknowledgement.tsx
> fix(NoticeAlert): Click "I understand" to trigger the checkbox

- apps/aptos/components/Farms/components/FarmTable/FarmTable.tsx
- apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
- packages/uikit/src/widgets/Pool/PoolsTable/index.tsx
> fix: (table): Border overflow in action panel in farm/pools table

- apps/bridge/pages/aptos.tsx
> style(bridge): Fix css

- apps/aptos/config/constants/tokenLists/pancake-default.tokenlist.json
Pls approve this when review this PR
https://github.com/pancakeswap/token-list/pull/87
> chore: Adjustment aptos token name

- packages/uikit/src/widgets/Pool/StakeModal.tsx
> fix: (pools): Render warning in stake modal

- apps/web/src/components/NetworkModal/UnsupportedNetworkModal.tsx
- apps/web/src/views/Farms/components/BCakeBoosterCard.tsx
- apps/web/src/views/Home/components/Banners/AptosBanner.tsx
- apps/web/src/views/Home/components/Banners/CompetitionBanner.tsx
- apps/web/src/views/Home/components/Banners/IFOBanner.tsx
- apps/web/src/views/Home/components/Banners/LotteryBanner.tsx
- apps/web/src/views/Home/components/Banners/PerpetualBanner.tsx
- apps/web/src/views/Home/components/Hero.tsx
- apps/web/src/views/Nft/market/components/BannerHeader/index.tsx
- apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCard.tsx
- apps/web/src/views/Pottery/components/PrizeFunds.tsx
- apps/web/src/views/TradingCompetition/Footer.tsx
- apps/web/src/views/TradingCompetition/MoDCompetition.tsx
- apps/web/src/views/TradingCompetition/components/ClaimModal/index.tsx
- apps/web/src/views/TradingCompetition/components/FinishedCompetitionBanner/index.tsx
- apps/web/src/views/TradingCompetition/components/PrizesInfo/PrizesGrid/PrizesGrid.tsx
- apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanks.tsx
- apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
- apps/web/src/views/TradingCompetition/easter/components/BattleBanner/EasterBattleBanner.tsx
- apps/web/src/views/TradingCompetition/easter/components/PrizesInfo/EasterPrizesText.tsx
- apps/web/src/views/TradingCompetition/fantoken/components/BattleBanner/FanTokenBattleBanner.tsx
- apps/web/src/views/TradingCompetition/fantoken/components/PrizesInfo/FanTokenPrizesText.tsx
- apps/web/src/views/TradingCompetition/mobox/components/BattleBanner/MoboxBattleBanner.tsx
- apps/web/src/views/TradingCompetition/mobox/components/PrizesInfo/MoboxPrizesText.tsx
- apps/web/src/views/TradingCompetition/mod/components/BattleBanner/ModBattleBanner.tsx
- apps/web/src/views/TradingCompetition/mod/components/PrizesInfo/ModPrizesText.tsx
Reverts pancakeswap/pancake-frontend#5554
> fix: Revert "refactor: Remove legacy next image"

- apps/web/src/config/constants/pools.tsx
- packages/farms/constants/56.ts
Farm info:
LP Symbol: SQUAD - CAKE
Address: 0x54cd9d6ce45cef4fcc1ac568329254661b28711d
Pool info:
Token address: 0x724A32dFFF9769A0a0e1F0515c0012d1fB14c3bd
Pool contract address: 0x08c9d626a2f0cc1ed9bd07ebedef8929f45b83d3
Pool token rewards per block: 2.459
> chore: List SQUAD

- apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/GetTokenModal.tsx
- apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/GetTokenModal.tsx
- apps/web/src/views/Predictions/components/History/PnlTab/PnlTab.tsx
> chore(OpenNewIcon): Use invertedContrast color

- apps/web/package.json
- apps/web/src/hooks/useSWRContract.ts
- apps/web/src/state/block/hooks.ts
- apps/web/src/state/multicall/hooks.ts
- apps/web/src/views/Nft/market/Collections/index.tsx
- apps/web/src/views/Nft/market/hooks/useNftsForAddress.tsx
- apps/web/src/views/Predictions/components/ChainlinkChart.tsx
- apps/web/src/views/Swap/SmartSwap/hooks/useBestTrade.ts
- apps/web/src/views/Swap/StableSwap/hooks/useStableTradeExactIn.ts
- packages/wagmi/package.json
- yarn.lock
Reverts pancakeswap/pancake-frontend#5594
the nft collections always be loading after bump swr
need to figure out why
apps/web/src/views/Nft/market/hooks/useCollectionNfts.tsx
nfts  return [] from useSWRInfinite
> revert: "chore: Bump up swr"

- apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
- apps/web/src/views/RemoveLiquidity/index.tsx
on iPhone 12 Mini.
Before:
After:
> style(RemoveLiquidity): Adjust the arrangement of Buttons on mobile

- apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
- apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/index.tsx
> feat(StableLP): Add/Remove LP add percentButton

- apps/bridge/package.json
- apps/web/package.json
- packages/wagmi/package.json
- yarn.lock
> feat: Bump wagmi version

- apps/web/src/views/FarmAuction/components/AuctionLeaderboard/AuctionLeaderboardTable.tsx
> chore: Bidder Address use BscScanIcon

- apps/web/src/components/CurrencyInputPanel/index.tsx
- apps/web/src/components/SearchModal/ManageLists.tsx
- apps/web/src/config/constants/lists.ts
- apps/web/src/hooks/Tokens.ts
- apps/web/src/state/lists/hooks.ts
- apps/web/src/state/user/hooks/index.tsx
- apps/web/src/views/Swap/hooks/useWarningImport.tsx
> chore: Enable coingecko etherum list

- apps/e2e/cypress/integration/nfts/nfts.test.ts
- apps/web/src/views/Nft/market/Collection/Items/CollectionNfts.tsx
- apps/web/src/views/Nft/market/components/MarketPageTitle.tsx
Protect the content and dataflow by adding the NFT collection details page e2e test
> test: NFT collection details page e2e test

- apps/aptos/config/constants/tokens/1.ts
> fix(Aptos): Fix token name

- apps/web/src/hooks/useLockedEndNotification.tsx
> fix(Menu): Pool Lock end tag only show in BSC

- packages/uikit/src/widgets/Farm/components/DepositModal/index.tsx
- packages/uikit/src/widgets/Farm/components/WithdrawModal/index.tsx
- packages/uikit/src/widgets/Modal/ModalInput.tsx
- packages/utils/trimTrailZero.ts
> fix: Modal percentage button

- apps/web/src/components/CurrencyInputPanel/index.tsx
- packages/uikit/src/widgets/Modal/ModalInput.tsx
> fix(Swap&Farms): PercentButton only appears when maxAmount has balance

- apps/web/src/views/Nft/market/components/CollectibleCard/CollectionCardWithVolume.tsx
I am read code, the console found a warning
> fix(NFT): Collection card key warning

- apps/web/src/components/Menu/hooks/useMenuItemsStatus.ts
- apps/web/src/hooks/useLockedEndNotification.tsx
- apps/web/src/hooks/useUserCakeLockStatus.ts
- apps/web/src/views/Pools/components/LockedPool/Buttons/ConvertToFlexibleButton.tsx
- apps/web/src/views/Pools/components/LockedPool/hooks/useLockedPool.tsx
It will reduce bundle size by not including farm hooks and dependencies
> perf: Use direct onchain call to reduce bundle size

- apps/web/src/hooks/useCakeEnable.tsx
- apps/web/src/views/Pools/components/LockedPool/Common/ExtendEnable.tsx
- apps/web/src/views/Profile/components/EditProfileModal/StartView.tsx
- packages/localization/src/config/translations.json
To review 
1. Go to user profile
2. Click avatar to change profile pic
3. See enable button activated if user has not enough cake to change profile pic / reactivate
4. Enable button will swap cake (0.001 cake is needed for changing profile pic) from bnb
> feat: (profile): Add enable button to swap required cake for change profile pic

- apps/web/src/views/Swap/components/HotTokenList/index.tsx
filter project which liquidity is < 100k
> feat: Add liq filter for token highlight list

- apps/web/src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
> style(limit-order): LoadingContent

- apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/Icons/BunnyKnownPlaceholder.tsx
- apps/bridge/components/layerZero/PoweredBy.tsx
- apps/web/src/components/Menu/hooks/useMenuItems.ts
- apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/Icons/BunnyKnownPlaceholder.tsx
- apps/web/src/views/Info/components/InfoCharts/CandleChart/index.tsx
- apps/web/src/views/Lottery/components/BuyTicketsButton.tsx
- apps/web/src/views/PancakeSquad/components/ArtistSection/index.tsx
- apps/web/src/views/Predictions/RoundMultiplierArrows.tsx
> perf: Use theme from context instead of new object for each call

- apis/proxy-worker/src/index.ts
Add empty body request checking for the endpoint
> chore(proxy): Block empty body

- apps/web/src/config/chains.ts
- apps/web/src/hooks/useAccountEventListener.ts
- apps/web/src/hooks/useActiveChainId.ts
- apps/web/src/hooks/useActiveWeb3React.ts
- apps/web/src/hooks/useAuth.tsx
- apps/web/src/hooks/useSwitchNetwork.ts
- apps/web/src/utils/getLiquidityUrlPathParts.ts
- apps/web/src/views/Info/Pools/PoolPage.tsx
- apps/web/src/views/Info/Tokens/TokenPage.tsx
Add back `chainId` support as fallback
> fix(web): Keep chainId as backward compatible

- apps/web/sentry.client.config.js
- apps/web/sentry.server.config.js
Edit sentry files to force Vercel update the sentry id in prod
> chore: Update Sentry ID in vercel build

- apps/web/src/views/Voting/Proposal/Votes.tsx
Show less voting information when on mobile devices, users can quickly view voting results.
> chore(Voting): When on a mobile, show fewer vote results

- apps/web/next.config.mjs
- apps/web/sentry.client.config.js
- apps/web/sentry.server.config.js
Try to update Sentry Release ID
> chore: Try to update sentry id in production

- apps/web/next.config.mjs
> chore: Remove Sentry test

- apps/web/src/config/constants/pools.tsx
- packages/farms/constants/56.ts
Farm info:
LP Symbol: ARENA -CAKE
Address: 0xfcc860289819c8b754ef31a1709a7952eb940223
Pool info:
Token address: 0xCfFD4D3B517b77BE32C76DA768634dE6C738889B
Pool contract address: 0xde9fc6485b5f4a1905d8011fcd201eb78cf34073
Pool token rewards per block: 2.893
> feat(farm/pool): List ARENA

- apps/web/src/views/Swap/SmartSwap/index.tsx
Should not show Trade Info when swaping BNB <-> WBNB
> fix(swap): Not show trade info for wrap and unwrap

- apps/web/src/state/nftMarket/helpers.ts
not sure the reason why the multicall reverts with our node endpoint
> fix(nft): try catch on chain total supply in collection

- apps/web/src/hooks/useFeatureFlag.ts
- apps/web/src/hooks/useLockedEndNotification.tsx
- apps/web/src/hooks/useSwapHotTokenDisplay.ts
- apps/web/src/state/user/hooks/useUserTokenRisk.ts
- apps/web/src/state/user/smartRouter.ts
- apps/web/src/utils/atomWithStorageWithErrorCatch.ts
- apps/web/src/views/Swap/components/CurrencyInputHeader.tsx
> fix: Catch localstorage exceeded quota

- apps/web/src/views/Lottery/components/BuyTicketsModal/TicketInput.tsx
> chore(Lottery): Change edit number input color

- apps/web/src/utils/atomWithStorageWithErrorCatch.ts
Update version of atomWithStorage
> chore: Update atomWithStorageWithErrorCatch version

- .changeset/happy-gifts-watch.md
Bump missing version update on #5932
> chore: Bump pkg version

- apps/web/src/views/Swap/components/AccessRisk/index.tsx
> chore(AvengerDAO): Change text color to inverted

- apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/GetTokenModal.tsx
- apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
- apps/aptos/views/Ifos/generated/ifo.ts
Resolve minor UI issues: 
- Update correct token image link when IFO user open GetTokenModal
- Display proper format for receivable value
> fix(aptos-ifo): Minor format fix

- apps/aptos/components/Logo/CurrencyLogo.css.ts
- apps/aptos/components/Logo/CurrencyLogo.tsx
- apps/aptos/components/NetworkSwitcher.tsx
> feat(Aptos): Testnet logo opacity

- apps/web/src/views/Farms/Farms.tsx
- apps/web/src/views/Farms/context.ts
- apps/web/src/views/Farms/index.tsx
There's possible error `Cannot access FarmContext before initialization` on dev
> fix(mp): Farm context undefined on dev

- apps/web/src/components/Navbar.bmp.tsx
- apps/web/src/utils/mpBridge.ts
Response `toWallet` new return `disconnect` command
> feat(web): can trigger disconnect on mp page

- apps/web/src/components/Menu/GlobalSettings/GasSettings.tsx
- packages/localization/src/config/translations.json
> feat(web): Changes gas settings wording

- packages/uikit/src/widgets/Ifo/IfoGenericIfoCard.tsx
- packages/uikit/src/widgets/Ifo/IfoPercentageOfTotal.tsx
- packages/uikit/src/widgets/Ifo/IfoProgressStepper.tsx
- packages/uikit/src/widgets/Ifo/IfoSkeletons.tsx
- packages/uikit/src/widgets/Ifo/IfoVestingAvailableToClaim.tsx
- packages/uikit/src/widgets/Ifo/IfoVestingFooter.tsx
Dev build gives error if something changes tha depends on uikit such as ui wallet
> fix: (uikit): Import from path not library

- apps/web/src/views/Home/components/Footer.tsx
- apps/web/src/views/Home/components/SalesSection/index.tsx
> chore(HomePage): Add externalLinkIcon of "Learn"

- apps/web/src/views/LimitOrders/components/LimitOrderTable/DetailLimitOrderModal.tsx
> fix(Limit): Fix BSCScanIcon color

- apps/aptos/config/constants/ifo.ts
- apps/aptos/config/constants/tokens/1.ts
- apps/aptos/views/Ifos/components/IfoFoldableCard/IfoCardFooter.tsx
- apps/aptos/views/Ifos/components/IfoFoldableCard/index.tsx
- Add description and information links
> feat(aptos-ifo): Add footer

- apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx
- Update Unlimited Sale text in IFO card
> chore(aptos-ifo): Update Unlimited Sale text

- packages/uikit/src/widgets/Swap/TradePrice.tsx
> chore(Swap): Change price symbol

- apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
- change vesting title into Unlimited Sale
> fix(aptos-ifo): Update vesting title to Unlimited Sale

- apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
> chore(aptos-Pools): Change ViewProjectSite position

- packages/uikit/src/components/DateStep/DateStep.tsx
> fix(IFO): Fix step icon

- apps/web/src/config/constants/lists.ts
- apps/web/src/hooks/useBUSDPrice.ts
Use API for fiat pricing on Ethereum
> feat(web): USD value for Ethereum

- apps/aptos/pages/swap.tsx
> fix(aptos-Swap): Fix title placement

- apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Info.tsx
- apps/aptos/views/Ifos/hooks/v3/useGetPublicIfoData.ts
> feat(aptos-IFO): Add vesting time info

- apps/web/src/components/Navbar.bmp.tsx
- apps/web/src/utils/mpBridge.ts
> feat: Sync miniprogram connecting status

- apps/web/src/config/wallet.ts
Using getter to delay the installed value
> fix(web): Move all wallets installed as getter

- apps/web/src/config/constants/pools.tsx
Pool info
Token address: 0x4268B8F0B87b6Eae5d897996E6b845ddbD99Adf3
Pool contract address: 0x08287f4942a7b68ddb87d20becd4fdadf4ae206e
Pool token rewards per block: 0.0135
> feat: Add axlUSDC pool

- apps/web/src/views/Farms/hooks/useStakeFarms.ts
- apps/web/src/views/Farms/hooks/useUnstakeFarms.ts
use gasPrice for nonBSC network
> fix: Unstake nonbsc undefined

- apps/aptos/components/Farms/components/FarmTable/Actions/ActionPanel.tsx
- apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
- apps/web/src/views/Farms/components/FarmTable/Row.tsx
- packages/uikit/src/widgets/Farm/components/FarmCard/DetailsSection.tsx
Farms should be placed in the same style as Pools.
> chore(Farms): Modify links placement on mobile

- packages/uikit/src/widgets/Modal/useModal.ts
It is currently creating a new onPresentCallback on each render that causes to change dom
> perf: Use ref to reduce renders in modal

- apps/web/src/views/Farms/components/FarmCard/FarmCard.tsx
- apps/web/src/views/Farms/components/FarmTable/Actions/ActionPanel.tsx
- apps/web/src/views/Farms/components/FarmTable/FarmTable.tsx
- apps/web/src/views/Migration/components/MigrationFarmTable.tsx
- apps/web/src/views/Migration/components/MigrationStep2/NewFarm/FarmRow.tsx
> chore(Farms): LP names should not be forced to uppercase

- packages/uikit/src/components/Footer/Components/SocialLinks.tsx
https://github.com/pancakeswap/pancake-frontend/pull/6102
> style: Fix footer SocialLinks

- apps/web/next.config.mjs
> fix: Image url issue

- apps/blog/components/Article/CardArticle.tsx
- apps/blog/components/Article/SingleArticle/ArticleInfo.tsx
- apps/blog/components/Article/SingleArticle/SimilarArticles.tsx
- apps/blog/components/BlogCard.tsx
- apps/blog/components/ChefsChoice/index.tsx
- apps/blog/components/NewBlog.tsx
- apps/blog/hooks/getArticle.ts
- apps/blog/next.config.mjs
- apps/blog/types.ts
- apps/blog/utils/transformArticle.ts
Reverts pancakeswap/pancake-frontend#6135
> revert: "feat(blog): add next image"

- packages/uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
- packages/uikit/src/components/Svg/Icons/LogoRound.tsx
> fix(Footer): Fix Token is sometimes displayed incorrectly

- packages/uikit/src/widgets/Farm/components/Tags/index.tsx
> chore: Unified tag with outline style

- apps/web/src/views/Home/components/Banners/TrustWalletCampaignBanner.tsx
The style of the button should be consistent with other banners.
> chore(TrustWalletBanner): Add button icon

- apps/web/src/views/Home/components/Banners/TrustWalletCampaignBanner.tsx
> fix(TrustWalletBanner): Fix "Trade Now" icon color

- apps/web/src/views/LimitOrders/index.tsx
> feat(Limit): Show USD price

- packages/uikit/src/widgets/Farm/components/Tags/index.tsx
> fix(Farms): Fix stableLP & Farm Auction tootip placement on mobile

- apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/TotalPurchased.tsx
- apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/IfoVestingCard/index.tsx
- apps/aptos/views/Ifos/components/IfoFoldableCard/IfoPoolCard/index.tsx
> feat(aptos-IFO): Add CAKE commit info when finished

- apps/aptos/components/CurrencyInputPanel/index.tsx
- apps/aptos/components/Liquidity/components/AddLiquidityForm.tsx
- apps/aptos/pages/swap.tsx
> feat(aptos-Swap&Liquidity): Add token USD price

- apps/web/src/components/SubgraphHealthIndicator/index.tsx
> chore(Pottery): Modify tooltip placement

- packages/farms/constants/56.ts
APX-BNB
LP: 0xAf839f4D3620a1EED00cCc21dDC01119C26a75E1
> feat: List APX-BNB LP Farm

- apps/aptos/components/CurrencyInputPanel/index.tsx
- apps/aptos/components/Liquidity/components/ChoosePair.tsx
- apps/aptos/components/Logo/CurrencyLogo.tsx
- apps/aptos/components/SearchModal/CommonBases.tsx
- apps/aptos/config/coins.ts
- apps/aptos/config/constants/exchange.ts
> feat(aptos-Swap&Liquidity): Add common token

- apps/web/src/views/FarmAuction/index.tsx
> chore(AuctionFarm): Add icon of Apply

- apps/web/src/views/Predictions/Leaderboard/components/Results/RankingCard.tsx
- apps/web/src/views/Predictions/Leaderboard/components/Results/ResultAvatar.tsx
- apps/web/src/views/Predictions/Leaderboard/components/WalletStatsModal.tsx
> chore(Prediction): Add BSCScanIcon of Leaderboard

- apps/web/src/views/Info/Pools/PoolPage.tsx
> chore(Info): Modify pairs APR tooltip placement

- apps/web/src/components/SubgraphHealthIndicator/index.tsx
> style(SubgraphHealth): Modify tooltip's Dot align

- apps/aptos/state/user/phishingBanner.ts
- apps/web/src/state/user/hooks/index.tsx
Checking window.location.hostname not showing on aptos web, use VERCEL_ENV insteal
> fix: use vercel env to show phishing banner

- apps/web/src/views/Profile/components/ProfileHeader.tsx
> style(Profiles): Modify BSCScanIcon placement

- apps/web/src/views/Pools/components/PoolCard/CardActions/index.tsx
- apps/web/src/views/Pools/components/PoolsTable/ActionPanel/Harvest.tsx
- packages/uikit/src/widgets/Pool/PoolsTable/HarvestAction.tsx
- packages/uikit/src/widgets/Pool/withCardActions.tsx
> chore(Pools): Earned token not use uppercase

- apps/web/src/views/Farms/components/FarmTable/Row.tsx
- packages/uikit/src/widgets/Farm/components/Tags/index.tsx
> refactor: Show farm tags in mobile in column

- apps/aptos/components/Pools/components/PoolTable/PoolRow.tsx
- apps/web/src/views/Pools/components/PoolsTable/Cells/NameCell.tsx
- packages/uikit/src/widgets/Pool/Cells/BaseCell.tsx
> fix(Pools): Fix token size on mobile when  token name too long

- apps/web/src/pages/_app.tsx
- apps/web/src/utils/customGTMEventTracking.ts
- apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
add token highlight event tracking
> chore: GTM migration plan part 2

- apps/aptos/components/Logo/CurrencyLogo.tsx
- apps/aptos/components/SearchModal/CurrencySearchModal.tsx
- apps/aptos/components/SearchModal/ImportRow.tsx
- apps/aptos/components/SearchModal/ImportToken.tsx
- apps/aptos/components/SearchModal/ManageLists.tsx
- apps/web/src/components/Logo/CurrencyLogo.tsx
- apps/web/src/components/SearchModal/CurrencySearchModal.tsx
- apps/web/src/components/SearchModal/ImportRow.tsx
- apps/web/src/components/SearchModal/ImportToken.tsx
- apps/web/src/components/SearchModal/ManageLists.tsx
- apps/web/src/views/Info/components/CurrencyLogo/index.tsx
- apps/web/src/views/Info/components/InfoTables/TokensTable.tsx
- apps/web/src/views/Swap/components/HotTokenList/SwapTokenTable.tsx
- packages/uikit/src/components/TokenLogo/TokenLogo.tsx
- packages/uikit/src/widgets/Swap/ImportList.tsx
- packages/uikit/src/widgets/Swap/ListLogo.tsx
> feat(Info): Token logo use multiple resources

- apps/web/src/views/Swap/styles.tsx
https://user-images.githubusercontent.com/109973128/224525093-bd9bbcc7-a93b-44e7-bc82-3d15fa041574.MOV
> chore(Swap): Fix horizontal drag issue on mobile

- apps/aptos/components/Menu/Settings/SettingsModal.tsx
- apps/aptos/components/Swap/AdvancedSwapDetails.tsx
- apps/web/src/components/App/AppHeader.tsx
- apps/web/src/components/Menu/GlobalSettings/GasSettings.tsx
- apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
- apps/web/src/components/Menu/GlobalSettings/TransactionSettings.tsx
- apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx
- apps/web/src/views/Swap/components/AdvancedSwapDetails.tsx
- packages/uikit/src/widgets/Liquidity/LiquidityCardHeader.tsx
> chore: Modify QuestionHelper's tooltip placement

- apps/web/src/views/Info/components/InfoCharts/BarChart/index.tsx
- apps/web/src/views/Info/components/InfoCharts/LineChart/index.tsx
- apps/web/src/views/Info/hooks/useChartCallbacks.ts
> fix: Info chart warning when hover

- apps/web/src/config/constants/pools.tsx
- packages/farms/constants/56.ts
Pool info
HAY Token address: 0x0782b6d8c4551B9760e74c0545a9bCD90bdc41E5
Pool contract address: 0x1c7d573d9614187096276a01ec15263fca820bdd
Pool token rewards per block: 0.01210
Farm info
LP symbol: HAY-USDT
Farming LP address: 0xb2aa63f363196caba3154d4187949283f085a488
Note: HAY syrup pool is a reverse syrup pool. users stake HAY to earn Cake
> feat(farm/pool): List HAY

- apps/bridge/components/Menu.tsx
- apps/bridge/components/layerZero/AptosBridgeFooter.tsx
- apps/bridge/components/layerZero/AptosBridgeMessage.tsx
- apps/bridge/components/layerZero/config.ts
- apps/bridge/pages/aptos.tsx
- apps/bridge/pages/cake.tsx
> feat:  Cake Aptos bridge

- apps/web/src/components/Logo/DoubleLogo.tsx
> chore(Liquidity): Modify tokenLogo placement

- apps/web/src/components/SearchModal/CurrencyList.tsx
> fix: Eth token list overlapped

- apps/web/src/components/Modal/Spacer.tsx
- packages/uikit/src/widgets/Modal/Spacer.tsx
> fix: Fix Spacer width

- apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx
- Update transfer token warning message
> chore: Update fee-on transfer token warning message

- apps/web/src/components/Chart/FormattedCurrencyAmount/FormattedCurrencyAmount.tsx
> fix(liquidity): Avoid decimal error when toFix

- apps/web/src/state/farmsV3/hooks.ts
- packages/farms/constants/56.ts
LINK-BNB (0.25% tier) 
0x0e1893beeb4d0913d26b9614b18aea29c56d94b9
XRP-BNB (0.25% tier) -
0xd15b00e81f98a7db25f1dc1ba6e983a4316c4cac
TRX-BUSD (0.25% tier) -
0x71f51e5070c7070b2d079c087bfa814642fcef58
ADA-BNB (0.25% tier) -
0x673516e510d702ab5f2bbf0c6b545111a85f7ea7
DOT-BNB (0.25% tier) -
0x62f0546cbcd684f7c394d8549119e072527c41bc
> feat: List 5 v3 farms

- apps/web/src/views/Migration/components/v3/Step3.tsx
- packages/localization/src/config/translations.json
> fix: Update migration text

- apps/web/src/components/LiquidityCardRow/index.tsx
- apps/web/src/views/Migration/components/v3/Step4.tsx
> chore(Migration): Modify step4 position's tag placement

- apps/web/src/config/constants/pools.tsx
GQ token contract: 0xF700D4c708C2be1463E355F337603183D20E0808
Pool Contract:
0x2f50d0010d408e0c299be8e1a8d553b8eb3e96ed
Reward per block: 7.093
> feat: List GQ pool

- apps/blog/pages/_app.tsx
- apps/bridge/pages/_app.tsx
- apps/web/src/pages/_app.tsx
- apps/web/src/utils/customGTMEventTracking.ts
I will double-check the tracking  status today, and use the preview to test it
> chore: migrate to new gtm

- apps/web/src/views/Migration/components/MigrationSticky.tsx
> fix(Migrarion): SubTitle use safeArea

- apps/web/src/views/AddLiquidityV3/formViews/V3FormView/components/FeeSelector.tsx
- void exception when parsing v3 amount is undefined
> fix(liquidity): Avoid exception when parsing v3 amount is undefined

- apps/web/src/views/AddLiquidityV3/formViews/V2FormView.tsx
> fix(Liquidity): Fix addLiquidityV2 percent issue

- apps/web/src/pages/liquidity/[tokenId].tsx
> chore(Liquidity): Modify claimFees symbol textColor

- apps/web/src/views/AddLiquidityV3/components/AprCalculator.tsx
- packages/uikit/src/widgets/RoiCalculator/DepositAmount.tsx
> fix(Liquidity): Fix tooltip placement

- apps/web/src/views/Farms/components/FarmCard/V3/FarmV3ApyButton.tsx
- apps/web/src/views/Farms/components/FarmCard/V3/FarmV3StakeAndUnStake.tsx
Use ApyLabelContainer for the APR of the LP position
> chore(Farms): UI improvement

- packages/uikit/src/widgets/Farm/components/FarmApyButton/index.tsx
> chore(Farms): Adjust V3 APR placement

- apps/web/src/pages/liquidity/[tokenId].tsx
> chore(Liquidity): Adjust token panel placement

- apps/web/src/config/__tests__/tokens.test.ts
> chore: check test

- packages/uikit/src/widgets/Farm/components/FarmApyButton/index.tsx
> chore(Farms): Adjust APR placement

- apps/web/src/views/Migration/components/MigrationStep1/OldFarm/FarmRow.tsx
- apps/web/src/views/Migration/components/MigrationStep2/NewFarm/FarmRow.tsx
- apps/web/src/views/Migration/components/v3/OldFarmRow.tsx
Before:
https://user-images.githubusercontent.com/109973128/229793192-4ce50038-98f1-46db-89dc-864296e6218a.mov
After:
https://user-images.githubusercontent.com/109973128/229792987-c9d18d46-b14a-43ac-ad20-6f48d0f63826.mov
> fix(Migration): Fix expand logic

- apps/aptos/components/Pools/components/PoolCard/PoolStatsInfo.tsx
- apps/aptos/components/Pools/components/PoolTable/PoolRow.tsx
- packages/localization/src/config/translations.json
- packages/uikit/src/widgets/Pool/Cells/EndsInCell.tsx
- packages/uikit/src/widgets/Pool/index.tsx
> feat(aptos-Pools): Add Ends in cell

- apps/web/src/components/Menu/UserMenu/index.tsx
- packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx
- packages/uikit/src/widgets/Menu/components/UserMenu/types.ts
> chore(UserMenu): SID should not omit text

- apps/web/src/components/Menu/UserMenu/index.tsx
- packages/uikit/src/widgets/Menu/components/UserMenu/index.tsx
- packages/uikit/src/widgets/Menu/components/UserMenu/types.ts
Reverts pancakeswap/pancake-frontend#6377
> revert: Revert "chore(UserMenu): SID should not omit text"

- apps/aptos/components/Pools/components/PoolCard/CollectModal.tsx
- packages/uikit/src/widgets/Pool/CollectModal.tsx
- packages/uikit/src/widgets/Pool/withCollectModal.tsx
> fix(aptos): Fix harvest action

- apps/web/.env
- apps/web/next.config.mjs
- apps/web/src/config/constants/endpoints.ts
- apps/web/src/hooks/useBUSDPrice.ts
- apps/web/src/hooks/useBestAMMTrade.ts
- apps/web/src/state/swap/hooks.ts
Reverts pancakeswap/pancake-frontend#6720
> revert: Revert "chore: Use api for usd quoting"

- apps/web/src/views/Home/components/CakeDataRow.tsx
> chore: Update rate change

- apps/aptos/components/Menu/Menu.tsx
- apps/web/src/components/Menu/index.tsx
- apps/web/src/views/Farms/Farms.tsx
- apps/web/src/views/Farms/FarmsV3.tsx
- packages/uikit/src/__tests__/widgets/menu.test.tsx
- packages/uikit/src/components/CakePrice/CakePrice.tsx
- packages/uikit/src/components/Footer/Footer.tsx
- packages/uikit/src/components/Footer/types.ts
- packages/uikit/src/widgets/Menu/Menu.tsx
- packages/uikit/src/widgets/Menu/types.ts
- Sort latest from v3 to v2 farms
- Add multi chain support in clicking CakePrice component
> chore: sort latest from v3 to v2 in farm

- packages/uikit/src/components/TabMenu/TabMenu.tsx
Reverts pancakeswap/pancake-frontend#6828
> revert: Revert "chore(TabMenu): Padding bottom adjustment"

- apps/web/src/pages/liquid-staking/[currency].tsx
Update liquidity staking referral for ETH
> fix(liquid-staking): Update staking eth

- apps/web/src/views/LiquidStaking/components/LiquidStakingApr.tsx
- packages/localization/src/config/translations.json
> chore(liquid-staking): Update APR text

- apps/web/src/config/nodes.ts
- apps/web/src/utils/viem.ts
- apps/web/src/utils/wagmi.ts
Reverts pancakeswap/pancake-frontend#6993
> revert: "feat: try fallback nodes"

- .changeset/hip-eggs-tie.md
- packages/tokens/package.json
- packages/tokens/tsup.config.ts
Reverts pancakeswap/pancake-frontend#7649
> Revert "chore: Remove invalid dependency"

- .changeset/hip-eggs-tie.md
- packages/tokens/package.json
- packages/tokens/tsup.config.ts
- pnpm-lock.yaml
Reverts pancakeswap/pancake-frontend#7650
> chore: Remove invalid dependency

- apps/web/src/components/GlobalCheckClaimStatus/index.tsx
Reverts pancakeswap/pancake-frontend#7872
> feat: Revert hide AnniversaryAchievementModal

- README.md
> fix: Change the capitalization or case of text in readme

- apps/web/src/views/FixedStaking/constant.ts
Reverts pancakeswap/pancake-frontend#8024
> Revert "chore: Enable BNB"

- apps/web/src/hooks/useRefreshEffect.test.ts
- apps/web/src/hooks/useRefreshEffect.ts
- apps/web/src/state/block/hooks.ts
- apps/web/src/state/multicall/hooks.ts
- apps/web/src/testUtils.tsx
Reverts pancakeswap/pancake-frontend#8237
> Revert "refactor: Use query in block hooks"

- apps/web/src/config/nodes.ts
Reverts pancakeswap/pancake-frontend#8324
> Revert "chore: Default to use pokt on polygon"

- apps/web/src/config/wallchain.ts
- apps/web/src/views/Swap/V3Swap/hooks/useWallchain.ts
> feat: Process more tokens with Wallchain

- apps/aptos/package.json
- apps/blog/package.json
- apps/bridge/package.json
- apps/games/package.json
- apps/web/next.config.mjs
- apps/web/package.json
- apps/web/src/testUtils.tsx
- apps/web/src/views/TradingCompetition/Footer.tsx
- apps/web/src/views/TradingCompetition/components/FinishedCompetitionBanner/index.tsx
- apps/web/src/views/TradingCompetition/components/ShareImageModal.tsx
- apps/web/src/views/TradingCompetition/components/TeamRanks/TeamRanksWithParticipants.tsx
- apps/web/src/views/TradingCompetition/components/YourScore/ScoreCard.tsx
- apps/web/src/views/TradingCompetition/types.ts
- examples/playground/package.json
- packages/next-config/package.json
- packages/widgets-internal/package.json
- pnpm-lock.yaml
Reverts pancakeswap/pancake-frontend#8314
> chore: Revert nextjs bump

- apps/web/src/config/wallet.ts
- apps/web/src/hooks/useEagerConnect.bmp.ts
- apps/web/src/utils/wagmi.ts
- package.json
- packages/ifos/package.json
- packages/pools/package.json
- packages/position-managers/package.json
- packages/uikit/package.json
- packages/wagmi/package.json
- pnpm-lock.yaml
Reverts pancakeswap/pancake-frontend#8576
> revert: "chore: Remove ledger"

- apps/web/src/config/wallet.ts
- apps/web/src/utils/wagmi.ts
Reverts pancakeswap/pancake-frontend#8580
> chore: Ledger connector

- .github/workflows/release.yml
- package.json
- pnpm-lock.yaml
> chore: Update changesets

- apps/web/package.json
- pnpm-lock.yaml
> chore: Update binance w3w

- packages/widgets-internal/roi/aprHelper.ts
- packages/widgets-internal/roi/hooks/useRate.ts
> fix: v3 Roi calculator display

- apps/web/next.config.mjs
> feat: 🎸 Try to optimize the build speed

- apps/web/src/hooks/infinity/useInfinityCakeAPR.ts
- apps/web/src/state/farmsV4/state/extendPools/hooks.ts
- apps/web/src/views/universalFarms/hooks/usePositionAPR.ts
> fix(PAN-5002): derived bin pool liquidity & lp fee

- apps/web/src/components/SearchModal/CurrencySearch.tsx
- apps/web/src/components/SearchModal/CurrencySearchModal.tsx
- apps/web/src/components/SearchModal/SwapNetworkSelection.tsx
> fix: PAN 6313
